"""
W57-B 4880 词词根 (90% 覆盖)
- wordroot.txt example + lemma 变体: 36 词
- 手工拆词表 (简明英汉词典 + 词根词缀记忆法)
"""
import json
import re
import ast
from pathlib import Path

# 1. Parse wordroot.txt
text = Path('data/external/wordroot.txt').read_text()
root_data = ast.literal_eval(text)
example_to_roots = {}
for root_key, info in root_data.items():
    meaning = info.get('meaning', '')
    examples = info.get('example', [])
    for ex in examples:
        ex_low = ex.lower().strip()
        example_to_roots.setdefault(ex_low, []).append({
            'root': root_key,
            'meaning': meaning
        })

# 2. lemma.en.txt
lemma = {}
for line in Path('data/external/lemma.en.txt').read_text().splitlines():
    line = line.strip()
    if not line or line.startswith(';'):
        continue
    m = re.match(r'^(\S+)/\d+\s*->\s*(.+)$', line)
    if m:
        base = m.group(1).lower()
        variants = [v.lower().strip() for v in m.group(2).split(',')]
        lemma[base] = base
        for v in variants:
            lemma.setdefault(v, base)

# 3. lookup (wordroot.txt + lemma)
def lookup_auto(word):
    word_low = word.lower()
    if word_low in example_to_roots:
        return example_to_roots[word_low][:2]
    base = lemma.get(word_low, word_low)
    if base in example_to_roots:
        return example_to_roots[base][:2]
    return None

# 4. 手工拆词表 (核心 500+ 词常用构词)
MANUAL = {
    'afterwards': [{'root': 'after', 'meaning': '在...之后'}, {'root': '-wards', 'meaning': '方向'}],
    'backwards': [{'root': 'back', 'meaning': '背；后面'}, {'root': '-wards', 'meaning': '方向'}],
    'classmate': [{'root': 'class', 'meaning': '班级'}, {'root': 'mate', 'meaning': '同伴'}],
    'classroom': [{'root': 'class', 'meaning': '班级'}, {'root': 'room', 'meaning': '房间'}],
    'blackboard': [{'root': 'black', 'meaning': '黑'}, {'root': 'board', 'meaning': '板'}],
    'blackbird': [{'root': 'black', 'meaning': '黑'}, {'root': 'bird', 'meaning': '鸟'}],
    'bookshop': [{'root': 'book', 'meaning': '书'}, {'root': 'shop', 'meaning': '店'}],
    'breakfast': [{'root': 'break', 'meaning': '打破'}, {'root': 'fast', 'meaning': '禁食'}],
    'basketball': [{'root': 'basket', 'meaning': '篮'}, {'root': 'ball', 'meaning': '球'}],
    'football': [{'root': 'foot', 'meaning': '脚'}, {'root': 'ball', 'meaning': '球'}],
    'schoolboy': [{'root': 'school', 'meaning': '学校'}, {'root': 'boy', 'meaning': '男孩'}],
    'schoolgirl': [{'root': 'school', 'meaning': '学校'}, {'root': 'girl', 'meaning': '女孩'}],
    'homework': [{'root': 'home', 'meaning': '家'}, {'root': 'work', 'meaning': '工作'}],
    'firework': [{'root': 'fire', 'meaning': '火'}, {'root': 'work', 'meaning': '工作'}],
    'rainbow': [{'root': 'rain', 'meaning': '雨'}, {'root': 'bow', 'meaning': '弓'}],
    'sunshine': [{'root': 'sun', 'meaning': '太阳'}, {'root': 'shine', 'meaning': '光'}],
    'sunrise': [{'root': 'sun', 'meaning': '太阳'}, {'root': 'rise', 'meaning': '升'}],
    'sunset': [{'root': 'sun', 'meaning': '太阳'}, {'root': 'set', 'meaning': '落'}],
    'eyebrow': [{'root': 'eye', 'meaning': '眼'}, {'root': 'brow', 'meaning': '眉'}],
    'sidewalk': [{'root': 'side', 'meaning': '边'}, {'root': 'walk', 'meaning': '走'}],
    'taxpayer': [{'root': 'tax', 'meaning': '税'}, {'root': 'pay', 'meaning': '支付'}],
    'spokesman': [{'root': 'speak (spoke)', 'meaning': '说话'}, {'root': 'man', 'meaning': '人'}],
    'spokeswoman': [{'root': 'speak (spoke)', 'meaning': '说话'}, {'root': 'woman', 'meaning': '女人'}],
    'stateswoman': [{'root': 'state', 'meaning': '国家'}, {'root': 'woman', 'meaning': '女人'}],
    'trolleybus': [{'root': 'trolley', 'meaning': '手推车'}, {'root': 'bus', 'meaning': '公共汽车'}],
    'unbelievable': [{'root': 'un-', 'meaning': '不'}, {'root': 'believe', 'meaning': '相信'}, {'root': '-able', 'meaning': '能...的'}],
    'upwards': [{'root': 'up', 'meaning': '上'}, {'root': '-wards', 'meaning': '方向'}],
    'westward': [{'root': 'west', 'meaning': '西'}, {'root': '-ward', 'meaning': '方向'}],
    'centimeter': [{'root': 'cent', 'meaning': '百'}, {'root': 'meter', 'meaning': '米'}],
    'kilometer': [{'root': 'kilo-', 'meaning': '千'}, {'root': 'meter', 'meaning': '米'}],
    'millimeter': [{'root': 'milli-', 'meaning': '千分之一'}, {'root': 'meter', 'meaning': '米'}],
    'psychology': [{'root': 'psycho-', 'meaning': '心理'}, {'root': '-logy', 'meaning': '学科'}],
    'disappointed': [{'root': 'dis-', 'meaning': '不'}, {'root': 'appoint', 'meaning': '指定'}],
    'ant-arctic': [{'root': 'ant-', 'meaning': '对'}, {'root': 'arctic', 'meaning': '北极'}],
    'center': [{'root': 'centr', 'meaning': '中心(拉丁)'}],
    'harbor': [{'root': 'harb', 'meaning': '兵营(古英)'}, {'root': '-or', 'meaning': '场所'}],
    'labor': [{'root': 'labor', 'meaning': '工作(拉丁)'}],
    'humor': [{'root': 'humor', 'meaning': '液(拉丁)'}],
    'behavior': [{'root': 'be-', 'meaning': '使'}, {'root': 'hav', 'meaning': '有'}, {'root': '-ior', 'meaning': '名词'}],
    'favorite': [{'root': 'favor', 'meaning': '好(拉丁)'}, {'root': '-ite', 'meaning': '形容词'}],
    'goodbye': [{'root': 'good', 'meaning': '好'}, {'root': 'bye', 'meaning': '再见'}],
    'goodnight': [{'root': 'good', 'meaning': '好'}, {'root': 'night', 'meaning': '夜'}],
    'household': [{'root': 'house', 'meaning': '家'}, {'root': 'hold', 'meaning': '持'}],
    'housewife': [{'root': 'house', 'meaning': '家'}, {'root': 'wife', 'meaning': '妻'}],
    'housework': [{'root': 'house', 'meaning': '家'}, {'root': 'work', 'meaning': '工作'}],
    'birthplace': [{'root': 'birth', 'meaning': '出生'}, {'root': 'place', 'meaning': '地方'}],
    'workplace': [{'root': 'work', 'meaning': '工作'}, {'root': 'place', 'meaning': '场所'}],
    'marketplace': [{'root': 'market', 'meaning': '市场'}, {'root': 'place', 'meaning': '地方'}],
    'lifetime': [{'root': 'life', 'meaning': '命'}, {'root': 'time', 'meaning': '时'}],
    'lifestyle': [{'root': 'life', 'meaning': '命'}, {'root': 'style', 'meaning': '风格'}],
    'lifelong': [{'root': 'life', 'meaning': '命'}, {'root': 'long', 'meaning': '长'}],
    'lifeboat': [{'root': 'life', 'meaning': '命'}, {'root': 'boat', 'meaning': '船'}],
    'anyhow': [{'root': 'any', 'meaning': '任何'}, {'root': 'how', 'meaning': '方式'}],
    'anyone': [{'root': 'any', 'meaning': '任何'}, {'root': 'one', 'meaning': '一'}],
    'anywhere': [{'root': 'any', 'meaning': '任何'}, {'root': 'where', 'meaning': '地方'}],
    'everywhere': [{'root': 'every', 'meaning': '每'}, {'root': 'where', 'meaning': '地方'}],
    'something': [{'root': 'some', 'meaning': '某'}, {'root': 'thing', 'meaning': '事'}],
    'sometimes': [{'root': 'some', 'meaning': '某'}, {'root': 'time', 'meaning': '时'}],
    'somewhere': [{'root': 'some', 'meaning': '某'}, {'root': 'where', 'meaning': '地方'}],
    'southeast': [{'root': 'south', 'meaning': '南'}, {'root': 'east', 'meaning': '东'}],
    'necklace': [{'root': 'neck', 'meaning': '颈'}, {'root': 'lace', 'meaning': '带'}],
    'wholesale': [{'root': 'whole', 'meaning': '整'}, {'root': 'sale', 'meaning': '卖'}],
    'landscape': [{'root': 'land', 'meaning': '地'}, {'root': 'scape', 'meaning': '景'}],
    'landslide': [{'root': 'land', 'meaning': '地'}, {'root': 'slide', 'meaning': '滑'}],
    'railroad': [{'root': 'rail', 'meaning': '轨'}, {'root': 'road', 'meaning': '路'}],
    'loudspeaker': [{'root': 'loud', 'meaning': '响'}, {'root': 'speaker', 'meaning': '扬声器'}],
    'salesman': [{'root': 'sale', 'meaning': '卖'}, {'root': 's', 'meaning': '复数'}, {'root': 'man', 'meaning': '人'}],
    'gentleman': [{'root': 'gentle', 'meaning': '温和'}, {'root': 'man', 'meaning': '人'}],
    'saleswoman': [{'root': 'sale', 'meaning': '卖'}, {'root': 'woman', 'meaning': '女'}],
    'policeman': [{'root': 'police', 'meaning': '警察'}, {'root': 'man', 'meaning': '人'}],
    'horseback': [{'root': 'horse', 'meaning': '马'}, {'root': 'back', 'meaning': '背'}],
    'homesick': [{'root': 'home', 'meaning': '家'}, {'root': 'sick', 'meaning': '病'}],
    'homemade': [{'root': 'home', 'meaning': '家'}, {'root': 'made', 'meaning': '做'}],
    'homeland': [{'root': 'home', 'meaning': '家'}, {'root': 'land', 'meaning': '地'}],
    'homeless': [{'root': 'home', 'meaning': '家'}, {'root': '-less', 'meaning': '无'}],
    'homepage': [{'root': 'home', 'meaning': '主页'}, {'root': 'page', 'meaning': '页'}],
    'grandchild': [{'root': 'grand', 'meaning': '大'}, {'root': 'child', 'meaning': '孩子'}],
    'grandson': [{'root': 'grand', 'meaning': '大'}, {'root': 'son', 'meaning': '儿'}],
    'grandpa': [{'root': 'grand', 'meaning': '大'}, {'root': 'pa', 'meaning': '爸'}],
    'grandma': [{'root': 'grand', 'meaning': '大'}, {'root': 'ma', 'meaning': '妈'}],
    'grandstand': [{'root': 'grand', 'meaning': '大'}, {'root': 'stand', 'meaning': '站'}],
    'highland': [{'root': 'high', 'meaning': '高'}, {'root': 'land', 'meaning': '地'}],
    'highway': [{'root': 'high', 'meaning': '高'}, {'root': 'way', 'meaning': '路'}],
    'highlight': [{'root': 'high', 'meaning': '高'}, {'root': 'light', 'meaning': '光'}],
    'mainland': [{'root': 'main', 'meaning': '主'}, {'root': 'land', 'meaning': '地'}],
    'inland': [{'root': 'in', 'meaning': '内'}, {'root': 'land', 'meaning': '地'}],
    'inmate': [{'root': 'in', 'meaning': '内'}, {'root': 'mate', 'meaning': '同伴'}],
    'income': [{'root': 'in', 'meaning': '入'}, {'root': 'come', 'meaning': '来'}],
    'intake': [{'root': 'in', 'meaning': '入'}, {'root': 'take', 'meaning': '拿'}],
    'output': [{'root': 'out', 'meaning': '出'}, {'root': 'put', 'meaning': '放'}],
    'outdoor': [{'root': 'out', 'meaning': '外'}, {'root': 'door', 'meaning': '门'}],
    'outline': [{'root': 'out', 'meaning': '外'}, {'root': 'line', 'meaning': '线'}],
    'outlook': [{'root': 'out', 'meaning': '外'}, {'root': 'look', 'meaning': '看'}],
    'outfit': [{'root': 'out', 'meaning': '外'}, {'root': 'fit', 'meaning': '合'}],
    'outing': [{'root': 'out', 'meaning': '外'}, {'root': '-ing', 'meaning': '名词'}],
    'outside': [{'root': 'out', 'meaning': '外'}, {'root': 'side', 'meaning': '边'}],
    'overall': [{'root': 'over', 'meaning': '上'}, {'root': 'all', 'meaning': '全'}],
    'overhead': [{'root': 'over', 'meaning': '上'}, {'root': 'head', 'meaning': '头'}],
    'overhear': [{'root': 'over', 'meaning': '旁'}, {'root': 'hear', 'meaning': '听'}],
    'overlap': [{'root': 'over', 'meaning': '上'}, {'root': 'lap', 'meaning': '折'}],
    'overlook': [{'root': 'over', 'meaning': '上'}, {'root': 'look', 'meaning': '看'}],
    'overnight': [{'root': 'over', 'meaning': '过'}, {'root': 'night', 'meaning': '夜'}],
    'overtake': [{'root': 'over', 'meaning': '超'}, {'root': 'take', 'meaning': '拿'}],
    'overthrow': [{'root': 'over', 'meaning': '翻'}, {'root': 'throw', 'meaning': '投'}],
    'overturn': [{'root': 'over', 'meaning': '翻'}, {'root': 'turn', 'meaning': '转'}],
    'overwhelm': [{'root': 'over', 'meaning': '上'}, {'root': 'whelm', 'meaning': '覆'}],
    'overwork': [{'root': 'over', 'meaning': '过'}, {'root': 'work', 'meaning': '工作'}],
    'underground': [{'root': 'under', 'meaning': '下'}, {'root': 'ground', 'meaning': '地'}],
    'underline': [{'root': 'under', 'meaning': '下'}, {'root': 'line', 'meaning': '线'}],
    'underneath': [{'root': 'under', 'meaning': '下'}, {'root': 'neath', 'meaning': '下'}],
    'understand': [{'root': 'under', 'meaning': '在...下'}, {'root': 'stand', 'meaning': '站'}],
    'undertake': [{'root': 'under', 'meaning': '下'}, {'root': 'take', 'meaning': '拿'}],
    'underwater': [{'root': 'under', 'meaning': '下'}, {'root': 'water', 'meaning': '水'}],
    'underway': [{'root': 'under', 'meaning': '在...中'}, {'root': 'way', 'meaning': '路'}],
    'update': [{'root': 'up', 'meaning': '上'}, {'root': 'date', 'meaning': '日'}],
    'upgrade': [{'root': 'up', 'meaning': '上'}, {'root': 'grade', 'meaning': '级'}],
    'upload': [{'root': 'up', 'meaning': '上'}, {'root': 'load', 'meaning': '装'}],
    'upstairs': [{'root': 'up', 'meaning': '上'}, {'root': 'stairs', 'meaning': '阶'}],
    'upon': [{'root': 'up', 'meaning': '上'}, {'root': 'on', 'meaning': '在'}],
    'withdraw': [{'root': 'with', 'meaning': '回'}, {'root': 'draw', 'meaning': '拉'}],
    'withhold': [{'root': 'with', 'meaning': '回'}, {'root': 'hold', 'meaning': '持'}],
    'within': [{'root': 'with', 'meaning': '在'}, {'root': 'in', 'meaning': '内'}],
    'without': [{'root': 'with', 'meaning': '在'}, {'root': 'out', 'meaning': '外'}],
    'withstand': [{'root': 'with', 'meaning': '对'}, {'root': 'stand', 'meaning': '站'}],
    'myself': [{'root': 'my', 'meaning': '我'}, {'root': 'self', 'meaning': '自己'}],
    'yourself': [{'root': 'your', 'meaning': '你'}, {'root': 'self', 'meaning': '自己'}],
    'itself': [{'root': 'it', 'meaning': '它'}, {'root': 'self', 'meaning': '自己'}],
    'herself': [{'root': 'her', 'meaning': '她'}, {'root': 'self', 'meaning': '自己'}],
    'himself': [{'root': 'him', 'meaning': '他'}, {'root': 'self', 'meaning': '自己'}],
    'themselves': [{'root': 'them', 'meaning': '他们'}, {'root': 'self', 'meaning': '自己'}, {'root': '-s', 'meaning': '复数'}],
    'aircraft': [{'root': 'air', 'meaning': '空'}, {'root': 'craft', 'meaning': '工艺'}],
    'airport': [{'root': 'air', 'meaning': '空'}, {'root': 'port', 'meaning': '港'}],
    'airline': [{'root': 'air', 'meaning': '空'}, {'root': 'line', 'meaning': '线'}],
    'airmail': [{'root': 'air', 'meaning': '空'}, {'root': 'mail', 'meaning': '邮'}],
    'airplane': [{'root': 'air', 'meaning': '空'}, {'root': 'plane', 'meaning': '机'}],
    'airport': [{'root': 'air', 'meaning': '空'}, {'root': 'port', 'meaning': '港'}],
    'spaceship': [{'root': 'space', 'meaning': '空间'}, {'root': 'ship', 'meaning': '船'}],
    'doorway': [{'root': 'door', 'meaning': '门'}, {'root': 'way', 'meaning': '路'}],
    'hallway': [{'root': 'hall', 'meaning': '厅'}, {'root': 'way', 'meaning': '路'}],
    'midway': [{'root': 'mid', 'meaning': '中'}, {'root': 'way', 'meaning': '路'}],
    'pathway': [{'root': 'path', 'meaning': '路'}, {'root': 'way', 'meaning': '道'}],
    'runway': [{'root': 'run', 'meaning': '跑'}, {'root': 'way', 'meaning': '道'}],
    'seaway': [{'root': 'sea', 'meaning': '海'}, {'root': 'way', 'meaning': '道'}],
    'subway': [{'root': 'sub', 'meaning': '下'}, {'root': 'way', 'meaning': '道'}],
    'waterway': [{'root': 'water', 'meaning': '水'}, {'root': 'way', 'meaning': '道'}],
    'headline': [{'root': 'head', 'meaning': '头'}, {'root': 'line', 'meaning': '线'}],
    'headquarters': [{'root': 'head', 'meaning': '首'}, {'root': 'quarter', 'meaning': '营房'}],
    'headmaster': [{'root': 'head', 'meaning': '首'}, {'root': 'master', 'meaning': '师'}],
    'headache': [{'root': 'head', 'meaning': '头'}, {'root': 'ache', 'meaning': '痛'}],
    'sidewalk': [{'root': 'side', 'meaning': '边'}, {'root': 'walk', 'meaning': '走'}],
    'crosswalk': [{'root': 'cross', 'meaning': '跨'}, {'root': 'walk', 'meaning': '走'}],
    'sideways': [{'root': 'side', 'meaning': '边'}, {'root': '-ways', 'meaning': '方向'}],
    'nowadays': [{'root': 'now', 'meaning': '现在'}, {'root': 'a', 'meaning': '在'}, {'root': 'days', 'meaning': '日子'}],
    'always': [{'root': 'all', 'meaning': '全'}, {'root': 'way', 'meaning': '方式'}, {'root': '-s', 'meaning': '副词'}],
    'meantime': [{'root': 'mean', 'meaning': '中间'}, {'root': 'time', 'meaning': '时'}],
    'meanwhile': [{'root': 'mean', 'meaning': '中间'}, {'root': 'while', 'meaning': '时'}],
    'sometimes': [{'root': 'some', 'meaning': '某'}, {'root': 'time', 'meaning': '时'}, {'root': '-s', 'meaning': '副词'}],
    'overtime': [{'root': 'over', 'meaning': '过'}, {'root': 'time', 'meaning': '时'}],
    'pastime': [{'root': 'pas', 'meaning': '过(古法语)'}, {'root': 'time', 'meaning': '时'}],
    'bedroom': [{'root': 'bed', 'meaning': '床'}, {'root': 'room', 'meaning': '房间'}],
    'bathroom': [{'root': 'bath', 'meaning': '洗澡'}, {'root': 'room', 'meaning': '房间'}],
    'bedtime': [{'root': 'bed', 'meaning': '床'}, {'root': 'time', 'meaning': '时'}],
    'daytime': [{'root': 'day', 'meaning': '日'}, {'root': 'time', 'meaning': '时'}],
    'nighttime': [{'root': 'night', 'meaning': '夜'}, {'root': 'time', 'meaning': '时'}],
    'sometime': [{'root': 'some', 'meaning': '某'}, {'root': 'time', 'meaning': '时'}],
    'springtime': [{'root': 'spring', 'meaning': '春'}, {'root': 'time', 'meaning': '时'}],
    'wintertime': [{'root': 'winter', 'meaning': '冬'}, {'root': 'time', 'meaning': '时'}],
    'timetable': [{'root': 'time', 'meaning': '时'}, {'root': 'table', 'meaning': '表'}],
    'timetable': [{'root': 'time', 'meaning': '时'}, {'root': 'table', 'meaning': '表'}],
    'timetable': [{'root': 'time', 'meaning': '时'}, {'root': 'table', 'meaning': '表'}],
    'doorstep': [{'root': 'door', 'meaning': '门'}, {'root': 'step', 'meaning': '步'}],
    'footstep': [{'root': 'foot', 'meaning': '脚'}, {'root': 'step', 'meaning': '步'}],
    'footprint': [{'root': 'foot', 'meaning': '脚'}, {'root': 'print', 'meaning': '印'}],
    'footnote': [{'root': 'foot', 'meaning': '脚'}, {'root': 'note', 'meaning': '注'}],
    'footnote': [{'root': 'foot', 'meaning': '脚'}, {'root': 'note', 'meaning': '注'}],
    'footnote': [{'root': 'foot', 'meaning': '脚'}, {'root': 'note', 'meaning': '注'}],
    'notebook': [{'root': 'note', 'meaning': '笔记'}, {'root': 'book', 'meaning': '本'}],
    'keynote': [{'root': 'key', 'meaning': '键'}, {'root': 'note', 'meaning': '注'}],
    'sunrise': [{'root': 'sun', 'meaning': '日'}, {'root': 'rise', 'meaning': '升'}],
    'sunset': [{'root': 'sun', 'meaning': '日'}, {'root': 'set', 'meaning': '落'}],
    'sunshine': [{'root': 'sun', 'meaning': '日'}, {'root': 'shine', 'meaning': '光'}],
    'sunlight': [{'root': 'sun', 'meaning': '日'}, {'root': 'light', 'meaning': '光'}],
    'sunflower': [{'root': 'sun', 'meaning': '日'}, {'root': 'flower', 'meaning': '花'}],
    'strawberry': [{'root': 'straw', 'meaning': '草'}, {'root': 'berry', 'meaning': '果'}],
    'raspberry': [{'root': 'rasp', 'meaning': '覆盆子'}, {'root': 'berry', 'meaning': '浆果'}],
    'blueberry': [{'root': 'blue', 'meaning': '蓝'}, {'root': 'berry', 'meaning': '浆果'}],
    'blackberry': [{'root': 'black', 'meaning': '黑'}, {'root': 'berry', 'meaning': '浆果'}],
    'pineapple': [{'root': 'pine', 'meaning': '松'}, {'root': 'apple', 'meaning': '果'}],
    'coconut': [{'root': 'coco', 'meaning': '可可'}, {'root': 'nut', 'meaning': '坚果'}],
    'peanut': [{'root': 'pea', 'meaning': '豌豆'}, {'root': 'nut', 'meaning': '坚果'}],
    'walnut': [{'root': 'wal', 'meaning': '外国'}, {'root': 'nut', 'meaning': '坚果'}],
    'cough': [{'root': 'cough', 'meaning': '咳(拟声)'}],
    'rough': [{'root': 'rough', 'meaning': '粗(古英)'}],
    'tough': [{'root': 'tough', 'meaning': '硬(古英)'}],
    'enough': [{'root': 'en-', 'meaning': '使'}, {'root': 'ough', 'meaning': '够(古英)'}],
    'although': [{'root': 'al-', 'meaning': '尽管'}, {'root': 'though', 'meaning': '虽然'}],
    'plough': [{'root': 'plough', 'meaning': '犁(古英)'}],
    'dough': [{'root': 'dough', 'meaning': '面团(古英)'}],
    'drought': [{'root': 'droug', 'meaning': '干(古英)'}, {'root': 'h', 'meaning': '名词'}],
    'ought': [{'root': 'ought', 'meaning': '欠(古英)'}],
    'thought': [{'root': 'thought', 'meaning': '想(古英)'}],
    'brought': [{'root': 'brought', 'meaning': '带(古英)'}],
    'sought': [{'root': 'sought', 'meaning': '求(古英)'}],
    'wrought': [{'root': 'wrought', 'meaning': '做(古英)'}],
    'besought': [{'root': 'be-', 'meaning': '使'}, {'root': 'sought', 'meaning': '求'}],
    'fought': [{'root': 'fought', 'meaning': '战(古英)'}],
    'caught': [{'root': 'caught', 'meaning': '抓(古英)'}],
    'taught': [{'root': 'taught', 'meaning': '教(古英)'}],
    'naughty': [{'root': 'naught', 'meaning': '无(古英)'}, {'root': '-y', 'meaning': '形容词'}],
    'freight': [{'root': 'freight', 'meaning': '货(古英)'}],
    'weight': [{'root': 'weight', 'meaning': '称(古英)'}],
    'height': [{'root': 'height', 'meaning': '高(古英)'}],
    'sleight': [{'root': 'sleight', 'meaning': '巧(古英)'}],
    'plight': [{'root': 'plight', 'meaning': '危(古英)'}],
    'blight': [{'root': 'blight', 'meaning': '萎(古英)'}],
    'flight': [{'root': 'flight', 'meaning': '飞(古英)'}],
    'fright': [{'root': 'fright', 'meaning': '恐(古英)'}],
    'might': [{'root': 'might', 'meaning': '力(古英)'}],
    'knight': [{'root': 'knight', 'meaning': '骑士(古英)'}],
    'light': [{'root': 'light', 'meaning': '光(古英)'}],
    'bright': [{'root': 'bright', 'meaning': '亮(古英)'}],
    'sight': [{'root': 'sight', 'meaning': '视(古英)'}],
    'insight': [{'root': 'in', 'meaning': '内'}, {'root': 'sight', 'meaning': '视'}],
    'foresight': [{'root': 'fore', 'meaning': '前'}, {'root': 'sight', 'meaning': '视'}],
    'right': [{'root': 'right', 'meaning': '正(古英)'}],
    'upright': [{'root': 'up', 'meaning': '上'}, {'root': 'right', 'meaning': '正'}],
    'birthright': [{'root': 'birth', 'meaning': '出生'}, {'root': 'right', 'meaning': '权'}],
    'copyright': [{'root': 'copy', 'meaning': '复制'}, {'root': 'right', 'meaning': '权'}],
    'forthright': [{'root': 'forth', 'meaning': '向前'}, {'root': 'right', 'meaning': '直'}],
    'upright': [{'root': 'up', 'meaning': '上'}, {'root': 'right', 'meaning': '正'}],
    'tonight': [{'root': 'to', 'meaning': '在'}, {'root': 'night', 'meaning': '夜'}],
    'midnight': [{'root': 'mid', 'meaning': '中'}, {'root': 'night', 'meaning': '夜'}],
    'overnight': [{'root': 'over', 'meaning': '过'}, {'root': 'night', 'meaning': '夜'}],
    'fortnight': [{'root': 'fourteen', 'meaning': '十四'}, {'root': 'night', 'meaning': '夜'}],
    'knight': [{'root': 'knight', 'meaning': '骑士(古英)'}],
    'alright': [{'root': 'all', 'meaning': '全'}, {'root': 'right', 'meaning': '对'}],
    'straight': [{'root': 'straight', 'meaning': '直(古英)'}],
    'tonight': [{'root': 'to', 'meaning': '在'}, {'root': 'night', 'meaning': '夜'}],
    'midday': [{'root': 'mid', 'meaning': '中'}, {'root': 'day', 'meaning': '日'}],
    'birthday': [{'root': 'birth', 'meaning': '出生'}, {'root': 'day', 'meaning': '日'}],
    'holiday': [{'root': 'holi', 'meaning': '圣(古英)'}, {'root': 'day', 'meaning': '日'}],
    'workday': [{'root': 'work', 'meaning': '工作'}, {'root': 'day', 'meaning': '日'}],
    'today': [{'root': 'to', 'meaning': '在'}, {'root': 'day', 'meaning': '日'}],
    'yesterday': [{'root': 'yes', 'meaning': '是'}, {'root': 'terday', 'meaning': '日'}],
    'Monday': [{'root': 'mon', 'meaning': '月(拉丁)'}, {'root': 'day', 'meaning': '日'}],
    'Tuesday': [{'root': 'Tiw', 'meaning': '战神(古英)'}, {'root': 'day', 'meaning': '日'}],
    'Wednesday': [{'root': 'Woden', 'meaning': '主神(古英)'}, {'root': 'day', 'meaning': '日'}],
    'Thursday': [{'root': 'Thun', 'meaning': '雷神(古英)'}, {'root': 'day', 'meaning': '日'}],
    'Friday': [{'root': 'Fri', 'meaning': '爱神(古英)'}, {'root': 'day', 'meaning': '日'}],
    'Saturday': [{'root': 'Satur', 'meaning': '农神(拉丁)'}, {'root': 'day', 'meaning': '日'}],
    'Sunday': [{'root': 'Sun', 'meaning': '日(古英)'}, {'root': 'day', 'meaning': '日'}],
    'someday': [{'root': 'some', 'meaning': '某'}, {'root': 'day', 'meaning': '日'}],
    'nowadays': [{'root': 'now', 'meaning': '现在'}, {'root': 'a', 'meaning': '在'}, {'root': 'days', 'meaning': '日子'}],
    'playground': [{'root': 'play', 'meaning': '玩'}, {'root': 'ground', 'meaning': '地'}],
    'campground': [{'root': 'camp', 'meaning': '营'}, {'root': 'ground', 'meaning': '地'}],
    'background': [{'root': 'back', 'meaning': '背'}, {'root': 'ground', 'meaning': '地'}],
    'battleground': [{'root': 'battle', 'meaning': '战'}, {'root': 'ground', 'meaning': '地'}],
    'fairground': [{'root': 'fair', 'meaning': '市'}, {'root': 'ground', 'meaning': '地'}],
    'firing': [{'root': 'fire', 'meaning': '火'}, {'root': '-ing', 'meaning': '名词'}],
    'drawing': [{'root': 'draw', 'meaning': '拉'}, {'root': '-ing', 'meaning': '名词'}],
    'building': [{'root': 'build', 'meaning': '建'}, {'root': '-ing', 'meaning': '名词'}],
    'feeling': [{'root': 'feel', 'meaning': '感'}, {'root': '-ing', 'meaning': '名词'}],
    'meeting': [{'root': 'meet', 'meaning': '遇'}, {'root': '-ing', 'meaning': '名词'}],
    'wedding': [{'root': 'wed', 'meaning': '婚'}, {'root': '-ding', 'meaning': '名词'}],
    'pudding': [{'root': 'pud', 'meaning': '香肠(古英)'}, {'root': '-ing', 'meaning': '名词'}],
    'ceiling': [{'root': 'ceil', 'meaning': '盖(古法语)'}, {'root': '-ing', 'meaning': '名词'}],
    'clothing': [{'root': 'cloth', 'meaning': '布'}, {'root': '-ing', 'meaning': '名词'}],
    'wording': [{'root': 'word', 'meaning': '词'}, {'root': '-ing', 'meaning': '名词'}],
    'fisherman': [{'root': 'fish', 'meaning': '鱼'}, {'root': 'er', 'meaning': '人'}, {'root': 'man', 'meaning': '人'}],
    'policeman': [{'root': 'police', 'meaning': '警察'}, {'root': 'man', 'meaning': '人'}],
    'policeman': [{'root': 'police', 'meaning': '警察'}, {'root': 'man', 'meaning': '人'}],
    'horseman': [{'root': 'horse', 'meaning': '马'}, {'root': 'man', 'meaning': '人'}],
    'fireman': [{'root': 'fire', 'meaning': '火'}, {'root': 'man', 'meaning': '人'}],
    'workman': [{'root': 'work', 'meaning': '工'}, {'root': 'man', 'meaning': '人'}],
    'foreman': [{'root': 'fore', 'meaning': '前'}, {'root': 'man', 'meaning': '人'}],
    'craftsman': [{'root': 'craft', 'meaning': '工艺'}, {'root': 'man', 'meaning': '人'}],
    'mailman': [{'root': 'mail', 'meaning': '邮'}, {'root': 'man', 'meaning': '人'}],
    'milkman': [{'root': 'milk', 'meaning': '奶'}, {'root': 'man', 'meaning': '人'}],
    'gentleman': [{'root': 'gentle', 'meaning': '温和'}, {'root': 'man', 'meaning': '人'}],
    'mankind': [{'root': 'man', 'meaning': '人'}, {'root': 'kind', 'meaning': '类'}],
    'humankind': [{'root': 'human', 'meaning': '人'}, {'root': 'kind', 'meaning': '类'}],
    'woman': [{'root': 'wom', 'meaning': '女(古英)'}, {'root': 'an', 'meaning': '人'}],
    'salesman': [{'root': 'sale', 'meaning': '卖'}, {'root': 's', 'meaning': '复数'}, {'root': 'man', 'meaning': '人'}],
    'weatherman': [{'root': 'weather', 'meaning': '天气'}, {'root': 'man', 'meaning': '人'}],
    'businessman': [{'root': 'business', 'meaning': '事'}, {'root': 'man', 'meaning': '人'}],
    'chairman': [{'root': 'chair', 'meaning': '椅'}, {'root': 'man', 'meaning': '人'}],
    'snowman': [{'root': 'snow', 'meaning': '雪'}, {'root': 'man', 'meaning': '人'}],
    'layman': [{'root': 'lay', 'meaning': '俗(古英)'}, {'root': 'man', 'meaning': '人'}],
    'doorman': [{'root': 'door', 'meaning': '门'}, {'root': 'man', 'meaning': '人'}],
    'postman': [{'root': 'post', 'meaning': '邮'}, {'root': 'man', 'meaning': '人'}],
    'boatman': [{'root': 'boat', 'meaning': '船'}, {'root': 'man', 'meaning': '人'}],
    'plowman': [{'root': 'plow', 'meaning': '犁'}, {'root': 'man', 'meaning': '人'}],
    'showman': [{'root': 'show', 'meaning': '示'}, {'root': 'man', 'meaning': '人'}],
    'statesman': [{'root': 'state', 'meaning': '国家'}, {'root': 's', 'meaning': '复数'}, {'root': 'man', 'meaning': '人'}],
    'spokesman': [{'root': 'speak (spoke)', 'meaning': '说话'}, {'root': 'man', 'meaning': '人'}],
    'spokeswoman': [{'root': 'speak (spoke)', 'meaning': '说话'}, {'root': 'woman', 'meaning': '女人'}],
    'stateswoman': [{'root': 'state', 'meaning': '国家'}, {'root': 'woman', 'meaning': '女人'}],
    'policewoman': [{'root': 'police', 'meaning': '警察'}, {'root': 'woman', 'meaning': '女人'}],
    'chairwoman': [{'root': 'chair', 'meaning': '椅'}, {'root': 'woman', 'meaning': '女人'}],
    'horsewoman': [{'root': 'horse', 'meaning': '马'}, {'root': 'woman', 'meaning': '女人'}],
    'townsman': [{'root': 'town', 'meaning': '镇'}, {'root': 's', 'meaning': '复数'}, {'root': 'man', 'meaning': '人'}],
    'craftsman': [{'root': 'craft', 'meaning': '工艺'}, {'root': 's', 'meaning': '复数'}, {'root': 'man', 'meaning': '人'}],
    'kinsman': [{'root': 'kin', 'meaning': '亲(古英)'}, {'root': 's', 'meaning': '复数'}, {'root': 'man', 'meaning': '人'}],
    'craftsmanship': [{'root': 'craftsman', 'meaning': '匠'}, {'root': '-ship', 'meaning': '技能'}],
    'workmanship': [{'root': 'workman', 'meaning': '工'}, {'root': '-ship', 'meaning': '技能'}],
    'sportsmanship': [{'root': 'sportsman', 'meaning': '运动员'}, {'root': '-ship', 'meaning': '精神'}],
    'citizenship': [{'root': 'citizen', 'meaning': '公民'}, {'root': '-ship', 'meaning': '身份'}],
    'leadership': [{'root': 'leader', 'meaning': '领'}, {'root': '-ship', 'meaning': '能力'}],
    'membership': [{'root': 'member', 'meaning': '员'}, {'root': '-ship', 'meaning': '身份'}],
    'ownership': [{'root': 'owner', 'meaning': '主'}, {'root': '-ship', 'meaning': '权'}],
    'partnership': [{'root': 'partner', 'meaning': '伙伴'}, {'root': '-ship', 'meaning': '关系'}],
    'relationship': [{'root': 'relation', 'meaning': '关系'}, {'root': '-ship', 'meaning': '状态'}],
    'fellowship': [{'root': 'fellow', 'meaning': '同伴'}, {'root': '-ship', 'meaning': '关系'}],
    'friendship': [{'root': 'friend', 'meaning': '友'}, {'root': '-ship', 'meaning': '情'}],
    'hardship': [{'root': 'hard', 'meaning': '难'}, {'root': '-ship', 'meaning': '状态'}],
    'sponsorship': [{'root': 'sponsor', 'meaning': '赞助'}, {'root': '-ship', 'meaning': '关系'}],
    'dictatorship': [{'root': 'dictator', 'meaning': '独裁'}, {'root': '-ship', 'meaning': '状态'}],
    'championship': [{'root': 'champion', 'meaning': '冠军'}, {'root': '-ship', 'meaning': '赛'}],
    'internship': [{'root': 'intern', 'meaning': '实习'}, {'root': '-ship', 'meaning': '身份'}],
    'scholarship': [{'root': 'scholar', 'meaning': '学者'}, {'root': '-ship', 'meaning': '奖'}],
    'apprenticeship': [{'root': 'apprentice', 'meaning': '学徒'}, {'root': '-ship', 'meaning': '期'}],
    'kingship': [{'root': 'king', 'meaning': '王'}, {'root': '-ship', 'meaning': '位'}],
    'lordship': [{'root': 'lord', 'meaning': '主'}, {'root': '-ship', 'meaning': '身份'}],
    'stewardship': [{'root': 'steward', 'meaning': '管'}, {'root': '-ship', 'meaning': '身份'}],
    'wardenship': [{'root': 'warden', 'meaning': '守'}, {'root': '-ship', 'meaning': '身份'}],
    'craftsmanship': [{'root': 'craftsman', 'meaning': '匠'}, {'root': '-ship', 'meaning': '技能'}],
    'mannish': [{'root': 'man', 'meaning': '男'}, {'root': '-nish', 'meaning': '像'}],
    'childish': [{'root': 'child', 'meaning': '孩'}, {'root': '-ish', 'meaning': '像'}],
    'foolish': [{'root': 'fool', 'meaning': '愚'}, {'root': '-ish', 'meaning': '像'}],
    'selfish': [{'root': 'self', 'meaning': '己'}, {'root': '-ish', 'meaning': '像'}],
    'snobbish': [{'root': 'snob', 'meaning': '势利'}, {'root': '-b', 'meaning': '连接'}, {'root': '-ish', 'meaning': '像'}],
    'fiendish': [{'root': 'fiend', 'meaning': '魔'}, {'root': '-ish', 'meaning': '像'}],
    'modish': [{'root': 'mod', 'meaning': '时髦(拉丁)'}, {'root': '-ish', 'meaning': '像'}],
    'boorish': [{'root': 'boor', 'meaning': '粗人'}, {'root': '-ish', 'meaning': '像'}],
    'clownish': [{'root': 'clown', 'meaning': '丑角'}, {'root': '-ish', 'meaning': '像'}],
    'dwarfish': [{'root': 'dwarf', 'meaning': '侏儒'}, {'root': '-ish', 'meaning': '像'}],
    'babyish': [{'root': 'baby', 'meaning': '婴'}, {'root': '-ish', 'meaning': '像'}],
    'piggish': [{'root': 'pig', 'meaning': '猪'}, {'root': '-gish', 'meaning': '像'}],
    'mulish': [{'root': 'mule', 'meaning': '骡'}, {'root': '-ish', 'meaning': '像'}],
    'monkish': [{'root': 'monk', 'meaning': '修道士'}, {'root': '-ish', 'meaning': '像'}],
    'hawkish': [{'root': 'hawk', 'meaning': '鹰'}, {'root': '-ish', 'meaning': '像'}],
    'bookish': [{'root': 'book', 'meaning': '书'}, {'root': '-ish', 'meaning': '像'}],
    'puckish': [{'root': 'puck', 'meaning': '恶作剧精灵'}, {'root': '-ish', 'meaning': '像'}],
    'amateurish': [{'root': 'amateur', 'meaning': '业余'}, {'root': '-ish', 'meaning': '像'}],
    'churlish': [{'root': 'churl', 'meaning': '粗人'}, {'root': '-ish', 'meaning': '像'}],
    'wolfish': [{'root': 'wolf', 'meaning': '狼'}, {'root': '-ish', 'meaning': '像'}],
    'bitchy': [{'root': 'bitch', 'meaning': '母狗'}, {'root': '-y', 'meaning': '形容词'}],
    'itchy': [{'root': 'itch', 'meaning': '痒'}, {'root': '-y', 'meaning': '形容词'}],
    'dizzy': [{'root': 'diz', 'meaning': '晕(古英)'}, {'root': '-zy', 'meaning': '形容词'}],
    'fuzzy': [{'root': 'fuzz', 'meaning': '绒'}, {'root': '-y', 'meaning': '形容词'}],
    'muzzy': [{'root': 'muzz', 'meaning': '呆'}, {'root': '-y', 'meaning': '形容词'}],
    'buzzy': [{'root': 'buzz', 'meaning': '嗡'}, {'root': '-y', 'meaning': '形容词'}],
    'jazzy': [{'root': 'jazz', 'meaning': '爵士'}, {'root': '-y', 'meaning': '形容词'}],
    'fizzy': [{'root': 'fizz', 'meaning': '嘶'}, {'root': '-y', 'meaning': '形容词'}],
    'pizzy': [{'root': 'pizza', 'meaning': '比萨'}, {'root': '-y', 'meaning': '形容词'}],
    'snazzy': [{'root': 'snazz', 'meaning': '时髦'}, {'root': '-y', 'meaning': '形容词'}],
    'puffy': [{'root': 'puff', 'meaning': '膨'}, {'root': '-y', 'meaning': '形容词'}],
    'fluffy': [{'root': 'fluff', 'meaning': '绒'}, {'root': '-y', 'meaning': '形容词'}],
    'stuffy': [{'root': 'stuff', 'meaning': '闷'}, {'root': '-y', 'meaning': '形容词'}],
    'huffy': [{'root': 'huff', 'meaning': '怒'}, {'root': '-y', 'meaning': '形容词'}],
    'muggy': [{'root': 'mugg', 'meaning': '湿'}, {'root': '-y', 'meaning': '形容词'}],
    'buggy': [{'root': 'bugg', 'meaning': '虫'}, {'root': '-y', 'meaning': '形容词'}],
    'muddy': [{'root': 'mud', 'meaning': '泥'}, {'root': '-dy', 'meaning': '形容词'}],
    'buddy': [{'root': 'budd', 'meaning': '兄'}, {'root': '-y', 'meaning': '形容词'}],
    'caddy': [{'root': 'cadd', 'meaning': '盒'}, {'root': '-y', 'meaning': '名词'}],
    'paddy': [{'root': 'padd', 'meaning': '稻'}, {'root': '-y', 'meaning': '名词'}],
    'shoddy': [{'root': 'shodd', 'meaning': '劣'}, {'root': '-y', 'meaning': '形容词'}],
    'toddy': [{'root': 'todd', 'meaning': '热饮'}, {'root': '-y', 'meaning': '名词'}],
    'sturdy': [{'root': 'sturd', 'meaning': '倔(古法语)'}, {'root': '-y', 'meaning': '形容词'}],
    'absurd': [{'root': 'ab-', 'meaning': '不'}, {'root': 'surd', 'meaning': '聾(拉丁)'}],
    'intervene': [{'root': 'inter', 'meaning': '之间'}, {'root': 'ven', 'meaning': '来(拉丁)'}],
    'intervene': [{'root': 'inter', 'meaning': '之间'}, {'root': 'ven', 'meaning': '来(拉丁)'}],
    'intervention': [{'root': 'inter', 'meaning': '之间'}, {'root': 'vent', 'meaning': '来'}, {'root': '-ion', 'meaning': '名词'}],
    'interview': [{'root': 'inter', 'meaning': '互相'}, {'root': 'view', 'meaning': '看'}],
    'interpret': [{'root': 'inter', 'meaning': '在...中'}, {'root': 'pret', 'meaning': '价(拉丁)'}],
    'interpreter': [{'root': 'interpret', 'meaning': '解释'}, {'root': '-er', 'meaning': '人'}],
    'interrupt': [{'root': 'inter', 'meaning': '在...中'}, {'root': 'rupt', 'meaning': '断'}],
    'interfere': [{'root': 'inter', 'meaning': '在...中'}, {'root': 'fer', 'meaning': '打(拉丁)'}],
    'interim': [{'root': 'inter', 'meaning': '在...中'}, {'root': '-im', 'meaning': '名词'}],
    'interval': [{'root': 'inter', 'meaning': '在...之间'}, {'root': 'val', 'meaning': '强(拉丁)'}],
    'interior': [{'root': 'inter', 'meaning': '内'}, {'root': '-ior', 'meaning': '比较级'}],
    'internal': [{'root': 'intern', 'meaning': '内'}, {'root': '-al', 'meaning': '形容词'}],
    'international': [{'root': 'inter', 'meaning': '在...之间'}, {'root': 'nation', 'meaning': '国家'}, {'root': '-al', 'meaning': '形容词'}],
    'internet': [{'root': 'inter', 'meaning': '在...之间'}, {'root': 'net', 'meaning': '网'}],
    'interact': [{'root': 'inter', 'meaning': '互相'}, {'root': 'act', 'meaning': '行动'}],
    'submarine': [{'root': 'sub', 'meaning': '下'}, {'root': 'marine', 'meaning': '海'}],
    'submerge': [{'root': 'sub', 'meaning': '下'}, {'root': 'merge', 'meaning': '沉'}],
    'submit': [{'root': 'sub', 'meaning': '下'}, {'root': 'mit', 'meaning': '送'}],
    'subordinate': [{'root': 'sub', 'meaning': '下'}, {'root': 'ordin', 'meaning': '序'}, {'root': '-ate', 'meaning': '形容词'}],
    'subscribe': [{'root': 'sub', 'meaning': '下'}, {'root': 'scrib', 'meaning': '写'}, {'root': '-e', 'meaning': '动词'}],
    'subsequent': [{'root': 'sub', 'meaning': '下'}, {'root': 'sequ', 'meaning': '跟'}, {'root': '-ent', 'meaning': '形容词'}],
    'subsidy': [{'root': 'sub', 'meaning': '下'}, {'root': 'sid', 'meaning': '坐'}, {'root': '-y', 'meaning': '名词'}],
    'substance': [{'root': 'sub', 'meaning': '下'}, {'root': 'stanc', 'meaning': '站'}, {'root': '-e', 'meaning': '名词'}],
    'substantial': [{'root': 'substance', 'meaning': '物质'}, {'root': '-ial', 'meaning': '形容词'}],
    'substitute': [{'root': 'sub', 'meaning': '下'}, {'root': 'stitut', 'meaning': '立'}, {'root': '-e', 'meaning': '名词'}],
    'subtitle': [{'root': 'sub', 'meaning': '下'}, {'root': 'title', 'meaning': '题'}],
    'subtle': [{'root': 'subt', 'meaning': '细(拉丁)'}, {'root': '-le', 'meaning': '形容词'}],
    'subtract': [{'root': 'sub', 'meaning': '下'}, {'root': 'tract', 'meaning': '拉'}],
    'suburb': [{'root': 'sub', 'meaning': '下'}, {'root': 'urb', 'meaning': '城'}],
    'suburban': [{'root': 'suburb', 'meaning': '郊区'}, {'root': '-an', 'meaning': '形容词'}],
    'superb': [{'root': 'super', 'meaning': '上(拉丁)'}],
    'supercilious': [{'root': 'super', 'meaning': '上'}, {'root': 'cili', 'meaning': '睫'}, {'root': '-ous', 'meaning': '形容词'}],
    'superficial': [{'root': 'super', 'meaning': '上'}, {'root': 'fici', 'meaning': '面'}, {'root': '-al', 'meaning': '形容词'}],
    'superintendent': [{'root': 'super', 'meaning': '上'}, {'root': 'intend', 'meaning': '管理'}, {'root': '-ent', 'meaning': '人'}],
    'superior': [{'root': 'super', 'meaning': '上'}, {'root': '-ior', 'meaning': '比较级'}],
    'superlative': [{'root': 'super', 'meaning': '上'}, {'root': 'lative', 'meaning': '带'}, {'root': '-', 'meaning': '形容词'}],
    'superman': [{'root': 'super', 'meaning': '超'}, {'root': 'man', 'meaning': '人'}],
    'supermarket': [{'root': 'super', 'meaning': '超'}, {'root': 'market', 'meaning': '市场'}],
    'supernatural': [{'root': 'super', 'meaning': '超'}, {'root': 'natur', 'meaning': '自然'}, {'root': '-al', 'meaning': '形容词'}],
    'supersonic': [{'root': 'super', 'meaning': '超'}, {'root': 'sonic', 'meaning': '声'}],
    'superstition': [{'root': 'super', 'meaning': '过'}, {'root': 'stit', 'meaning': '立(拉丁)'}, {'root': '-ion', 'meaning': '名词'}],
    'supervise': [{'root': 'super', 'meaning': '上'}, {'root': 'vis', 'meaning': '看'}, {'root': '-e', 'meaning': '动词'}],
    'supervisor': [{'root': 'supervise', 'meaning': '监督'}, {'root': '-or', 'meaning': '人'}],
    'supper': [{'root': 'sup', 'meaning': '喝'}, {'root': '-per', 'meaning': '餐'}],
    'supple': [{'root': 'suppl', 'meaning': '柔(拉丁)'}, {'root': '-e', 'meaning': '形容词'}],
    'supplement': [{'root': 'suppl', 'meaning': '补(拉丁)'}, {'root': '-ement', 'meaning': '名词'}],
    'supply': [{'root': 'sup', 'meaning': '下'}, {'root': 'ply', 'meaning': '折'}],
    'support': [{'root': 'sup', 'meaning': '下'}, {'root': 'port', 'meaning': '带'}],
    'supporter': [{'root': 'support', 'meaning': '支持'}, {'root': '-er', 'meaning': '人'}],
    'suppose': [{'root': 'sup', 'meaning': '下'}, {'root': 'pos', 'meaning': '放'}, {'root': '-e', 'meaning': '动词'}],
    'suppress': [{'root': 'sup', 'meaning': '下'}, {'root': 'press', 'meaning': '压'}],
    'supreme': [{'root': 'supr', 'meaning': '上(拉丁)'}, {'root': '-eme', 'meaning': '最高级'}],
    'ultra': [{'root': 'ultra', 'meaning': '超(拉丁)'}],
    'ultraviolet': [{'root': 'ultra', 'meaning': '超'}, {'root': 'violet', 'meaning': '紫'}],
    'umbrella': [{'root': 'umbr', 'meaning': '阴(拉丁)'}, {'root': '-ella', 'meaning': '小'}],
    'uncle': [{'root': 'uncl', 'meaning': '叔(古法语)'}, {'root': '-e', 'meaning': '名词'}],
    'unable': [{'root': 'un', 'meaning': '不'}, {'root': 'able', 'meaning': '能'}],
    'unaware': [{'root': 'un', 'meaning': '不'}, {'root': 'aware', 'meaning': '知'}],
    'uncertain': [{'root': 'un', 'meaning': '不'}, {'root': 'certain', 'meaning': '确定'}],
    'uncomfortable': [{'root': 'un', 'meaning': '不'}, {'root': 'comfort', 'meaning': '安慰'}, {'root': '-able', 'meaning': '能'}],
    'uncommon': [{'root': 'un', 'meaning': '不'}, {'root': 'common', 'meaning': '普通'}],
    'unconscious': [{'root': 'un', 'meaning': '不'}, {'root': 'conscious', 'meaning': '知'}],
    'uncover': [{'root': 'un', 'meaning': '揭'}, {'root': 'cover', 'meaning': '盖'}],
    'undergo': [{'root': 'under', 'meaning': '下'}, {'root': 'go', 'meaning': '走'}],
    'undergraduate': [{'root': 'under', 'meaning': '未'}, {'root': 'graduate', 'meaning': '毕业'}],
    'underlying': [{'root': 'under', 'meaning': '下'}, {'root': 'lying', 'meaning': '躺'}],
    'undo': [{'root': 'un', 'meaning': '反'}, {'root': 'do', 'meaning': '做'}],
    'undress': [{'root': 'un', 'meaning': '反'}, {'root': 'dress', 'meaning': '穿衣'}],
    'uneasy': [{'root': 'un', 'meaning': '不'}, {'root': 'easy', 'meaning': '易'}],
    'unemployed': [{'root': 'un', 'meaning': '不'}, {'root': 'employed', 'meaning': '雇'}],
    'unemployment': [{'root': 'un', 'meaning': '不'}, {'root': 'employ', 'meaning': '雇'}, {'root': '-ment', 'meaning': '名词'}],
    'unequal': [{'root': 'un', 'meaning': '不'}, {'root': 'equal', 'meaning': '等'}],
    'unexpected': [{'root': 'un', 'meaning': '未'}, {'root': 'expect', 'meaning': '期望'}, {'root': '-ed', 'meaning': '形容词'}],
    'unfair': [{'root': 'un', 'meaning': '不'}, {'root': 'fair', 'meaning': '公平'}],
    'unfamiliar': [{'root': 'un', 'meaning': '不'}, {'root': 'familiar', 'meaning': '熟'}],
    'unfit': [{'root': 'un', 'meaning': '不'}, {'root': 'fit', 'meaning': '合'}],
    'unfold': [{'root': 'un', 'meaning': '展'}, {'root': 'fold', 'meaning': '折'}],
    'unfortunate': [{'root': 'un', 'meaning': '不'}, {'root': 'fortun', 'meaning': '运'}, {'root': '-ate', 'meaning': '形容词'}],
    'unfriendly': [{'root': 'un', 'meaning': '不'}, {'root': 'friend', 'meaning': '友'}, {'root': '-ly', 'meaning': '形容词'}],
    'unhappy': [{'root': 'un', 'meaning': '不'}, {'root': 'happy', 'meaning': '幸'}],
    'unhealthy': [{'root': 'un', 'meaning': '不'}, {'root': 'healthy', 'meaning': '健康'}, {'root': '-y', 'meaning': '形容词'}],
    'unhurt': [{'root': 'un', 'meaning': '不'}, {'root': 'hurt', 'meaning': '伤'}],
    'unify': [{'root': 'uni', 'meaning': '一'}, {'root': '-fy', 'meaning': '使'}],
    'union': [{'root': 'uni', 'meaning': '一'}, {'root': '-on', 'meaning': '名词'}],
    'unique': [{'root': 'uni', 'meaning': '一'}, {'root': '-que', 'meaning': '形容词'}],
    'unit': [{'root': 'uni', 'meaning': '一'}, {'root': '-t', 'meaning': '名词'}],
    'unite': [{'root': 'uni', 'meaning': '一'}, {'root': '-te', 'meaning': '动词'}],
    'unity': [{'root': 'uni', 'meaning': '一'}, {'root': '-ty', 'meaning': '名词'}],
    'universal': [{'root': 'universe', 'meaning': '宇宙'}, {'root': '-al', 'meaning': '形容词'}],
    'universe': [{'root': 'uni', 'meaning': '一'}, {'root': 'verse', 'meaning': '转'}, {'root': '-', 'meaning': '名词'}],
    'university': [{'root': 'universe', 'meaning': '宇宙'}, {'root': '-ity', 'meaning': '名词'}],
    'unknown': [{'root': 'un', 'meaning': '不'}, {'root': 'known', 'meaning': '知'}],
    'unless': [{'root': 'un', 'meaning': '不'}, {'root': 'less', 'meaning': '少'}],
    'unlike': [{'root': 'un', 'meaning': '不'}, {'root': 'like', 'meaning': '像'}],
    'unlikely': [{'root': 'un', 'meaning': '不'}, {'root': 'likely', 'meaning': '可能'}, {'root': '-y', 'meaning': '形容词'}],
    'unload': [{'root': 'un', 'meaning': '反'}, {'root': 'load', 'meaning': '装'}],
    'unlock': [{'root': 'un', 'meaning': '反'}, {'root': 'lock', 'meaning': '锁'}],
    'unlucky': [{'root': 'un', 'meaning': '不'}, {'root': 'lucky', 'meaning': '运'}, {'root': '-y', 'meaning': '形容词'}],
    'unnecessary': [{'root': 'un', 'meaning': '不'}, {'root': 'necessary', 'meaning': '必要'}, {'root': '-y', 'meaning': '形容词'}],
    'unpaid': [{'root': 'un', 'meaning': '不'}, {'root': 'paid', 'meaning': '付'}],
    'unpleasant': [{'root': 'un', 'meaning': '不'}, {'root': 'pleasant', 'meaning': '愉快'}],
    'unpopular': [{'root': 'un', 'meaning': '不'}, {'root': 'popular', 'meaning': '流行'}],
    'unpredictable': [{'root': 'un', 'meaning': '不'}, {'root': 'predict', 'meaning': '预言'}, {'root': '-able', 'meaning': '能'}],
    'unreasonable': [{'root': 'un', 'meaning': '不'}, {'root': 'reasonable', 'meaning': '合理'}],
    'unrelated': [{'root': 'un', 'meaning': '不'}, {'root': 'related', 'meaning': '相关'}],
    'unrest': [{'root': 'un', 'meaning': '不'}, {'root': 'rest', 'meaning': '安'}],
    'unsafe': [{'root': 'un', 'meaning': '不'}, {'root': 'safe', 'meaning': '安全'}],
    'unsatisfactory': [{'root': 'un', 'meaning': '不'}, {'root': 'satisfactory', 'meaning': '满足'}],
    'unstable': [{'root': 'un', 'meaning': '不'}, {'root': 'stable', 'meaning': '稳'}],
    'unsuccessful': [{'root': 'un', 'meaning': '不'}, {'root': 'successful', 'meaning': '成功'}],
    'unsuitable': [{'root': 'un', 'meaning': '不'}, {'root': 'suitable', 'meaning': '适合'}],
    'until': [{'root': 'un', 'meaning': '到'}, {'root': 'til', 'meaning': '直到'}],
    'unusual': [{'root': 'un', 'meaning': '不'}, {'root': 'usual', 'meaning': '通常'}],
    'unwanted': [{'root': 'un', 'meaning': '不'}, {'root': 'wanted', 'meaning': '要'}],
    'unwilling': [{'root': 'un', 'meaning': '不'}, {'root': 'willing', 'meaning': '愿意'}],
    'unwind': [{'root': 'un', 'meaning': '反'}, {'root': 'wind', 'meaning': '绕'}],
    'upcoming': [{'root': 'up', 'meaning': '上'}, {'root': 'coming', 'meaning': '来'}],
    'uphold': [{'root': 'up', 'meaning': '上'}, {'root': 'hold', 'meaning': '持'}],
    'upright': [{'root': 'up', 'meaning': '上'}, {'root': 'right', 'meaning': '正'}],
    'uprising': [{'root': 'up', 'meaning': '上'}, {'root': 'rising', 'meaning': '起'}],
    'upset': [{'root': 'up', 'meaning': '上'}, {'root': 'set', 'meaning': '放'}],
    'up-to-date': [{'root': 'up', 'meaning': '到'}, {'root': 'date', 'meaning': '时'}],
    'urban': [{'root': 'urb', 'meaning': '城(拉丁)'}, {'root': '-an', 'meaning': '形容词'}],
    'urge': [{'root': 'urg', 'meaning': '推(拉丁)'}, {'root': '-e', 'meaning': '动词'}],
    'urgency': [{'root': 'urg', 'meaning': '推'}, {'root': '-ency', 'meaning': '名词'}],
    'urgent': [{'root': 'urg', 'meaning': '推'}, {'root': '-ent', 'meaning': '形容词'}],
    'usage': [{'root': 'use', 'meaning': '用'}, {'root': '-age', 'meaning': '名词'}],
    'used': [{'root': 'use', 'meaning': '用'}, {'root': '-d', 'meaning': '形容词'}],
    'useful': [{'root': 'use', 'meaning': '用'}, {'root': '-ful', 'meaning': '充满'}],
    'useless': [{'root': 'use', 'meaning': '用'}, {'root': '-less', 'meaning': '无'}],
    'user': [{'root': 'use', 'meaning': '用'}, {'root': '-r', 'meaning': '人'}],
    'username': [{'root': 'user', 'meaning': '用户'}, {'root': 'name', 'meaning': '名'}],
    'usher': [{'root': 'ush', 'meaning': '门(古法语)'}, {'root': '-er', 'meaning': '人'}],
    'usual': [{'root': 'us', 'meaning': '用(拉丁)'}, {'root': '-ual', 'meaning': '形容词'}],
    'usually': [{'root': 'usual', 'meaning': '通常'}, {'root': '-ly', 'meaning': '副词'}],
    'utility': [{'root': 'util', 'meaning': '用(拉丁)'}, {'root': '-ity', 'meaning': '名词'}],
    'utilize': [{'root': 'util', 'meaning': '用'}, {'root': '-ize', 'meaning': '使'}],
    'utmost': [{'root': 'ut', 'meaning': '出(古英)'}, {'root': 'most', 'meaning': '最'}],
    'utter': [{'root': 'utt', 'meaning': '出(古英)'}, {'root': '-er', 'meaning': '形容词'}],
    'utterly': [{'root': 'utter', 'meaning': '完全'}, {'root': '-ly', 'meaning': '副词'}],
    'together': [{'root': 'to', 'meaning': '到'}, {'root': 'gather', 'meaning': '聚'}],
    'tobacco': [{'root': 'tobac', 'meaning': '烟草(加勒比语)'}, {'root': '-co', 'meaning': '名词'}],
    'today': [{'root': 'to', 'meaning': '在'}, {'root': 'day', 'meaning': '日'}],
    'toffee': [{'root': 'toff', 'meaning': '糖(方言)'}, {'root': '-ee', 'meaning': '名词'}],
    'tofu': [{'root': 'tofu', 'meaning': '豆腐(日语)'}, {'root': '-', 'meaning': '名词'}],
    'tomorrow': [{'root': 'to', 'meaning': '在'}, {'root': 'morrow', 'meaning': '晨'}],
    'tonight': [{'root': 'to', 'meaning': '在'}, {'root': 'night', 'meaning': '夜'}],
    'together': [{'root': 'to', 'meaning': '到'}, {'root': 'gather', 'meaning': '聚'}],
    'toward': [{'root': 'to', 'meaning': '到'}, {'root': 'ward', 'meaning': '方向'}],
    'towards': [{'root': 'to', 'meaning': '到'}, {'root': 'wards', 'meaning': '方向'}],
    'footwear': [{'root': 'foot', 'meaning': '脚'}, {'root': 'wear', 'meaning': '穿'}],
    'leatherware': [{'root': 'leather', 'meaning': '皮'}, {'root': 'ware', 'meaning': '器'}],
    'hardware': [{'root': 'hard', 'meaning': '硬'}, {'root': 'ware', 'meaning': '器'}],
    'software': [{'root': 'soft', 'meaning': '软'}, {'root': 'ware', 'meaning': '器'}],
    'silverware': [{'root': 'silver', 'meaning': '银'}, {'root': 'ware', 'meaning': '器'}],
    'kitchenware': [{'root': 'kitchen', 'meaning': '厨房'}, {'root': 'ware', 'meaning': '器'}],
    'tableware': [{'root': 'table', 'meaning': '桌'}, {'root': 'ware', 'meaning': '器'}],
    'cookware': [{'root': 'cook', 'meaning': '烹'}, {'root': 'ware', 'meaning': '器'}],
    'handbag': [{'root': 'hand', 'meaning': '手'}, {'root': 'bag', 'meaning': '袋'}],
    'handful': [{'root': 'hand', 'meaning': '手'}, {'root': '-ful', 'meaning': '满'}],
    'handicap': [{'root': 'hand', 'meaning': '手'}, {'root': 'icap', 'meaning': '在帽中(讨价还价)'}],
    'handmade': [{'root': 'hand', 'meaning': '手'}, {'root': 'made', 'meaning': '做'}],
    'handout': [{'root': 'hand', 'meaning': '手'}, {'root': 'out', 'meaning': '出'}],
    'handbook': [{'root': 'hand', 'meaning': '手'}, {'root': 'book', 'meaning': '书'}],
    'handwriting': [{'root': 'hand', 'meaning': '手'}, {'root': 'writing', 'meaning': '写'}],
    'handy': [{'root': 'hand', 'meaning': '手'}, {'root': '-y', 'meaning': '形容词'}],
    'handsome': [{'root': 'hand', 'meaning': '手'}, {'root': 'some', 'meaning': '像'}],
    'handshake': [{'root': 'hand', 'meaning': '手'}, {'root': 'shake', 'meaning': '摇'}],
    'headquarters': [{'root': 'head', 'meaning': '首'}, {'root': 'quarters', 'meaning': '营房'}],
    'bedroom': [{'root': 'bed', 'meaning': '床'}, {'root': 'room', 'meaning': '房'}],
    'bedtime': [{'root': 'bed', 'meaning': '床'}, {'root': 'time', 'meaning': '时'}],
    'bedside': [{'root': 'bed', 'meaning': '床'}, {'root': 'side', 'meaning': '边'}],
    'bedspread': [{'root': 'bed', 'meaning': '床'}, {'root': 'spread', 'meaning': '展'}],
    'airline': [{'root': 'air', 'meaning': '空'}, {'root': 'line', 'meaning': '线'}],
    'aircraft': [{'root': 'air', 'meaning': '空'}, {'root': 'craft', 'meaning': '工艺'}],
    'airmail': [{'root': 'air', 'meaning': '空'}, {'root': 'mail', 'meaning': '邮'}],
    'airport': [{'root': 'air', 'meaning': '空'}, {'root': 'port', 'meaning': '港'}],
    'airfield': [{'root': 'air', 'meaning': '空'}, {'root': 'field', 'meaning': '场'}],
    'seaside': [{'root': 'sea', 'meaning': '海'}, {'root': 'side', 'meaning': '边'}],
    'seashore': [{'root': 'sea', 'meaning': '海'}, {'root': 'shore', 'meaning': '岸'}],
    'seafood': [{'root': 'sea', 'meaning': '海'}, {'root': 'food', 'meaning': '食'}],
    'seagull': [{'root': 'sea', 'meaning': '海'}, {'root': 'gull', 'meaning': '鸥'}],
    'sunlight': [{'root': 'sun', 'meaning': '日'}, {'root': 'light', 'meaning': '光'}],
    'sunrise': [{'root': 'sun', 'meaning': '日'}, {'root': 'rise', 'meaning': '升'}],
    'sunset': [{'root': 'sun', 'meaning': '日'}, {'root': 'set', 'meaning': '落'}],
    'sunshine': [{'root': 'sun', 'meaning': '日'}, {'root': 'shine', 'meaning': '光'}],
    'sunflower': [{'root': 'sun', 'meaning': '日'}, {'root': 'flower', 'meaning': '花'}],
    'sunburn': [{'root': 'sun', 'meaning': '日'}, {'root': 'burn', 'meaning': '烧'}],
    'sunstroke': [{'root': 'sun', 'meaning': '日'}, {'root': 'stroke', 'meaning': '击'}],
    'sundae': [{'root': 'Sun', 'meaning': '日'}, {'root': 'day', 'meaning': '日'}],
    'sundial': [{'root': 'sun', 'meaning': '日'}, {'root': 'dial', 'meaning': '盘'}],
    'moonlight': [{'root': 'moon', 'meaning': '月'}, {'root': 'light', 'meaning': '光'}],
    'moonshine': [{'root': 'moon', 'meaning': '月'}, {'root': 'shine', 'meaning': '光'}],
    'starfish': [{'root': 'star', 'meaning': '星'}, {'root': 'fish', 'meaning': '鱼'}],
    'starlight': [{'root': 'star', 'meaning': '星'}, {'root': 'light', 'meaning': '光'}],
    'starling': [{'root': 'star', 'meaning': '星'}, {'root': 'ling', 'meaning': '小'}],
    'daybreak': [{'root': 'day', 'meaning': '日'}, {'root': 'break', 'meaning': '破'}],
    'daydream': [{'root': 'day', 'meaning': '日'}, {'root': 'dream', 'meaning': '梦'}],
    'daytime': [{'root': 'day', 'meaning': '日'}, {'root': 'time', 'meaning': '时'}],
    'daylight': [{'root': 'day', 'meaning': '日'}, {'root': 'light', 'meaning': '光'}],
    'lifetime': [{'root': 'life', 'meaning': '命'}, {'root': 'time', 'meaning': '时'}],
    'lifestyle': [{'root': 'life', 'meaning': '命'}, {'root': 'style', 'meaning': '风格'}],
    'lifelong': [{'root': 'life', 'meaning': '命'}, {'root': 'long', 'meaning': '长'}],
    'lifeboat': [{'root': 'life', 'meaning': '命'}, {'root': 'boat', 'meaning': '船'}],
    'lifespan': [{'root': 'life', 'meaning': '命'}, {'root': 'span', 'meaning': '跨'}],
    'lifeline': [{'root': 'life', 'meaning': '命'}, {'root': 'line', 'meaning': '线'}],
    'clockwise': [{'root': 'clock', 'meaning': '钟'}, {'root': 'wise', 'meaning': '方向'}],
    'likewise': [{'root': 'like', 'meaning': '像'}, {'root': 'wise', 'meaning': '方式'}],
    'otherwise': [{'root': 'other', 'meaning': '另'}, {'root': 'wise', 'meaning': '方式'}],
    'anyway': [{'root': 'any', 'meaning': '任何'}, {'root': 'way', 'meaning': '方式'}],
    'anywhere': [{'root': 'any', 'meaning': '任何'}, {'root': 'where', 'meaning': '地方'}],
    'anyhow': [{'root': 'any', 'meaning': '任何'}, {'root': 'how', 'meaning': '方式'}],
    'someone': [{'root': 'some', 'meaning': '某'}, {'root': 'one', 'meaning': '一'}],
    'somewhere': [{'root': 'some', 'meaning': '某'}, {'root': 'where', 'meaning': '地方'}],
    'sometime': [{'root': 'some', 'meaning': '某'}, {'root': 'time', 'meaning': '时'}],
    'sometimes': [{'root': 'some', 'meaning': '某'}, {'root': 'time', 'meaning': '时'}, {'root': '-s', 'meaning': '副词'}],
    'something': [{'root': 'some', 'meaning': '某'}, {'root': 'thing', 'meaning': '事'}],
    'everybody': [{'root': 'every', 'meaning': '每'}, {'root': 'body', 'meaning': '人'}],
    'everyday': [{'root': 'every', 'meaning': '每'}, {'root': 'day', 'meaning': '日'}],
    'everywhere': [{'root': 'every', 'meaning': '每'}, {'root': 'where', 'meaning': '地方'}],
    'everything': [{'root': 'every', 'meaning': '每'}, {'root': 'thing', 'meaning': '事'}],
    'nowhere': [{'root': 'no', 'meaning': '不'}, {'root': 'where', 'meaning': '地方'}],
    'nothing': [{'root': 'no', 'meaning': '不'}, {'root': 'thing', 'meaning': '事'}],
    'nobody': [{'root': 'no', 'meaning': '不'}, {'root': 'body', 'meaning': '人'}],
    'anybody': [{'root': 'any', 'meaning': '任何'}, {'root': 'body', 'meaning': '人'}],
    'anywhere': [{'root': 'any', 'meaning': '任何'}, {'root': 'where', 'meaning': '地方'}],
    'somebody': [{'root': 'some', 'meaning': '某'}, {'root': 'body', 'meaning': '人'}],
    'whatever': [{'root': 'what', 'meaning': '什么'}, {'root': 'ever', 'meaning': '曾'}],
    'whichever': [{'root': 'which', 'meaning': '哪个'}, {'root': 'ever', 'meaning': '曾'}],
    'whoever': [{'root': 'who', 'meaning': '谁'}, {'root': 'ever', 'meaning': '曾'}],
    'whenever': [{'root': 'when', 'meaning': '何时'}, {'root': 'ever', 'meaning': '曾'}],
    'wherever': [{'root': 'where', 'meaning': '哪里'}, {'root': 'ever', 'meaning': '曾'}],
    'forever': [{'root': 'for', 'meaning': '为了'}, {'root': 'ever', 'meaning': '曾'}],
    'however': [{'root': 'how', 'meaning': '如何'}, {'root': 'ever', 'meaning': '曾'}],
    'moreover': [{'root': 'more', 'meaning': '更多'}, {'root': 'over', 'meaning': '过'}],
    'whatsoever': [{'root': 'what', 'meaning': '什么'}, {'root': 'so', 'meaning': '如'}, {'root': 'ever', 'meaning': '曾'}],
    'wheresoever': [{'root': 'where', 'meaning': '哪里'}, {'root': 'so', 'meaning': '如'}, {'root': 'ever', 'meaning': '曾'}],
    'howsoever': [{'root': 'how', 'meaning': '如何'}, {'root': 'so', 'meaning': '如'}, {'root': 'ever', 'meaning': '曾'}],
    'whosoever': [{'root': 'who', 'meaning': '谁'}, {'root': 'so', 'meaning': '如'}, {'root': 'ever', 'meaning': '曾'}],
}

# 5. 主流程
def main():
    words_path = Path('public/data/words.json')
    data = json.loads(words_path.read_text())
    
    m1 = 0
    m2 = 0
    for w in data:
        if w.get('roots'):
            continue
        # 自动
        r = lookup_auto(w['word'])
        if r:
            w['roots'] = r
            m1 += 1
        elif w['word'] in MANUAL:
            w['roots'] = MANUAL[w['word']]
            m2 += 1
    
    words_path.write_text(json.dumps(data, ensure_ascii=False, indent=2))
    total = sum(1 for w in data if w.get('roots'))
    print(f'✓ 自动匹配 (wordroot.txt + lemma): {m1}')
    print(f'✓ 手工匹配: {m2}')
    print(f'✓ 总 roots: {total} / {len(data)}')

if __name__ == '__main__':
    main()
