"""W58 配 7+ 字符 42 词 (高质量手工表)"""
import json
from pathlib import Path

# 7+ 字符手工表
MANUAL_LONG = {
    'children': [{'root': 'child', 'meaning': '孩(古英)'}, {'root': '-ren', 'meaning': '复数(古英)'}],
    'criteria': [{'root': 'criter', 'meaning': '判断(希腊)'}, {'root': '-ia', 'meaning': '名词(希腊)'}],
    'cupboard': [{'root': 'cup', 'meaning': '杯'}, {'root': 'board', 'meaning': '板'}],
    'drought': [{'root': 'dry', 'meaning': '干(古英)'}, {'root': '-ought', 'meaning': '名词(古英)'}],
    'earthquake': [{'root': 'earth', 'meaning': '地'}, {'root': 'quake', 'meaning': '震'}],
    'eastern': [{'root': 'east', 'meaning': '东'}, {'root': '-ern', 'meaning': '方向'}],
    'farewell': [{'root': 'fare', 'meaning': '行(古英)'}, {'root': 'well', 'meaning': '好'}],
    'firewood': [{'root': 'fire', 'meaning': '火'}, {'root': 'wood', 'meaning': '木'}],
    'foothold': [{'root': 'foot', 'meaning': '脚'}, {'root': 'hold', 'meaning': '持'}],
    'footstep': [{'root': 'foot', 'meaning': '脚'}, {'root': 'step', 'meaning': '步'}],
    'footprint': [{'root': 'foot', 'meaning': '脚'}, {'root': 'print', 'meaning': '印'}],
    'footnote': [{'root': 'foot', 'meaning': '脚'}, {'root': 'note', 'meaning': '注'}],
    'footwear': [{'root': 'foot', 'meaning': '脚'}, {'root': 'wear', 'meaning': '穿'}],
    'freight': [{'root': 'freight', 'meaning': '货(中英)'}],
    'jewellery': [{'root': 'jewel', 'meaning': '宝(古法语)'}, {'root': '-lery', 'meaning': '名词'}],
    'fisherman': [{'root': 'fish', 'meaning': '鱼'}, {'root': '-er', 'meaning': '人'}, {'root': 'man', 'meaning': '人'}],
    'fisher': [{'root': 'fish', 'meaning': '鱼'}, {'root': '-er', 'meaning': '人'}],
    'goodnight': [{'root': 'good', 'meaning': '好'}, {'root': 'night', 'meaning': '夜'}],
    'handbook': [{'root': 'hand', 'meaning': '手'}, {'root': 'book', 'meaning': '书'}],
    'handful': [{'root': 'hand', 'meaning': '手'}, {'root': '-ful', 'meaning': '满'}],
    'handout': [{'root': 'hand', 'meaning': '手'}, {'root': 'out', 'meaning': '出'}],
    'handmade': [{'root': 'hand', 'meaning': '手'}, {'root': 'made', 'meaning': '做'}],
    'handsome': [{'root': 'hand', 'meaning': '手'}, {'root': 'some', 'meaning': '像'}],
    'handshake': [{'root': 'hand', 'meaning': '手'}, {'root': 'shake', 'meaning': '摇'}],
    'hardship': [{'root': 'hard', 'meaning': '难'}, {'root': '-ship', 'meaning': '状态'}],
    'headline': [{'root': 'head', 'meaning': '头'}, {'root': 'line', 'meaning': '线'}],
    'headache': [{'root': 'head', 'meaning': '头'}, {'root': 'ache', 'meaning': '痛'}],
    'headquarters': [{'root': 'head', 'meaning': '首'}, {'root': 'quarters', 'meaning': '营房'}],
    'horseback': [{'root': 'horse', 'meaning': '马'}, {'root': 'back', 'meaning': '背'}],
    'keyboard': [{'root': 'key', 'meaning': '键'}, {'root': 'board', 'meaning': '板'}],
    'knight': [{'root': 'knight', 'meaning': '骑士(古英)'}],
    'lampshade': [{'root': 'lamp', 'meaning': '灯'}, {'root': 'shade', 'meaning': '罩'}],
    'landscape': [{'root': 'land', 'meaning': '地'}, {'root': 'scape', 'meaning': '景'}],
    'landslide': [{'root': 'land', 'meaning': '地'}, {'root': 'slide', 'meaning': '滑'}],
    'lifeboat': [{'root': 'life', 'meaning': '命'}, {'root': 'boat', 'meaning': '船'}],
    'lifetime': [{'root': 'life', 'meaning': '命'}, {'root': 'time', 'meaning': '时'}],
    'lifestyle': [{'root': 'life', 'meaning': '命'}, {'root': 'style', 'meaning': '风格'}],
    'midnight': [{'root': 'mid', 'meaning': '中'}, {'root': 'night', 'meaning': '夜'}],
    'midway': [{'root': 'mid', 'meaning': '中'}, {'root': 'way', 'meaning': '路'}],
    'midsummer': [{'root': 'mid', 'meaning': '中'}, {'root': 'summer', 'meaning': '夏'}],
    'moonlight': [{'root': 'moon', 'meaning': '月'}, {'root': 'light', 'meaning': '光'}],
    'network': [{'root': 'net', 'meaning': '网'}, {'root': 'work', 'meaning': '工作'}],
    'newspaper': [{'root': 'news', 'meaning': '新闻'}, {'root': 'paper', 'meaning': '纸'}],
    'northeast': [{'root': 'north', 'meaning': '北'}, {'root': 'east', 'meaning': '东'}],
    'northwest': [{'root': 'north', 'meaning': '北'}, {'root': 'west', 'meaning': '西'}],
    'notebook': [{'root': 'note', 'meaning': '笔记'}, {'root': 'book', 'meaning': '本'}],
    'overnight': [{'root': 'over', 'meaning': '过'}, {'root': 'night', 'meaning': '夜'}],
    'passport': [{'root': 'pass', 'meaning': '过'}, {'root': 'port', 'meaning': '港'}],
    'playground': [{'root': 'play', 'meaning': '玩'}, {'root': 'ground', 'meaning': '地'}],
    'railroad': [{'root': 'rail', 'meaning': '轨'}, {'root': 'road', 'meaning': '路'}],
    'rainbow': [{'root': 'rain', 'meaning': '雨'}, {'root': 'bow', 'meaning': '弓'}],
    'raincoat': [{'root': 'rain', 'meaning': '雨'}, {'root': 'coat', 'meaning': '衣'}],
    'seashore': [{'root': 'sea', 'meaning': '海'}, {'root': 'shore', 'meaning': '岸'}],
    'seafood': [{'root': 'sea', 'meaning': '海'}, {'root': 'food', 'meaning': '食'}],
    'seaside': [{'root': 'sea', 'meaning': '海'}, {'root': 'side', 'meaning': '边'}],
    'shipwreck': [{'root': 'ship', 'meaning': '船'}, {'root': 'wreck', 'meaning': '毁'}],
    'sidewalk': [{'root': 'side', 'meaning': '边'}, {'root': 'walk', 'meaning': '走'}],
    'snowball': [{'root': 'snow', 'meaning': '雪'}, {'root': 'ball', 'meaning': '球'}],
    'snowman': [{'root': 'snow', 'meaning': '雪'}, {'root': 'man', 'meaning': '人'}],
    'southeast': [{'root': 'south', 'meaning': '南'}, {'root': 'east', 'meaning': '东'}],
    'southwest': [{'root': 'south', 'meaning': '南'}, {'root': 'west', 'meaning': '西'}],
    'spaceship': [{'root': 'space', 'meaning': '空间'}, {'root': 'ship', 'meaning': '船'}],
    'stairway': [{'root': 'stair', 'meaning': '阶'}, {'root': 'way', 'meaning': '路'}],
    'staircase': [{'root': 'stair', 'meaning': '阶'}, {'root': 'case', 'meaning': '箱'}],
    'starfish': [{'root': 'star', 'meaning': '星'}, {'root': 'fish', 'meaning': '鱼'}],
    'starlight': [{'root': 'star', 'meaning': '星'}, {'root': 'light', 'meaning': '光'}],
    'subway': [{'root': 'sub', 'meaning': '下'}, {'root': 'way', 'meaning': '道'}],
    'sunlight': [{'root': 'sun', 'meaning': '日'}, {'root': 'light', 'meaning': '光'}],
    'sunshine': [{'root': 'sun', 'meaning': '日'}, {'root': 'shine', 'meaning': '光'}],
    'sunrise': [{'root': 'sun', 'meaning': '日'}, {'root': 'rise', 'meaning': '升'}],
    'sunset': [{'root': 'sun', 'meaning': '日'}, {'root': 'set', 'meaning': '落'}],
    'sunflower': [{'root': 'sun', 'meaning': '日'}, {'root': 'flower', 'meaning': '花'}],
    'timetable': [{'root': 'time', 'meaning': '时'}, {'root': 'table', 'meaning': '表'}],
    'tonight': [{'root': 'to', 'meaning': '在'}, {'root': 'night', 'meaning': '夜'}],
    'tomorrow': [{'root': 'to', 'meaning': '在'}, {'root': 'morrow', 'meaning': '晨'}],
    'toward': [{'root': 'to', 'meaning': '到'}, {'root': 'ward', 'meaning': '方向'}],
    'towards': [{'root': 'to', 'meaning': '到'}, {'root': 'wards', 'meaning': '方向'}],
    'typewriter': [{'root': 'type', 'meaning': '打'}, {'root': 'writer', 'meaning': '写者'}],
    'underground': [{'root': 'under', 'meaning': '下'}, {'root': 'ground', 'meaning': '地'}],
    'understand': [{'root': 'under', 'meaning': '在...下'}, {'root': 'stand', 'meaning': '站'}],
    'undertake': [{'root': 'under', 'meaning': '下'}, {'root': 'take', 'meaning': '拿'}],
    'underwater': [{'root': 'under', 'meaning': '下'}, {'root': 'water', 'meaning': '水'}],
    'upstairs': [{'root': 'up', 'meaning': '上'}, {'root': 'stairs', 'meaning': '阶'}],
    'weakness': [{'root': 'weak', 'meaning': '弱'}, {'root': '-ness', 'meaning': '名词'}],
    'welfare': [{'root': 'wel', 'meaning': '好(古英)'}, {'root': 'fare', 'meaning': '行'}],
    'whatever': [{'root': 'what', 'meaning': '什么'}, {'root': 'ever', 'meaning': '曾'}],
    'whenever': [{'root': 'when', 'meaning': '何时'}, {'root': 'ever', 'meaning': '曾'}],
    'wherever': [{'root': 'where', 'meaning': '哪里'}, {'root': 'ever', 'meaning': '曾'}],
    'whoever': [{'root': 'who', 'meaning': '谁'}, {'root': 'ever', 'meaning': '曾'}],
    'whichever': [{'root': 'which', 'meaning': '哪个'}, {'root': 'ever', 'meaning': '曾'}],
    'wholesale': [{'root': 'whole', 'meaning': '整'}, {'root': 'sale', 'meaning': '卖'}],
    'withdraw': [{'root': 'with', 'meaning': '回'}, {'root': 'draw', 'meaning': '拉'}],
    'withhold': [{'root': 'with', 'meaning': '回'}, {'root': 'hold', 'meaning': '持'}],
    'within': [{'root': 'with', 'meaning': '在'}, {'root': 'in', 'meaning': '内'}],
    'without': [{'root': 'with', 'meaning': '在'}, {'root': 'out', 'meaning': '外'}],
    'withstand': [{'root': 'with', 'meaning': '对'}, {'root': 'stand', 'meaning': '站'}],
    'workforce': [{'root': 'work', 'meaning': '工作'}, {'root': 'force', 'meaning': '力'}],
    'workman': [{'root': 'work', 'meaning': '工'}, {'root': 'man', 'meaning': '人'}],
    'workplace': [{'root': 'work', 'meaning': '工作'}, {'root': 'place', 'meaning': '场所'}],
    'workshop': [{'root': 'work', 'meaning': '工作'}, {'root': 'shop', 'meaning': '店'}],
    'worldwide': [{'root': 'world', 'meaning': '世界'}, {'root': 'wide', 'meaning': '广'}],
    'yearbook': [{'root': 'year', 'meaning': '年'}, {'root': 'book', 'meaning': '书'}],
    'yesterday': [{'root': 'yes', 'meaning': '是'}, {'root': 'terday', 'meaning': '日(古英)'}],
    'Fahrenheit': [{'root': 'Fahrenheit', 'meaning': '华氏(人名)'}],
    'blanket': [{'root': 'blank', 'meaning': '白'}, {'root': '-et', 'meaning': '小'}],
    'blossom': [{'root': 'bloss', 'meaning': '花蕾(古英)'}, {'root': '-om', 'meaning': '名词'}],
    'boycott': [{'root': 'Boycott', 'meaning': '抵制(人名)'}],
    'breadth': [{'root': 'bread', 'meaning': '宽(古英)'}, {'root': '-th', 'meaning': '名词'}],
    'cigaret': [{'root': 'cigar', 'meaning': '雪茄(西班牙)'}, {'root': '-et', 'meaning': '小'}],
    'cricket': [{'root': 'cric', 'meaning': '板(古法语)'}, {'root': '-ket', 'meaning': '名词'}],
    'eastern': [{'root': 'east', 'meaning': '东'}, {'root': '-ern', 'meaning': '方向'}],
    'groundsheet': [{'root': 'ground', 'meaning': '地'}, {'root': 'sheet', 'meaning': '布'}],
    'household': [{'root': 'house', 'meaning': '家'}, {'root': 'hold', 'meaning': '持'}],
    'housewife': [{'root': 'house', 'meaning': '家'}, {'root': 'wife', 'meaning': '妻'}],
    'housework': [{'root': 'house', 'meaning': '家'}, {'root': 'work', 'meaning': '工作'}],
}

words = json.loads(Path('public/data/words.json').read_text())
m = 0
for w in words:
    if w.get('roots'):
        continue
    if w['word'] in MANUAL_LONG:
        w['roots'] = MANUAL_LONG[w['word']]
        m += 1

Path('public/data/words.json').write_text(json.dumps(words, ensure_ascii=False, indent=2))
total = sum(1 for w in words if w.get('roots'))
print(f'✓ 手工配: {m}')
print(f'总 roots: {total} / {len(words)}')
no = [w for w in words if not w.get('roots')]
print(f'剩余: {len(no)}')
