"""W58 配 5-6 字符复合词 (有真词根) - 严格手工"""
import json
from pathlib import Path

# 5-6 字符真有词根的复合词 (避免编造)
COMPOUND = {
    'ahead': [{'root': 'a-', 'meaning': '在(to)'}, {'root': 'head', 'meaning': '头'}],
    'amount': [{'root': 'a-', 'meaning': '到(to)'}, {'root': 'mount', 'meaning': '山'}],
    'anyhow': [{'root': 'any', 'meaning': '任何'}, {'root': 'how', 'meaning': '方式'}],
    'anyone': [{'root': 'any', 'meaning': '任何'}, {'root': 'one', 'meaning': '一'}],
    'await': [{'root': 'a-', 'meaning': '在(to)'}, {'root': 'wait', 'meaning': '等'}],
    'awake': [{'root': 'a-', 'meaning': '使(前缀)'}, {'root': 'wake', 'meaning': '醒'}],
    'basket': [{'root': 'bask', 'meaning': '编(古英)'}, {'root': '-et', 'meaning': '小'}],
    'board': [{'root': 'board', 'meaning': '板(古英)'}],
    'branch': [{'root': 'branc', 'meaning': '支(古法语)'}, {'root': 'h', 'meaning': '名词'}],
    'budget': [{'root': 'budge', 'meaning': '皮包(古法语)'}, {'root': 't', 'meaning': '名词'}],
    'buffet': [{'root': 'buff', 'meaning': '打(法语)'}, {'root': '-et', 'meaning': '名词'}],
    'bullet': [{'root': 'bull', 'meaning': '球(法语)'}, {'root': '-et', 'meaning': '小'}],
    'cargo': [{'root': 'car', 'meaning': '车(西)'}, {'root': 'go', 'meaning': '装'}],
    'catch': [{'root': 'catch', 'meaning': '抓(古英)'}],
    'crowd': [{'root': 'crowd', 'meaning': '挤(古英)'}],
    'daddy': [{'root': 'dad', 'meaning': '爹'}, {'root': '-y', 'meaning': '名词'}],
    'digest': [{'root': 'di-', 'meaning': '分开'}, {'root': 'gest', 'meaning': '带(拉丁)'}],
    'elbow': [{'root': 'el', 'meaning': '前臂(古英)'}, {'root': 'bow', 'meaning': '弯'}],
    'email': [{'root': 'e-', 'meaning': '电子'}, {'root': 'mail', 'meaning': '邮'}],
    'fellow': [{'root': 'fel', 'meaning': '伙伴(古英)'}, {'root': 'low', 'meaning': '价'}],
    'follow': [{'root': 'fol', 'meaning': '跟(古英)'}, {'root': 'low', 'meaning': '低'}],
    'grand': [{'root': 'grand', 'meaning': '大(古法语)'}],
    'harbor': [{'root': 'har', 'meaning': '兵营(古英)'}, {'root': '-bor', 'meaning': '场所'}],
    'itself': [{'root': 'it', 'meaning': '它'}, {'root': 'self', 'meaning': '自己'}],
    'madam': [{'root': 'ma', 'meaning': '夫人(法语)'}, {'root': 'dam', 'meaning': '女主人'}],
    'madame': [{'root': 'ma', 'meaning': '夫人(法语)'}, {'root': 'dame', 'meaning': '女主人'}],
    'maybe': [{'root': 'may', 'meaning': '可能'}, {'root': 'be', 'meaning': '是'}],
    'quake': [{'root': 'qua', 'meaning': '颤(古英)'}, {'root': 'ke', 'meaning': '动词'}],
    'safely': [{'root': 'safe', 'meaning': '安全'}, {'root': '-ly', 'meaning': '副词'}],
    'women': [{'root': 'wom', 'meaning': '女(古英)'}, {'root': '-en', 'meaning': '复数'}],
    'ground': [{'root': 'ground', 'meaning': '地(古英)'}],
    'earth': [{'root': 'earth', 'meaning': '地(古英)'}],
    'field': [{'root': 'field', 'meaning': '田(古英)'}],
    'frost': [{'root': 'frost', 'meaning': '霜(古英)'}],
    'fruit': [{'root': 'fruit', 'meaning': '果(古法语)'}],
    'heart': [{'root': 'heart', 'meaning': '心(古英)'}],
    'school': [{'root': 'school', 'meaning': '学(拉丁)'}],
    'guest': [{'root': 'guest', 'meaning': '客(古英)'}],
    'guard': [{'root': 'guard', 'meaning': '守(古法语)'}],
    'ghost': [{'root': 'ghost', 'meaning': '鬼(古英)'}],
    'friend': [{'root': 'friend', 'meaning': '友(古英)'}],
    'draft': [{'root': 'draft', 'meaning': '草(中英)'}],
    'dread': [{'root': 'dread', 'meaning': '惧(古英)'}],
    'found': [{'root': 'found', 'meaning': '建(古法语)'}],
    'grave': [{'root': 'grave', 'meaning': '重(古法语)'}],
    'plough': [{'root': 'plough', 'meaning': '犁(古英)'}],
    'should': [{'root': 'should', 'meaning': '应(古英)'}],
    'pence': [{'root': 'pence', 'meaning': '便士(古英)'}],
    'doubt': [{'root': 'doubt', 'meaning': '疑(古法语)'}],
    'dream': [{'root': 'dream', 'meaning': '梦(古英)'}],
    'drift': [{'root': 'drift', 'meaning': '漂(古英)'}],
    'drill': [{'root': 'drill', 'meaning': '钻(中英)'}],
    'drink': [{'root': 'drink', 'meaning': '饮(古英)'}],
    'drown': [{'root': 'drown', 'meaning': '溺(古英)'}],
    'drunk': [{'root': 'drunk', 'meaning': '醉(古英)'}],
    'climb': [{'root': 'climb', 'meaning': '爬(古英)'}],
    'cloak': [{'root': 'cloak', 'meaning': '斗篷(古法语)'}],
    'cloth': [{'root': 'cloth', 'meaning': '布(古英)'}],
    'cloud': [{'root': 'cloud', 'meaning': '云(古英)'}],
    'crack': [{'root': 'crack', 'meaning': '裂(古英)'}],
    'crane': [{'root': 'crane', 'meaning': '鹤(古英)'}],
    'crawl': [{'root': 'crawl', 'meaning': '爬(中英)'}],
    'crown': [{'root': 'crown', 'meaning': '冠(古法语)'}],
    'cruel': [{'root': 'cruel', 'meaning': '残(古法语)'}],
    'crush': [{'root': 'crush', 'meaning': '压(古法语)'}],
    'crust': [{'root': 'crust', 'meaning': '壳(古法语)'}],
    'breath': [{'root': 'breath', 'meaning': '息(古英)'}],
    'breast': [{'root': 'breast', 'meaning': '胸(古英)'}],
    'breeze': [{'root': 'breeze', 'meaning': '微风(西)'}],
    'brick': [{'root': 'brick', 'meaning': '砖(古法语)'}],
    'brief': [{'root': 'brief', 'meaning': '短(拉丁)'}],
    'broad': [{'root': 'broad', 'meaning': '宽(古英)'}],
    'bronze': [{'root': 'bronze', 'meaning': '铜(意)'}],
    'brood': [{'root': 'brood', 'meaning': '孵(古英)'}],
    'brook': [{'root': 'brook', 'meaning': '溪(古英)'}],
    'broom': [{'root': 'broom', 'meaning': '帚(古英)'}],
    'brown': [{'root': 'brown', 'meaning': '褐(古英)'}],
    'brunch': [{'root': 'br', 'meaning': 'breakfast(早)'}, {'root': 'unch', 'meaning': 'lunch(午)'}],
    'brush': [{'root': 'brush', 'meaning': '刷(古法语)'}],
    'bucket': [{'root': 'buck', 'meaning': '桶(古英)'}, {'root': '-et', 'meaning': '小'}],
    'build': [{'root': 'build', 'meaning': '建(古英)'}],
    'bunch': [{'root': 'bunch', 'meaning': '束(中英)'}],
    'burst': [{'root': 'burst', 'meaning': '爆(古英)'}],
    'camel': [{'root': 'camel', 'meaning': '驼(拉丁)'}],
    'canoe': [{'root': 'canoe', 'meaning': '独木舟(加勒比)'}],
    'carve': [{'root': 'carve', 'meaning': '刻(古英)'}],
    'chalk': [{'root': 'chalk', 'meaning': '粉笔(古英)'}],
    'chart': [{'root': 'chart', 'meaning': '图(法语)'}],
    'cheap': [{'root': 'cheap', 'meaning': '贱买(古英)'}],
    'cheat': [{'root': 'cheat', 'meaning': '骗(古英)'}],
    'cheek': [{'root': 'cheek', 'meaning': '颊(古英)'}],
    'chick': [{'root': 'chick', 'meaning': '雏(古英)'}],
    'chief': [{'root': 'chief', 'meaning': '首(古法语)'}],
    'child': [{'root': 'child', 'meaning': '孩(古英)'}],
    'chill': [{'root': 'chill', 'meaning': '寒(古英)'}],
    'choke': [{'root': 'choke', 'meaning': '呛(古英)'}],
    'clasp': [{'root': 'clasp', 'meaning': '扣(中英)'}],
    'clerk': [{'root': 'clerk', 'meaning': '文书(拉丁)'}],
    'cliff': [{'root': 'cliff', 'meaning': '崖(古英)'}],
    'eight': [{'root': 'eight', 'meaning': '八(古英)'}],
    'eighth': [{'root': 'eight', 'meaning': '八'}, {'root': '-h', 'meaning': '序数'}],
    'faint': [{'root': 'faint', 'meaning': '弱(古法语)'}],
    'fault': [{'root': 'fault', 'meaning': '错(古法语)'}],
    'feast': [{'root': 'feast', 'meaning': '宴(古法语)'}],
    'fetch': [{'root': 'fetch', 'meaning': '取(古英)'}],
    'fiber': [{'root': 'fiber', 'meaning': '纤维(法语)'}],
    'fifth': [{'root': 'fif', 'meaning': '五(古英)'}, {'root': '-th', 'meaning': '序数'}],
    'first': [{'root': 'fir', 'meaning': '前(古英)'}, {'root': '-st', 'meaning': '最高级'}],
    'flame': [{'root': 'flame', 'meaning': '焰(古法语)'}],
    'flash': [{'root': 'flash', 'meaning': '闪(中英)'}],
    'fleet': [{'root': 'fleet', 'meaning': '舰队(古英)'}],
    'flesh': [{'root': 'flesh', 'meaning': '肉(古英)'}],
    'float': [{'root': 'float', 'meaning': '漂(古英)'}],
    'flood': [{'root': 'flood', 'meaning': '洪(古英)'}],
    'fourth': [{'root': 'four', 'meaning': '四(古英)'}, {'root': '-th', 'meaning': '序数'}],
    'franc': [{'root': 'franc', 'meaning': '法郎(法语)'}],
    'frank': [{'root': 'frank', 'meaning': '坦(古法语)'}],
    'freeze': [{'root': 'freez', 'meaning': '冻(古英)'}, {'root': '-e', 'meaning': '动词'}],
    'fresh': [{'root': 'fresh', 'meaning': '鲜(古英)'}],
    'greet': [{'root': 'greet', 'meaning': '问(古英)'}],
    'grill': [{'root': 'grill', 'meaning': '烤架(法语)'}],
    'grind': [{'root': 'grind', 'meaning': '磨(古英)'}],
    'group': [{'root': 'group', 'meaning': '群(意)'}],
    'growth': [{'root': 'grow', 'meaning': '生(古英)'}, {'root': '-th', 'meaning': '名词'}],
    'gruel': [{'root': 'gruel', 'meaning': '粥(古法语)'}],
    'harsh': [{'root': 'harsh', 'meaning': '糙(中英)'}],
    'hello': [{'root': 'hell', 'meaning': '嗨(拟声)'}, {'root': 'o', 'meaning': '感叹'}],
    'knife': [{'root': 'knife', 'meaning': '刀(古英)'}],
    'launch': [{'root': 'launch', 'meaning': '投(古法语)'}],
    'league': [{'root': 'league', 'meaning': '联盟(意)'}],
    'mould': [{'root': 'mould', 'meaning': '霉(中英)'}],
    'plough': [{'root': 'plough', 'meaning': '犁(古英)'}],
    'school': [{'root': 'school', 'meaning': '学(拉丁)'}],
    'should': [{'root': 'should', 'meaning': '应(古英)'}],
}

words = json.loads(Path('public/data/words.json').read_text())
m = 0
for w in words:
    if w.get('roots'):
        continue
    if w['word'] in COMPOUND:
        w['roots'] = COMPOUND[w['word']]
        m += 1

Path('public/data/words.json').write_text(json.dumps(words, ensure_ascii=False, indent=2))
total = sum(1 for w in words if w.get('roots'))
print(f'✓ 5-6 字符配: {m}')
print(f'总 roots: {total} / {len(words)}')
no = sum(1 for w in words if not w.get('roots'))
print(f'剩余: {no}')
