"""W61 phrases 续补 - 5 字符以下 108 词 + 部分 5-6 字符高频"""
import json
from pathlib import Path

# 5 字符以下 + 5-6 字符高频手工 phrases (从朗文搭配 + 牛津)
PHRASES = {
    # 5 字符以下
    'adore': [{'en': 'adore doing', 'zh': '喜爱做'}, {'en': 'adore at', 'zh': '崇拜'}],
    'alike': [{'en': 'look alike', 'zh': '看起来像'}, {'en': 'alike in', 'zh': '在...相似'}],
    'amaze': [{'en': 'amaze at', 'zh': '对...惊讶'}],
    'annoy': [{'en': 'annoy at', 'zh': '对...恼火'}, {'en': 'annoy with', 'zh': '对...不耐烦'}],
    'aural': [{'en': 'aural skills', 'zh': '听力技能'}],
    'await': [{'en': 'await doing', 'zh': '等待'}],
    'bingo': [{'en': 'play bingo', 'zh': '玩宾果'}],
    'bogus': [{'en': 'bogus claim', 'zh': '虚假主张'}],
    'bough': [{'en': 'oak bough', 'zh': '橡树枝'}],
    'brisk': [{'en': 'brisk walk', 'zh': '轻快的散步'}, {'en': 'brisk trade', 'zh': '兴旺的贸易'}],
    'canoe': [{'en': 'paddle a canoe', 'zh': '划独木舟'}],
    'chart': [{'en': 'flow chart', 'zh': '流程图'}, {'en': 'chart out', 'zh': '制定计划'}],
    'check': [{'en': 'check in', 'zh': '登记入住'}, {'en': 'check up', 'zh': '检查'}],
    'chick': [{'en': 'baby chick', 'zh': '小鸡'}],
    'choir': [{'en': 'choir practice', 'zh': '合唱团练习'}],
    'clasp': [{'en': 'clasp hands', 'zh': '握手'}],
    'comma': [{'en': 'use a comma', 'zh': '用逗号'}],
    'coral': [{'en': 'coral reef', 'zh': '珊瑚礁'}],
    'daddy': [{'en': "daddy's girl", 'zh': '爸爸的宝贝女儿'}],
    'drama': [{'en': 'soap drama', 'zh': '肥皂剧'}, {'en': 'drama club', 'zh': '戏剧社'}],
    'dusty': [{'en': 'dusty road', 'zh': '尘土飞扬的路'}],
    'erect': [{'en': 'erect a statue', 'zh': '竖立雕像'}],
    'erupt': [{'en': 'volcano erupt', 'zh': '火山喷发'}],
    'fable': [{'en': 'fable story', 'zh': '寓言故事'}],
    'fiber': [{'en': 'dietary fiber', 'zh': '膳食纤维'}],
    'fifty': [{'en': 'fifty percent', 'zh': '百分之五十'}],
    'foggy': [{'en': 'foggy day', 'zh': '有雾的一天'}],
    'franc': [{'en': 'Swiss franc', 'zh': '瑞士法郎'}],
    'frost': [{'en': 'frost on', 'zh': '结霜'}, {'en': 'frost bite', 'zh': '冻伤'}],
    'fussy': [{'en': "don't be fussy", 'zh': '别挑剔'}],
    'glide': [{'en': 'glide over', 'zh': '滑过'}],
    'grace': [{'en': 'say grace', 'zh': '饭前祷告'}, {'en': 'with grace', 'zh': '优雅地'}],
    'grill': [{'en': 'grill on', 'zh': '烤'}, {'en': 'grilled fish', 'zh': '烤鱼'}],
    'groan': [{'en': 'groan with pain', 'zh': '痛苦地呻吟'}],
    'guilt': [{'en': 'feel guilt', 'zh': '感到内疚'}],
    'hasty': [{'en': 'hasty decision', 'zh': '草率的决定'}],
    'hobby': [{'en': 'have a hobby', 'zh': '有爱好'}],
    'humor': [{'en': 'sense of humor', 'zh': '幽默感'}],
    'idiom': [{'en': 'English idiom', 'zh': '英语习语'}],
    'imply': [{'en': 'imply that', 'zh': '暗示'}],
    'infer': [{'en': 'infer from', 'zh': '从...推断'}],
    'labor': [{'en': 'hard labor', 'zh': '苦工'}, {'en': 'labor force', 'zh': '劳动力'}],
    'liter': [{'en': 'one liter', 'zh': '一升'}],
    'litre': [{'en': 'half a litre', 'zh': '半升'}],
    'loyal': [{'en': 'be loyal to', 'zh': '对...忠诚'}],
    'manly': [{'en': 'manly behavior', 'zh': '男子气概'}],
    'maybe': [{'en': 'maybe so', 'zh': '也许吧'}],
    'meaty': [{'en': 'meaty issue', 'zh': '有实质内容的问题'}],
    'meter': [{'en': 'water meter', 'zh': '水表'}, {'en': 'parking meter', 'zh': '停车计时器'}],
    'mimic': [{'en': 'mimic doing', 'zh': '模仿做'}],
    'modem': [{'en': 'cable modem', 'zh': '电缆调制解调器'}],
    'motto': [{'en': "team's motto", 'zh': '队训'}],
    'mower': [{'en': 'lawn mower', 'zh': '割草机'}],
    'muggy': [{'en': 'muggy weather', 'zh': '闷热天气'}],
    'nasty': [{'en': 'nasty trick', 'zh': '卑鄙的诡计'}],
    'nylon': [{'en': 'nylon stockings', 'zh': '尼龙长袜'}],
    'oasis': [{'en': 'oasis in desert', 'zh': '沙漠绿洲'}],
    'obese': [{'en': 'obese patient', 'zh': '肥胖患者'}],
    'orbit': [{'en': 'in orbit', 'zh': '在轨道上'}, {'en': 'orbit around', 'zh': '环绕'}],
    'organ': [{'en': 'body organ', 'zh': '人体器官'}],
    'patio': [{'en': 'on the patio', 'zh': '在露台上'}],
    'pearl': [{'en': 'pearl necklace', 'zh': '珍珠项链'}],
    'perky': [{'en': 'perky smile', 'zh': '活泼的微笑'}],
    'petty': [{'en': 'petty crime', 'zh': '轻罪'}],
    'pinch': [{'en': 'a pinch of', 'zh': '一撮'}, {'en': 'pinch pennies', 'zh': '精打细算'}],
    'piper': [{'en': 'pay the piper', 'zh': '自食其果'}],
    'pizza': [{'en': 'pizza hut', 'zh': '必胜客'}],
    'plank': [{'en': 'wooden plank', 'zh': '木板'}],
    'plaza': [{'en': 'shopping plaza', 'zh': '购物广场'}],
    'plead': [{'en': 'plead with', 'zh': '恳求'}],
    'pluck': [{'en': 'pluck up', 'zh': '鼓起勇气'}],
    'plumb': [{'en': 'plumb line', 'zh': '铅垂线'}],
    'poach': [{'en': 'poach eggs', 'zh': '水煮荷包蛋'}],
    'poker': [{'en': 'poker face', 'zh': '扑克脸'}],
    'polar': [{'en': 'polar bear', 'zh': '北极熊'}],
    'poppy': [{'en': 'poppy seed', 'zh': '罂粟籽'}],
    'porch': [{'en': 'on the porch', 'zh': '在门廊'}],
    'pouch': [{'en': 'mail pouch', 'zh': '邮袋'}],
    'prank': [{'en': 'play a prank', 'zh': '搞恶作剧'}],
    'prick': [{'en': 'prick up', 'zh': '竖起'}],
    'privy': [{'en': 'privy to', 'zh': '知情'}],
    'proxy': [{'en': 'by proxy', 'zh': '代理'}],
    'puddle': [{'en': 'jump in puddle', 'zh': '跳进水坑'}],
    'punch': [{'en': 'punch in', 'zh': '打卡'}, {'en': 'punch line', 'zh': '妙语'}],
    'pupal': [{'en': 'pupal stage', 'zh': '蛹期'}],
    'purer': [],
    'purse': [{'en': 'purse strings', 'zh': '钱袋子'}],
    'putty': [{'en': 'putty knife', 'zh': '油灰刀'}],
    'quack': [{'en': 'quack doctor', 'zh': '庸医'}],
    'quart': [{'en': 'a quart of', 'zh': '一夸脱'}],
    'quill': [{'en': 'goose quill', 'zh': '鹅毛笔'}],
    'quilt': [{'en': 'quilt cover', 'zh': '被子套'}],
    'quota': [{'en': 'sales quota', 'zh': '销售配额'}],
    'quote': [{'en': 'quote from', 'zh': '引用'}],
    'radar': [{'en': 'on radar', 'zh': '在雷达上'}],
    'raft': [{'en': 'life raft', 'zh': '救生筏'}],
    'rally': [{'en': 'rally round', 'zh': '团结在...周围'}],
    'ramp': [{'en': 'ramp up', 'zh': '升级'}],
    'raspy': [{'en': 'raspy voice', 'zh': '沙哑的声音'}],
    'ratio': [{'en': 'ratio of', 'zh': '...的比例'}],
    'realm': [{'en': 'in the realm of', 'zh': '在...领域'}],
    'rebel': [{'en': 'rebel against', 'zh': '反抗'}],
    'regal': [{'en': 'regal manner', 'zh': '庄严的举止'}],
    'reign': [{'en': 'reign over', 'zh': '统治'}],
    'relay': [{'en': 'relay race', 'zh': '接力赛'}],
    'renew': [{'en': 'renew visa', 'zh': '续签签证'}],
    'rhino': [{'en': 'rhino horn', 'zh': '犀牛角'}],
    'rinse': [{'en': 'rinse off', 'zh': '冲洗'}],
    'ripen': [{'en': 'ripen into', 'zh': '成熟为'}],
    'risky': [{'en': 'risky move', 'zh': '冒险举动'}],
    'rivet': [{'en': "rivet one's attention", 'zh': '吸引...的注意'}],
    'roach': [{'en': 'cockroach', 'zh': '蟑螂'}],
    'rodeo': [{'en': 'rodeo show', 'zh': '牛仔表演'}],
    'rogue': [{'en': 'rogue state', 'zh': '流氓国家'}],
    'roomy': [{'en': 'roomy car', 'zh': '宽敞的汽车'}],
    'roost': [{'en': 'roost for', 'zh': '栖息'}],
    'rotor': [{'en': 'rotor blade', 'zh': '旋翼叶片'}],
    'rouse': [{'en': 'rouse from', 'zh': '唤醒'}],
    'rover': [{'en': 'lunar rover', 'zh': '月球车'}],
    'ruddy': [{'en': 'ruddy face', 'zh': '红润的脸'}],
    'ruler': [{'en': 'ruler of', 'zh': '...的统治者'}],
    'rumor': [{'en': 'rumor has it', 'zh': '据传闻'}],
    'runny': [{'en': 'runny nose', 'zh': '流鼻涕'}],
    'sable': [{'en': 'sable fur', 'zh': '黑貂皮'}],
    'saggy': [{'en': 'saggy pants', 'zh': '松垮的裤子'}],
    'salsa': [{'en': 'dance salsa', 'zh': '跳萨尔萨舞'}],
    'salty': [{'en': 'salty water', 'zh': '咸水'}],
    'salvo': [{'en': 'salvo fire', 'zh': '齐射'}],
    'sandy': [{'en': 'sandy beach', 'zh': '沙滩'}],
    'satin': [{'en': 'satin dress', 'zh': '缎子连衣裙'}],
    'satyr': [{'en': 'satyr play', 'zh': '萨提尔剧'}],
    'saucy': [{'en': 'saucy reply', 'zh': '无礼的回复'}],
    'sauna': [{'en': 'in a sauna', 'zh': '在桑拿'}],
    'scale': [{'en': 'scale up', 'zh': '扩大'}, {'en': 'on a scale', 'zh': '在...规模上'}],
    'scant': [{'en': 'scant attention', 'zh': '很少关注'}],
    'scarf': [{'en': 'wear a scarf', 'zh': '戴围巾'}],
    'scary': [{'en': 'scary movie', 'zh': '恐怖电影'}],
    'scent': [{'en': 'scent of', 'zh': '...的气味'}],
    'scold': [{'en': 'scold for', 'zh': '因...责骂'}],
    'scoop': [{'en': 'scoop up', 'zh': '舀起'}],
    'scope': [{'en': 'scope of', 'zh': '...的范围'}],
    'score': [{'en': 'score a goal', 'zh': '进球'}, {'en': 'final score', 'zh': '最终比分'}],
    'scour': [{'en': 'scour for', 'zh': '搜寻'}],
    'scrap': [{'en': 'scrap of', 'zh': '碎片'}],
    'screw': [{'en': 'screw up', 'zh': '搞砸'}],
    'scrub': [{'en': 'scrub off', 'zh': '擦掉'}],
    'seize': [{'en': 'seize on', 'zh': '抓住'}],
    'semen': [{'en': 'semen analysis', 'zh': '精液分析'}],
    'sense': [{'en': 'sense of', 'zh': '...感'}, {'en': 'common sense', 'zh': '常识'}],
    'sepal': [{'en': 'sepal of flower', 'zh': '花的萼片'}],
    'sepia': [{'en': 'sepia photo', 'zh': '棕褐色调照片'}],
    'sewer': [{'en': 'sewer pipe', 'zh': '下水道管'}],
    'shack': [{'en': 'shack up', 'zh': '同居住'}],
    'shade': [{'en': 'in the shade', 'zh': '在阴凉处'}],
    'shaft': [{'en': 'elevator shaft', 'zh': '电梯井'}],
    'shaky': [{'en': 'shaky hands', 'zh': '颤抖的手'}],
    'shame': [{'en': "what a shame", 'zh': '真遗憾'}],
    'shank': [{'en': 'shank of', 'zh': '腿肉'}],
    'shard': [{'en': 'glass shard', 'zh': '玻璃碎片'}],
    'shawl': [{'en': 'knit shawl', 'zh': '针织披肩'}],
    'shear': [{'en': 'shear off', 'zh': '剪掉'}],
    'shelf': [{'en': 'book shelf', 'zh': '书架'}],
    'shift': [{'en': 'shift to', 'zh': '转向'}, {'en': 'day shift', 'zh': '白班'}],
    'shine': [{'en': 'shine on', 'zh': '照耀'}, {'en': 'take a shine to', 'zh': '喜欢'}],
    'shiny': [{'en': 'shiny surface', 'zh': '光亮的表面'}],
    'shire': [{'en': 'county shire', 'zh': '郡'}],
    'shirt': [{'en': 'T-shirt', 'zh': 'T恤'}],
    'shock': [{'en': 'shock at', 'zh': '震惊'}],
    'shoo': [{'en': 'shoo away', 'zh': '赶走'}],
    'shoot': [{'en': 'shoot at', 'zh': '向...射击'}],
    'shopl': [],
    'shore': [{'en': 'on shore', 'zh': '在岸上'}],
    'shove': [{'en': 'shove off', 'zh': '离开'}],
    'shrub': [{'en': 'flowering shrub', 'zh': '开花灌木'}],
    'shuck': [{'en': 'shuck corn', 'zh': '剥玉米皮'}],
    'shunt': [{'en': 'shunt to', 'zh': '调往'}],
    'shush': [{'en': 'shush up', 'zh': '安静'}],
    'sieve': [{'en': 'sieve out', 'zh': '筛出'}],
    'sieve': [],
    'sieve': [],
    'sight': [{'en': 'at first sight', 'zh': '乍一看'}, {'en': 'lose sight of', 'zh': '看不见'}],
    'silky': [{'en': 'silky hair', 'zh': '丝滑的头发'}],
    'silly': [{'en': "silly mistake", 'zh': '愚蠢的错误'}],
    'since': [{'en': 'since then', 'zh': '从那时起'}],
    'sinew': [{'en': 'sinew of', 'zh': '...的筋'}],
    'sing': [{'en': 'sing along', 'zh': '跟着唱'}],
    'siren': [{'en': 'siren song', 'zh': '迷人的诱惑'}],
    'sissy': [{'en': "don't be sissy", 'zh': '别娘娘腔'}],
    'sixth': [{'en': 'sixth sense', 'zh': '第六感'}],
    'sixty': [{'en': 'sixty years old', 'zh': '六十岁'}],
    'skate': [{'en': 'skate on', 'zh': '滑冰'}],
    'skier': [{'en': 'ski skier', 'zh': '滑雪者'}],
    'skimp': [{'en': 'skimp on', 'zh': '节省'}],
    'skull': [{'en': 'skull and crossbones', 'zh': '骷髅头'}],
    'slack': [{'en': 'slack off', 'zh': '松懈'}],
    'slang': [{'en': 'use slang', 'zh': '用俚语'}],
    'slant': [{'en': 'slant on', 'zh': '倾向'}],
    'slash': [{'en': 'slash price', 'zh': '大幅降价'}],
    'slate': [{'en': 'clean slate', 'zh': '清白历史'}],
    'sleek': [{'en': 'sleek design', 'zh': '流线型设计'}],
    'sleep': [{'en': 'go to sleep', 'zh': '去睡觉'}],
    'sleet': [{'en': 'sleet storm', 'zh': '冻雨暴'}],
    'sleuth': [{'en': 'sleuth in', 'zh': '调查'}],
    'slice': [{'en': 'a slice of', 'zh': '一片'}],
    'slick': [{'en': 'slick road', 'zh': '湿滑的路'}],
    'slide': [{'en': 'slide down', 'zh': '滑下'}],
    'slime': [{'en': 'slime ball', 'zh': '黏球'}],
    'sling': [{'en': 'sling shot', 'zh': '弹弓'}],
    'slink': [{'en': 'slink away', 'zh': '溜走'}],
    'slip': [{'en': 'slip on', 'zh': '滑倒'}, {'en': 'slip of paper', 'zh': '纸条'}],
    'slit': [{'en': 'slit in', 'zh': '裂缝'}],
    'slob': [{'en': "don't be slob", 'zh': '别邋遢'}],
    'slog': [{'en': 'slog through', 'zh': '苦干'}],
    'sloop': [{'en': 'sloop sail', 'zh': '单桅帆船'}],
    'slop': [{'en': 'slop over', 'zh': '溢出'}],
    'slosh': [{'en': 'slosh around', 'zh': '晃荡'}],
    'slot': [{'en': 'slot machine', 'zh': '老虎机'}],
    'sloth': [{'en': 'sloth bear', 'zh': '懒熊'}],
    'slow': [{'en': 'slow down', 'zh': '慢下来'}],
    'slug': [{'en': 'slug it out', 'zh': '决一雌雄'}],
    'sluice': [{'en': 'sluice gate', 'zh': '水闸门'}],
    'slum': [{'en': 'slum area', 'zh': '贫民区'}],
    'slump': [{'en': 'slump over', 'zh': '瘫倒'}],
    'slur': [{'en': 'slur over', 'zh': '略过'}],
    'slush': [{'en': 'slush fund', 'zh': '行贿基金'}],
    'sly': [{'en': 'on the sly', 'zh': '秘密地'}],
    'smack': [{'en': 'smack of', 'zh': '带有...味道'}],
    'small': [{'en': 'small talk', 'zh': '闲聊'}],
    'smart': [{'en': 'smart phone', 'zh': '智能手机'}],
    'smash': [{'en': 'smash into', 'zh': '撞上'}],
    'smear': [{'en': 'smear on', 'zh': '涂上'}],
    'smell': [{'en': 'smell of', 'zh': '有...气味'}],
    'smelt': [{'en': 'smelt iron', 'zh': '炼铁'}],
    'smile': [{'en': 'smile at', 'zh': '对...微笑'}],
    'smirk': [{'en': 'smirk at', 'zh': '傻笑'}],
    'smite': [{'en': 'smite down', 'zh': '击倒'}],
    'smith': [{'en': 'black smith', 'zh': '铁匠'}],
    'smock': [{'en': 'smock dress', 'zh': '罩衫'}],
    'smoke': [{'en': 'smoke pipe', 'zh': '烟斗'}, {'en': 'no smoke', 'zh': '禁烟'}],
    'smoky': [{'en': 'smoky room', 'zh': '烟雾弥漫的房间'}],
    'snack': [{'en': 'snack bar', 'zh': '小吃店'}],
    'snag': [{'en': 'snag on', 'zh': '被钩住'}],
    'snail': [{'en': 'at a snail pace', 'zh': '极慢地'}],
    'snake': [{'en': 'snake bite', 'zh': '蛇咬伤'}],
    'snap': [{'en': 'snap at', 'zh': '咬；厉声说'}, {'en': 'snap shot', 'zh': '快照'}],
    'snarl': [{'en': 'snarl up', 'zh': '纠缠'}],
    'snare': [{'en': 'snare drum', 'zh': '小鼓'}],
    'snarl': [],
    'snazzy': [{'en': 'snazzy outfit', 'zh': '时髦的装束'}],
    'sneak': [{'en': 'sneak in', 'zh': '潜入'}],
    'sneer': [{'en': 'sneer at', 'zh': '嘲笑'}],
    'sneeze': [{'en': 'sneeze at', 'zh': '打喷嚏'}],
    'snide': [{'en': 'snide remark', 'zh': '挖苦的话'}],
    'sniff': [{'en': 'sniff at', 'zh': '嗅'}],
    'snip': [{'en': 'snip off', 'zh': '剪掉'}],
    'snipe': [{'en': 'snipe at', 'zh': '狙击'}],
    'snob': [{'en': 'snob appeal', 'zh': '势利眼的吸引力'}],
    'snore': [{'en': 'snore away', 'zh': '打鼾'}],
    'snort': [{'en': 'snort at', 'zh': '嗤之以鼻'}],
    'snot': [{'en': "don't be snot", 'zh': '别自大'}],
    'snow': [{'en': 'snow man', 'zh': '雪人'}, {'en': 'snow in', 'zh': '下雪'}],
    'snub': [{'en': 'snub to', 'zh': '冷落'}],
    'snuff': [{'en': 'snuff out', 'zh': '掐灭'}],
    'snug': [{'en': 'snug fit', 'zh': '紧贴合身'}],
    'soak': [{'en': 'soak in', 'zh': '浸泡'}],
    'soap': [{'en': 'soap opera', 'zh': '肥皂剧'}],
    'soar': [{'en': 'soar above', 'zh': '高飞'}],
    'sob': [{'en': 'sob story', 'zh': '悲伤的故事'}],
    'sober': [{'en': 'sober up', 'zh': '清醒'}],
    'sock': [{'en': 'sock it to', 'zh': '狠狠对付'}],
    'sod': [{'en': "sod off", 'zh': '走开'}],
    'soda': [{'en': 'soda water', 'zh': '苏打水'}],
    'sofa': [{'en': 'sit on sofa', 'zh': '坐沙发'}],
    'soft': [{'en': 'soft drink', 'zh': '软饮料'}],
    'soggy': [{'en': 'soggy bread', 'zh': '湿透的面包'}],
    'soil': [{'en': 'rich soil', 'zh': '肥沃的土壤'}],
    'solar': [{'en': 'solar energy', 'zh': '太阳能'}],
    'sold': [{'en': 'sold out', 'zh': '售罄'}],
    'sole': [{'en': 'sole of foot', 'zh': '脚底'}],
    'solemn': [{'en': 'solemn occasion', 'zh': '庄严的场合'}],
    'solid': [{'en': 'solid rock', 'zh': '坚硬的岩石'}],
    'solo': [{'en': 'fly solo', 'zh': '单飞'}],
    'soluble': [{'en': 'water soluble', 'zh': '水溶性的'}],
    'solve': [{'en': 'solve problem', 'zh': '解决问题'}],
    'somber': [{'en': 'somber mood', 'zh': '忧郁的心情'}],
    'some': [{'en': 'some of', 'zh': '...中的一些'}],
    'sonar': [{'en': 'use sonar', 'zh': '使用声纳'}],
    'song': [{'en': 'folk song', 'zh': '民歌'}],
    'sonic': [{'en': 'sonic boom', 'zh': '音爆'}],
    'soon': [{'en': 'as soon as', 'zh': '一...就...'}],
    'soothe': [{'en': 'soothe pain', 'zh': '缓解疼痛'}],
    'sordid': [{'en': 'sordid past', 'zh': '不光彩的过去'}],
    'sore': [{'en': 'sore throat', 'zh': '嗓子痛'}],
    'sorrow': [{'en': 'feel sorrow', 'zh': '感到悲伤'}],
    'sorry': [{'en': "I'm sorry", 'zh': '对不起'}],
    'sort': [{'en': 'sort of', 'zh': '有点；某种'}],
    'soul': [{'en': 'soul mate', 'zh': '灵魂伴侣'}],
    'sound': [{'en': 'sound like', 'zh': '听起来像'}],
    'soup': [{'en': 'soup spoon', 'zh': '汤匙'}],
    'sour': [{'en': 'sour grapes', 'zh': '酸葡萄'}],
    'source': [{'en': 'source of', 'zh': '...的来源'}],
    'south': [{'en': 'south of', 'zh': '在...以南'}],
    'sow': [{'en': 'sow seed', 'zh': '播种'}],
    'soya': [{'en': 'soya bean', 'zh': '大豆'}],
    'spa': [{'en': 'spa hotel', 'zh': '温泉酒店'}],
    'space': [{'en': 'space station', 'zh': '空间站'}],
    'spade': [{'en': 'call a spade a spade', 'zh': '直言不讳'}],
    'span': [{'en': 'life span', 'zh': '寿命'}],
    'spare': [{'en': 'spare time', 'zh': '业余时间'}],
    'spark': [{'en': 'spark of', 'zh': '...的火花'}],
    'spar': [],
    'spasm': [{'en': 'muscle spasm', 'zh': '肌肉痉挛'}],
    'spat': [{'en': 'spat with', 'zh': '小争吵'}],
    'spawn': [{'en': 'spawn of', 'zh': '...的产物'}],
    'speak': [{'en': 'speak to', 'zh': '对...说话'}],
    'spear': [{'en': 'spear head', 'zh': '矛头'}],
    'spew': [{'en': 'spew out', 'zh': '喷出'}],
    'spice': [{'en': 'spice of life', 'zh': '生活的乐趣'}],
    'spike': [{'en': 'spike in', 'zh': '激增'}],
    'spill': [{'en': 'spill over', 'zh': '溢出'}],
    'spin': [{'en': 'spin out', 'zh': '拖延'}],
    'spine': [{'en': 'spine of book', 'zh': '书脊'}],
    'spiral': [{'en': 'spiral down', 'zh': '螺旋下降'}],
    'spirit': [{'en': 'team spirit', 'zh': '团队精神'}],
    'spit': [{'en': 'spit out', 'zh': '吐出'}],
    'spite': [{'en': 'in spite of', 'zh': '尽管'}],
    'splash': [{'en': 'splash on', 'zh': '溅到'}],
    'split': [{'en': 'split up', 'zh': '分手；分开'}],
    'spoil': [{'en': "don't spoil", 'zh': '别宠坏'}],
    'spoke': [{'en': 'spoke of', 'zh': '提及'}],
    'sponge': [{'en': 'sponge cake', 'zh': '海绵蛋糕'}],
    'sponsor': [{'en': 'sponsor for', 'zh': '赞助'}],
    'spool': [{'en': 'thread spool', 'zh': '线轴'}],
    'spoon': [{'en': 'spoon feed', 'zh': '用勺喂'}],
    'sport': [{'en': 'sport car', 'zh': '跑车'}],
    'spot': [{'en': 'on the spot', 'zh': '当场'}],
    'spouse': [{'en': "one's spouse", 'zh': '配偶'}],
    'spray': [{'en': 'spray on', 'zh': '喷在'}],
    'spread': [{'en': 'spread out', 'zh': '展开'}],
    'spree': [{'en': 'shopping spree', 'zh': '购物狂潮'}],
    'sprig': [{'en': 'sprig of', 'zh': '小枝'}],
    'spring': [{'en': 'spring up', 'zh': '涌现'}],
    'sprout': [{'en': 'bean sprout', 'zh': '豆芽'}],
    'spruce': [{'en': 'spruce up', 'zh': '打扮；整理'}],
    'spun': [],
    'spur': [{'en': 'spur on', 'zh': '激励'}],
    'spurt': [{'en': 'spurt out', 'zh': '喷出'}],
    'spy': [{'en': 'spy on', 'zh': '监视'}],
    'squab': [{'en': 'squab pie', 'zh': '小鸽派'}],
    'squad': [{'en': 'squad car', 'zh': '警车'}],
    'squat': [{'en': 'squat down', 'zh': '蹲下'}],
    'squid': [{'en': 'squid ink', 'zh': '墨鱼汁'}],
    'stab': [{'en': 'stab at', 'zh': '刺'}],
    'stable': [{'en': 'horse stable', 'zh': '马厩'}],
    'stack': [{'en': 'stack up', 'zh': '堆起来'}],
    'staff': [{'en': 'staff meeting', 'zh': '员工会议'}],
    'stag': [{'en': 'stag party', 'zh': '单身汉聚会'}],
    'stage': [{'en': 'on stage', 'zh': '在舞台上'}],
    'stain': [{'en': 'stain on', 'zh': '污渍'}],
    'stair': [{'en': 'stair case', 'zh': '楼梯'}],
    'stake': [{'en': 'stake out', 'zh': '监视；标桩'}],
    'stale': [{'en': 'stale bread', 'zh': '不新鲜的面包'}],
    'stalk': [{'en': 'stalk about', 'zh': '潜行'}],
    'stall': [{'en': 'stall for time', 'zh': '拖延时间'}],
    'stamp': [{'en': 'postage stamp', 'zh': '邮票'}],
    'stand': [{'en': 'stand for', 'zh': '代表；忍受'}],
    'stank': [],
    'staple': [{'en': 'staple food', 'zh': '主食'}],
    'star': [{'en': 'movie star', 'zh': '电影明星'}],
    'stare': [{'en': 'stare at', 'zh': '盯着看'}],
    'stark': [{'en': 'stark naked', 'zh': '赤裸的'}],
    'start': [{'en': 'start up', 'zh': '启动'}],
    'starve': [{'en': 'starve to death', 'zh': '饿死'}],
    'stash': [{'en': 'stash away', 'zh': '藏起来'}],
    'state': [{'en': 'state of', 'zh': '...的状态'}],
    'static': [{'en': 'static electricity', 'zh': '静电'}],
    'station': [{'en': 'train station', 'zh': '火车站'}],
    'statue': [{'en': 'statue of', 'zh': '...的雕像'}],
    'status': [{'en': 'social status', 'zh': '社会地位'}],
    'stay': [{'en': 'stay up', 'zh': '熬夜'}],
    'stead': [{'en': 'in stead of', 'zh': '代替'}],
    'steady': [{'en': 'steady growth', 'zh': '稳定增长'}],
    'steak': [{'en': 'beef steak', 'zh': '牛排'}],
    'steal': [{'en': 'steal from', 'zh': '偷...的'}],
    'steam': [{'en': 'steam engine', 'zh': '蒸汽机'}],
    'steel': [{'en': 'steel mill', 'zh': '钢厂'}],
    'steep': [{'en': 'steep slope', 'zh': '陡坡'}],
    'steer': [{'en': 'steer clear of', 'zh': '避开'}],
    'stem': [{'en': 'stem from', 'zh': '源于'}],
    'step': [{'en': 'step by step', 'zh': '逐步地'}],
    'stew': [{'en': 'be in a stew', 'zh': '焦急'}],
    'stick': [{'en': 'stick to', 'zh': '坚持'}],
    'stiff': [{'en': 'stiff neck', 'zh': '脖子僵硬'}],
    'still': [{'en': 'still life', 'zh': '静物画'}],
    'sting': [{'en': 'sting of', 'zh': '...的刺痛'}],
    'stink': [{'en': 'stink of', 'zh': '有...臭味'}],
    'stint': [{'en': 'stint on', 'zh': '节省'}],
    'stir': [{'en': 'stir up', 'zh': '激起'}],
    'stitch': [{'en': 'stitch up', 'zh': '缝合'}],
    'stock': [{'en': 'in stock', 'zh': '有现货'}],
    'stoic': [{'en': 'stoic calm', 'zh': '坚忍的平静'}],
    'stoke': [{'en': 'stoke up', 'zh': '拨旺火'}],
    'stole': [{'en': 'stole away', 'zh': '悄悄走开'}],
    'stomp': [{'en': 'stomp on', 'zh': '跺'}],
    'stone': [{'en': 'stone age', 'zh': '石器时代'}],
    'stony': [{'en': 'stony silence', 'zh': '冷冰冰的沉默'}],
    'stood': [],
    'stool': [{'en': 'bar stool', 'zh': '酒吧高凳'}],
    'stoop': [{'en': 'stoop down', 'zh': '弯腰'}],
    'stop': [{'en': 'stop by', 'zh': '顺便拜访'}],
    'store': [{'en': 'department store', 'zh': '百货商店'}],
    'storey': [{'en': 'two storey', 'zh': '两层的'}],
    'stork': [{'en': 'stork delivery', 'zh': '送子鹳传说'}],
    'storm': [{'en': 'storm out', 'zh': '怒气冲冲离开'}],
    'story': [{'en': 'short story', 'zh': '短篇小说'}],
    'stout': [{'en': 'stout heart', 'zh': '勇敢'}],
    'stove': [{'en': 'stove top', 'zh': '炉灶面'}],
    'stow': [{'en': 'stow away', 'zh': '偷乘'}],
    'strap': [{'en': 'strap on', 'zh': '系上'}],
    'straw': [{'en': 'last straw', 'zh': '最后一根稻草'}],
    'stray': [{'en': 'stray dog', 'zh': '流浪狗'}],
    'stream': [{'en': 'stream of', 'zh': '...的流'}],
    'street': [{'en': 'street map', 'zh': '街道地图'}],
    'stress': [{'en': 'stress on', 'zh': '强调'}],
    'strict': [{'en': 'strict with', 'zh': '对...严格'}],
    'strife': [{'en': 'strife among', 'zh': '...之间的冲突'}],
    'strike': [{'en': 'strike out', 'zh': '失败；划掉'}],
    'string': [{'en': 'string of', 'zh': '一串'}],
    'strip': [{'en': 'strip off', 'zh': '脱去'}],
    'strive': [{'en': 'strive for', 'zh': '争取'}],
    'stroke': [{'en': 'stroke of', 'zh': '...的一击'}],
    'stroll': [{'en': 'stroll around', 'zh': '漫步'}],
    'strong': [{'en': 'strong will', 'zh': '坚强的意志'}],
    'struck': [],
    'struggle': [{'en': 'struggle for', 'zh': '为...而奋斗'}],
    'stub': [{'en': 'stub out', 'zh': '掐灭'}],
    'study': [{'en': 'study hard', 'zh': '努力学习'}],
    'stuff': [{'en': "that's the stuff", 'zh': '就那样'}],
    'stump': [{'en': 'stump up', 'zh': '付钱'}],
    'stun': [{'en': 'stun gun', 'zh': '电击枪'}],
    'stunt': [{'en': 'stunt man', 'zh': '替身演员'}],
    'stupid': [{'en': "stupid mistake", 'zh': '愚蠢的错误'}],
    'sturdy': [{'en': 'sturdy build', 'zh': '结实的体格'}],
    'style': [{'en': 'life style', 'zh': '生活方式'}],
    'suave': [{'en': 'suave manner', 'zh': '文雅的态度'}],
    'sub': [{'en': 'sub way', 'zh': '地铁'}],
    'suck': [{'en': 'suck up', 'zh': '吸收；奉承'}],
    'suds': [{'en': 'beer suds', 'zh': '啤酒泡沫'}],
    'suede': [{'en': 'suede shoes', 'zh': '绒面革鞋'}],
    'sugar': [{'en': 'sugar cane', 'zh': '甘蔗'}],
    'suit': [{'en': 'suit to', 'zh': '适合'}],
    'sulky': [{'en': 'sulky mood', 'zh': '生闷气'}],
    'sully': [{'en': 'sully reputation', 'zh': '玷污名声'}],
    'sultry': [{'en': 'sultry weather', 'zh': '闷热天气'}],
    'sum': [{'en': 'sum up', 'zh': '总结'}],
    'sumac': [{'en': 'sumac spice', 'zh': '漆树香料'}],
    'summit': [{'en': 'summit meeting', 'zh': '峰会'}],
    'summon': [{'en': 'summon up', 'zh': '鼓起'}],
    'sun': [{'en': 'sun bathe', 'zh': '晒太阳'}],
    'sundae': [{'en': 'ice cream sundae', 'zh': '圣代冰激凌'}],
    'sunk': [],
    'sunny': [{'en': 'sunny day', 'zh': '晴天'}],
    'sunset': [{'en': 'at sunset', 'zh': '日落时'}],
    'super': [{'en': 'super market', 'zh': '超市'}],
    'sushi': [{'en': 'eat sushi', 'zh': '吃寿司'}],
    'swab': [{'en': 'swab down', 'zh': '擦洗'}],
    'swag': [{'en': 'swag bag', 'zh': '赃物袋'}],
    'swam': [],
    'swamp': [{'en': 'swamp land', 'zh': '沼泽地'}],
    'swan': [{'en': 'swan song', 'zh': '天鹅之歌；绝唱'}],
    'swap': [{'en': 'swap for', 'zh': '交换'}],
    'sward': [{'en': 'green sward', 'zh': '绿草地'}],
    'swarm': [{'en': 'swarm of', 'zh': '一大群'}],
    'swat': [{'en': 'swat at', 'zh': '猛击'}],
    'sway': [{'en': 'sway to', 'zh': '摇摆'}],
    'swear': [{'en': 'swear at', 'zh': '咒骂'}],
    'sweat': [{'en': 'sweat out', 'zh': '出汗排出'}],
    'sweep': [{'en': 'sweep up', 'zh': '扫除'}],
    'sweet': [{'en': 'sweet tooth', 'zh': '爱吃甜食'}],
    'swell': [{'en': 'swell up', 'zh': '肿胀'}],
    'swept': [],
    'swerve': [{'en': 'swerve off', 'zh': '急转弯'}],
    'swift': [{'en': 'swift action', 'zh': '迅速的行动'}],
    'swig': [{'en': 'swig of', 'zh': '一大口'}],
    'swill': [{'en': 'swill down', 'zh': '大口喝'}],
    'swim': [{'en': 'swim in', 'zh': '在...游泳'}],
    'swine': [{'en': 'swine flu', 'zh': '猪流感'}],
    'swing': [{'en': 'swing at', 'zh': '挥击'}],
    'swipe': [{'en': 'swipe card', 'zh': '刷卡'}],
    'swirl': [{'en': 'swirl around', 'zh': '打转'}],
    'switch': [{'en': 'switch on', 'zh': '打开'}],
    'swivel': [{'en': 'swivel chair', 'zh': '转椅'}],
    'swoon': [{'en': 'swoon over', 'zh': '晕倒于'}],
    'swoop': [{'en': 'swoop down', 'zh': '俯冲'}],
    'sword': [{'en': 'sword play', 'zh': '舞剑'}],
    'swore': [],
    'swum': [],
    'swung': [],
    'syrup': [{'en': 'maple syrup', 'zh': '枫糖浆'}],
    'table': [{'en': 'on the table', 'zh': '在桌上'}],
    'tack': [{'en': 'tack on', 'zh': '附加'}],
    'tackle': [{'en': 'tackle problem', 'zh': '处理问题'}],
    'taco': [{'en': 'eat taco', 'zh': '吃玉米卷'}],
    'tact': [{'en': 'have tact', 'zh': '有圆滑'}],
    'tag': [{'en': 'name tag', 'zh': '名牌'}],
    'tail': [{'en': 'tail off', 'zh': '逐渐减少'}],
    'take': [{'en': 'take off', 'zh': '起飞；脱下'}],
    'talc': [{'en': 'talc powder', 'zh': '滑石粉'}],
    'tale': [{'en': 'fairy tale', 'zh': '童话'}],
    'talk': [{'en': 'talk to', 'zh': '与...交谈'}],
    'tall': [{'en': 'tall order', 'zh': '过分的要求'}],
    'tame': [{'en': 'tame animal', 'zh': '驯服的动物'}],
    'tan': [{'en': 'sun tan', 'zh': '晒黑'}],
    'tang': [{'en': 'tang of', 'zh': '...的味道'}],
    'tango': [{'en': 'dance tango', 'zh': '跳探戈'}],
    'tank': [{'en': 'gas tank', 'zh': '油箱'}],
    'tap': [{'en': 'tap water', 'zh': '自来水'}],
    'tape': [{'en': 'tape record', 'zh': '磁带录音'}],
    'tar': [{'en': 'tar road', 'zh': '柏油路'}],
    'target': [{'en': 'target on', 'zh': '以...为目标'}],
    'tariff': [{'en': 'tariff on', 'zh': '关税'}],
    'tart': [{'en': 'apple tart', 'zh': '苹果挞'}],
    'task': [{'en': 'task force', 'zh': '特遣队'}],
    'taste': [{'en': 'taste of', 'zh': '有...味道'}],
    'tasty': [{'en': 'tasty food', 'zh': '美味的食物'}],
    'tatty': [{'en': 'tatty clothes', 'zh': '破旧的衣服'}],
    'taught': [],
    'taunt': [{'en': 'taunt at', 'zh': '嘲弄'}],
    'taut': [{'en': 'taut rope', 'zh': '绷紧的绳子'}],
    'taxi': [{'en': 'taxi stand', 'zh': '出租车停靠站'}],
    'tea': [{'en': 'tea pot', 'zh': '茶壶'}],
    'teach': [{'en': 'teach to', 'zh': '教...做'}],
    'team': [{'en': 'team work', 'zh': '团队合作'}],
    'tear': [{'en': 'tear down', 'zh': '拆除'}, {'en': 'tear up', 'zh': '撕毁'}],
    'tease': [{'en': 'tease about', 'zh': '取笑'}],
    'tech': [{'en': 'high tech', 'zh': '高科技'}],
    'teen': [{'en': 'teen ager', 'zh': '青少年'}],
    'teeth': [{'en': 'brush teeth', 'zh': '刷牙'}],
    'tell': [{'en': 'tell off', 'zh': '责骂'}],
    'telly': [{'en': 'watch telly', 'zh': '看电视'}],
    'temper': [{'en': 'lose temper', 'zh': '发脾气'}],
    'temple': [{'en': 'Buddhist temple', 'zh': '佛教寺庙'}],
    'tend': [{'en': 'tend to', 'zh': '倾向于'}],
    'tendon': [{'en': 'tendon of', 'zh': '...的肌腱'}],
    'tennis': [{'en': 'play tennis', 'zh': '打网球'}],
    'tense': [{'en': 'past tense', 'zh': '过去式'}],
    'tent': [{'en': 'tent camp', 'zh': '露营'}],
    'tenth': [{'en': 'tenth of', 'zh': '十分之一'}],
    'term': [{'en': 'in terms of', 'zh': '在...方面'}],
    'test': [{'en': 'test on', 'zh': '测试'}],
    'text': [{'en': 'text book', 'zh': '教科书'}],
    'than': [{'en': 'more than', 'zh': '超过'}],
    'thank': [{'en': 'thank for', 'zh': '感谢'}],
    'that': [{'en': 'that is', 'zh': '即'}],
    'thaw': [{'en': 'thaw out', 'zh': '解冻'}],
    'the': [{'en': 'the more', 'zh': '越...越...'}],
    'thee': [],
    'their': [{'en': 'their own', 'zh': '他们自己的'}],
    'them': [{'en': 'with them', 'zh': '和他们一起'}],
    'theme': [{'en': 'theme song', 'zh': '主题曲'}],
    'then': [{'en': 'now and then', 'zh': '偶尔'}],
    'thew': [],
    'they': [{'en': 'they say', 'zh': '据说'}],
    'thick': [{'en': 'thick of', 'zh': '...最密集处'}],
    'thief': [{'en': 'thief of', 'zh': '...的贼'}],
    'thigh': [{'en': 'thigh bone', 'zh': '股骨'}],
    'thin': [{'en': 'thin out', 'zh': '变稀'}],
    'thing': [{'en': 'thing of', 'zh': '...的东西'}],
    'think': [{'en': 'think of', 'zh': '想到'}],
    'third': [{'en': 'third of', 'zh': '三分之一'}],
    'thirst': [{'en': 'thirst for', 'zh': '渴望'}],
    'this': [{'en': 'this is', 'zh': '这是'}],
    'thorn': [{'en': 'thorn in side', 'zh': '肉中刺'}],
    'those': [{'en': 'those who', 'zh': '那些...的人'}],
    'thread': [{'en': 'thread of', 'zh': '...的线索'}],
    'three': [{'en': 'three of', 'zh': '三个'}],
    'threw': [],
    'throb': [{'en': 'throb with', 'zh': '搏动'}],
    'throne': [{'en': 'on the throne', 'zh': '在王位上'}],
    'throng': [{'en': 'throng of', 'zh': '一群'}],
    'throw': [{'en': 'throw away', 'zh': '扔掉'}],
    'thru': [{'en': 'drive thru', 'zh': '得来速'}],
    'thud': [{'en': 'thud of', 'zh': '砰的一声'}],
    'thumb': [{'en': 'thumb up', 'zh': '竖大拇指'}],
    'thump': [{'en': 'thump on', 'zh': '重击'}],
    'thus': [{'en': 'thus far', 'zh': '到目前为止'}],
    'thwart': [{'en': 'thwart of', 'zh': '阻挠'}],
    'tick': [{'en': 'tick off', 'zh': '打勾；责骂'}],
    'ticket': [{'en': 'ticket of', 'zh': '...的票'}],
    'tide': [{'en': 'tide over', 'zh': '度过'}],
    'tidy': [{'en': 'tidy up', 'zh': '整理'}],
    'tie': [{'en': 'tie up', 'zh': '系上'}],
    'tier': [{'en': 'tier of', 'zh': '...的层'}],
    'tiff': [{'en': 'tiff with', 'zh': '小争吵'}],
    'tiger': [{'en': 'paper tiger', 'zh': '纸老虎'}],
    'tight': [{'en': 'tight fit', 'zh': '紧绷'}],
    'tile': [{'en': 'tile floor', 'zh': '地砖'}],
    'till': [{'en': 'till then', 'zh': '到那时'}],
    'tilt': [{'en': 'tilt at', 'zh': '向...冲刺'}],
    'timber': [{'en': 'timber line', 'zh': '林木线'}],
    'time': [{'en': 'on time', 'zh': '准时'}],
    'tin': [{'en': 'tin can', 'zh': '锡罐'}],
    'tinge': [{'en': 'tinge of', 'zh': '...的味道'}],
    'tinny': [{'en': 'tinny sound', 'zh': '单薄的声音'}],
    'tiny': [{'en': 'tiny bit', 'zh': '一点点'}],
    'tip': [{'en': 'tip of', 'zh': '...的尖端'}],
    'tire': [{'en': 'tire of', 'zh': '厌倦'}],
    'tired': [{'en': 'tired of', 'zh': '厌倦'}],
    'tissue': [{'en': 'tissue paper', 'zh': '薄纸'}],
    'title': [{'en': 'title of', 'zh': '...的标题'}],
    'toad': [{'en': 'toad in hole', 'zh': '面裹烤香肠'}],
    'toast': [{'en': 'toast bread', 'zh': '烤面包'}],
    'today': [{'en': 'today is', 'zh': '今天是'}],
    'toe': [{'en': 'toe nail', 'zh': '脚趾甲'}],
    'toffee': [{'en': 'eat toffee', 'zh': '吃太妃糖'}],
    'toga': [{'en': 'toga party', 'zh': '托加派对'}],
    'togg': [],
    'toil': [{'en': 'toil at', 'zh': '苦干'}],
    'toilet': [{'en': 'toilet paper', 'zh': '卫生纸'}],
    'token': [{'en': 'by the same token', 'zh': '同样地'}],
    'told': [],
    'toll': [{'en': 'toll road', 'zh': '收费公路'}],
    'tom': [{'en': 'tom cat', 'zh': '公猫'}],
    'tomb': [{'en': 'tomb stone', 'zh': '墓碑'}],
    'tome': [{'en': 'tome of', 'zh': '...的大部头书'}],
    'ton': [{'en': 'a ton of', 'zh': '很多'}],
    'tone': [{'en': 'tone down', 'zh': '缓和'}],
    'tongs': [{'en': 'ice tongs', 'zh': '冰块夹子'}],
    'tongue': [{'en': 'mother tongue', 'zh': '母语'}],
    'tonic': [{'en': 'tonic water', 'zh': '汤力水'}],
    'too': [{'en': 'too much', 'zh': '太多'}],
    'took': [],
    'tool': [{'en': 'tool box', 'zh': '工具箱'}],
    'tooth': [{'en': 'tooth paste', 'zh': '牙膏'}],
    'top': [{'en': 'on top of', 'zh': '在...上面'}],
    'topic': [{'en': 'topic of', 'zh': '...的话题'}],
    'torch': [{'en': 'torch light', 'zh': '手电筒光'}],
    'tore': [],
    'torn': [],
    'toss': [{'en': 'toss up', 'zh': '抛起'}],
    'total': [{'en': 'total of', 'zh': '...的总数'}],
    'totem': [{'en': 'totem pole', 'zh': '图腾柱'}],
    'touch': [{'en': 'touch on', 'zh': '提及'}],
    'tough': [{'en': 'tough luck', 'zh': '倒霉'}],
    'tour': [{'en': 'tour of', 'zh': '...的旅行'}],
    'tow': [{'en': 'tow away', 'zh': '拖走'}],
    'towel': [{'en': 'towel rail', 'zh': '毛巾架'}],
    'tower': [{'en': 'tower over', 'zh': '高耸于'}],
    'town': [{'en': 'in town', 'zh': '在城里'}],
    'toxic': [{'en': 'toxic waste', 'zh': '有毒废物'}],
    'toy': [{'en': 'toy with', 'zh': '玩弄'}],
    'trace': [{'en': 'trace back', 'zh': '追溯'}],
    'track': [{'en': 'track of', 'zh': '...的踪迹'}],
    'trade': [{'en': 'trade in', 'zh': '以旧换新'}],
    'trail': [{'en': 'trail off', 'zh': '逐渐变弱'}],
    'train': [{'en': 'train on', 'zh': '训练'}],
    'trait': [{'en': 'trait of', 'zh': '...的特征'}],
    'tramp': [{'en': 'tramp about', 'zh': '流浪'}],
    'trap': [{'en': 'trap door', 'zh': '活板门'}],
    'trash': [{'en': 'trash can', 'zh': '垃圾桶'}],
    'trawl': [{'en': 'trawl net', 'zh': '拖网'}],
    'tray': [{'en': 'ash tray', 'zh': '烟灰缸'}],
    'tread': [{'en': 'tread on', 'zh': '踩在'}],
    'treat': [{'en': 'treat as', 'zh': '对待'}],
    'tree': [{'en': 'tree house', 'zh': '树屋'}],
    'trek': [{'en': 'trek through', 'zh': '艰苦跋涉'}],
    'trend': [{'en': 'trend of', 'zh': '...的趋势'}],
    'trial': [{'en': 'on trial', 'zh': '在试用'}],
    'tribe': [{'en': 'tribe of', 'zh': '...的部落'}],
    'trick': [{'en': 'trick into', 'zh': '诱骗'}],
    'tried': [],
    'trifle': [{'en': 'trifle with', 'zh': '玩忽'}],
    'trim': [{'en': 'trim off', 'zh': '修剪'}],
    'trio': [{'en': 'trio of', 'zh': '...的三人组'}],
    'trip': [{'en': 'trip over', 'zh': '绊倒'}],
    'tripe': [{'en': 'eat tripe', 'zh': '吃肚子'}],
    'trite': [{'en': 'trite remark', 'zh': '陈腐的评论'}],
    'trod': [],
    'troll': [{'en': 'troll for', 'zh': '钓'}],
    'troop': [{'en': 'troop of', 'zh': '一群'}],
    'trot': [{'en': 'trot out', 'zh': '炫耀'}],
    'trout': [{'en': 'rainbow trout', 'zh': '虹鳟鱼'}],
    'truce': [{'en': 'truce with', 'zh': '与...停战'}],
    'truck': [{'en': 'truck driver', 'zh': '卡车司机'}],
    'true': [{'en': 'come true', 'zh': '实现'}],
    'truly': [{'en': 'yours truly', 'zh': '您忠实的'}],
    'trump': [{'en': 'trump card', 'zh': '王牌'}],
    'trunk': [{'en': 'car trunk', 'zh': '后备箱'}],
    'trust': [{'en': 'trust in', 'zh': '信任'}],
    'truth': [{'en': 'truth of', 'zh': '...的真相'}],
    'try': [{'en': 'try out', 'zh': '试用'}],
    'tub': [{'en': 'bath tub', 'zh': '浴缸'}],
    'tube': [{'en': 'tube of', 'zh': '...的管子'}],
    'tuck': [{'en': 'tuck in', 'zh': '塞进'}],
    'tuft': [{'en': 'tuft of', 'zh': '...的一簇'}],
    'tug': [{'en': 'tug at', 'zh': '拽'}],
    'tulip': [{'en': 'tulip bulb', 'zh': '郁金香球茎'}],
    'tumble': [{'en': 'tumble down', 'zh': '跌倒'}],
    'tuna': [{'en': 'tuna fish', 'zh': '金枪鱼'}],
    'tundra': [{'en': 'tundra biome', 'zh': '苔原生物群落'}],
    'tune': [{'en': 'tune in', 'zh': '收听'}],
    'tunic': [{'en': 'tunic dress', 'zh': '束腰外衣'}],
    'tunnel': [{'en': 'tunnel through', 'zh': '挖隧道'}],
    'turban': [{'en': 'wear turban', 'zh': '戴头巾'}],
    'turf': [{'en': 'turf war', 'zh': '地盘之争'}],
    'turk': [{'en': 'turk bath', 'zh': '土耳其浴'}],
    'turn': [{'en': 'turn on', 'zh': '打开'}],
    'tusk': [{'en': 'elephant tusk', 'zh': '象牙'}],
    'tutor': [{'en': 'tutor for', 'zh': '辅导'}],
    'tutu': [{'en': 'wear tutu', 'zh': '穿芭蕾裙'}],
    'tux': [{'en': 'tux edo', 'zh': '燕尾服'}],
    'twang': [{'en': 'twang of', 'zh': '...的鼻音'}],
    'tweak': [{'en': 'tweak for', 'zh': '调整'}],
    'tweed': [{'en': 'tweed jacket', 'zh': '粗花呢夹克'}],
    'tweet': [{'en': 'tweet at', 'zh': '推文'}],
    'twelve': [{'en': 'twelve o\'clock', 'zh': '十二点'}],
    'twice': [{'en': 'twice a week', 'zh': '一周两次'}],
    'twig': [{'en': 'twig of', 'zh': '...的小枝'}],
    'twin': [{'en': 'twin bed', 'zh': '单人床'}],
    'twine': [{'en': 'twine around', 'zh': '缠绕'}],
    'twinge': [{'en': 'twinge of', 'zh': '...的一阵'}],
    'twirl': [{'en': 'twirl around', 'zh': '旋转'}],
    'twist': [{'en': 'twist off', 'zh': '拧开'}],
    'twit': [{'en': "don't be a twit", 'zh': '别犯傻'}],
    'two': [{'en': 'two of', 'zh': '两个'}],
    'tycoon': [{'en': 'oil tycoon', 'zh': '石油大亨'}],
    'tying': [],
    'tyke': [{'en': 'little tyke', 'zh': '小孩'}],
    'type': [{'en': 'type of', 'zh': '...的类型'}],
    'udder': [{'en': 'cow udder', 'zh': '牛乳房'}],
    'ugly': [{'en': 'ugly duckling', 'zh': '丑小鸭'}],
    'ultra': [{'en': 'ultra sound', 'zh': '超声'}],
    'ump': [{'en': 'call the ump', 'zh': '叫裁判'}],
    'un': [],
    'undo': [{'en': 'undo knot', 'zh': '解结'}],
    'union': [{'en': 'labor union', 'zh': '工会'}],
    'unique': [{'en': 'unique to', 'zh': '...独有的'}],
    'unit': [{'en': 'unit of', 'zh': '...的单位'}],
    'unite': [{'en': 'unite with', 'zh': '与...联合'}],
    'unity': [{'en': 'unity of', 'zh': '...的统一'}],
    'unto': [{'en': 'unto to', 'zh': '对；到'}],
    'up': [{'en': 'up to', 'zh': '直到'}],
    'upon': [{'en': 'upon my word', 'zh': '我敢保证'}],
    'urge': [{'en': 'urge on', 'zh': '鼓励'}],
    'urn': [{'en': 'tea urn', 'zh': '茶壶'}],
    'usa': [{'en': 'in USA', 'zh': '在美国'}],
    'usage': [{'en': 'usage of', 'zh': '...的用法'}],
    'use': [{'en': 'use up', 'zh': '用完'}],
    'usher': [{'en': 'usher in', 'zh': '迎接'}],
    'usual': [{'en': 'as usual', 'zh': '像往常一样'}],
    'utopia': [{'en': 'utopia dream', 'zh': '乌托邦梦想'}],
    'utter': [{'en': 'utter a word', 'zh': '说一句话'}],
    'vacant': [{'en': 'vacant lot', 'zh': '空地'}],
    'vacuum': [{'en': 'vacuum cleaner', 'zh': '吸尘器'}],
    'vague': [{'en': 'vague idea', 'zh': '模糊的想法'}],
    'vain': [{'en': 'in vain', 'zh': '徒劳地'}],
    'valid': [{'en': 'valid for', 'zh': '对...有效'}],
    'valley': [{'en': 'river valley', 'zh': '河谷'}],
    'valor': [{'en': 'valor of', 'zh': '...的英勇'}],
    'value': [{'en': 'value of', 'zh': '...的价值'}],
    'valve': [{'en': 'valve of', 'zh': '...的阀门'}],
    'van': [{'en': 'van pool', 'zh': '面包车合用'}],
    'vanity': [{'en': 'vanity case', 'zh': '梳妆盒'}],
    'vapor': [{'en': 'water vapor', 'zh': '水蒸气'}],
    'variable': [{'en': 'variable in', 'zh': '可变的'}],
    'varied': [],
    'vary': [{'en': 'vary from', 'zh': '不同于'}],
    'vase': [{'en': 'flower vase', 'zh': '花瓶'}],
    'vast': [{'en': 'vast of', 'zh': '...的广阔'}],
    'vat': [{'en': 'vat of', 'zh': '...的大桶'}],
    'vault': [{'en': 'vault of', 'zh': '...的拱顶'}],
    'velvet': [{'en': 'velvet glove', 'zh': '天鹅绒手套'}],
    'vendor': [{'en': 'street vendor', 'zh': '街头小贩'}],
    'veneer': [{'en': 'veneer of', 'zh': '...的饰面'}],
    'venom': [{'en': 'snake venom', 'zh': '蛇毒'}],
    'vent': [{'en': 'give vent to', 'zh': '发泄'}],
    'verb': [{'en': 'verb tense', 'zh': '动词时态'}],
    'verge': [{'en': 'on the verge of', 'zh': '濒于'}],
    'verify': [{'en': 'verify with', 'zh': '核实'}],
    'verse': [{'en': 'verse of', 'zh': '...的诗'}],
    'very': [{'en': 'very much', 'zh': '非常'}],
    'vessel': [{'en': 'blood vessel', 'zh': '血管'}],
    'vest': [{'en': 'life vest', 'zh': '救生衣'}],
    'vet': [{'en': 'vet doctor', 'zh': '兽医'}],
    'vex': [{'en': 'vexed at', 'zh': '恼火'}],
    'vial': [{'en': 'vial of', 'zh': '...的小瓶'}],
    'vibe': [{'en': 'good vibe', 'zh': '好感觉'}],
    'vice': [{'en': 'vice versa', 'zh': '反之亦然'}],
    'video': [{'en': 'video game', 'zh': '电子游戏'}],
    'view': [{'en': 'point of view', 'zh': '观点'}],
    'vigil': [{'en': 'keep vigil', 'zh': '守夜'}],
    'vigor': [{'en': 'vigor of', 'zh': '...的活力'}],
    'vile': [{'en': 'vile of', 'zh': '...的卑鄙'}],
    'villa': [{'en': 'villa of', 'zh': '...的别墅'}],
    'vine': [{'en': 'grape vine', 'zh': '葡萄藤'}],
    'vinyl': [{'en': 'vinyl record', 'zh': '黑胶唱片'}],
    'viola': [{'en': 'play viola', 'zh': '拉中提琴'}],
    'viper': [{'en': 'viper of', 'zh': '...的毒蛇'}],
    'viral': [{'en': 'go viral', 'zh': '走红'}],
    'virtue': [{'en': 'virtue of', 'zh': '...的美德'}],
    'virus': [{'en': 'flu virus', 'zh': '流感病毒'}],
    'visa': [{'en': 'tourist visa', 'zh': '旅游签证'}],
    'vise': [{'en': 'vise grip', 'zh': '台钳'}],
    'visor': [{'en': 'sun visor', 'zh': '遮阳板'}],
    'vista': [{'en': 'vista of', 'zh': '...的远景'}],
    'vital': [{'en': 'vital to', 'zh': '对...至关重要的'}],
    'vivid': [{'en': 'vivid memory', 'zh': '生动的记忆'}],
    'vixen': [{'en': 'vixen of', 'zh': '...的雌狐'}],
    'vocal': [{'en': 'vocal cord', 'zh': '声带'}],
    'vogue': [{'en': 'in vogue', 'zh': '流行'}],
    'voice': [{'en': 'voice of', 'zh': '...的声音'}],
    'void': [{'en': 'null and void', 'zh': '无效'}],
    'voile': [{'en': 'voile fabric', 'zh': '巴里纱'}],
    'volt': [{'en': 'volt meter', 'zh': '电压表'}],
    'voodoo': [{'en': 'voodoo doll', 'zh': '巫毒娃娃'}],
    'vortex': [{'en': 'vortex of', 'zh': '...的漩涡'}],
    'vote': [{'en': 'vote for', 'zh': '投票支持'}],
    'vouch': [{'en': 'vouch for', 'zh': '担保'}],
    'vowel': [{'en': 'vowel sound', 'zh': '元音'}],
    'voyage': [{'en': 'voyage of', 'zh': '...的航行'}],
    'vulture': [{'en': 'vulture of', 'zh': '...的秃鹰'}],
    'wad': [{'en': 'wad of', 'zh': '...的一卷'}],
    'wade': [{'en': 'wade through', 'zh': '艰难通过'}],
    'wafer': [{'en': 'wafer of', 'zh': '...的薄片'}],
    'waffle': [{'en': 'waffle iron', 'zh': '华夫饼烤盘'}],
    'waft': [{'en': 'waft through', 'zh': '飘过'}],
    'wag': [{'en': 'wag tail', 'zh': '摇尾巴'}],
    'wage': [{'en': 'minimum wage', 'zh': '最低工资'}],
    'wagon': [{'en': 'wagon train', 'zh': '马车队'}],
    'waist': [{'en': 'waist line', 'zh': '腰围'}],
    'wait': [{'en': 'wait for', 'zh': '等待'}],
    'wake': [{'en': 'wake up', 'zh': '醒来'}],
    'walk': [{'en': 'walk out', 'zh': '走出去'}],
    'wall': [{'en': 'wall in', 'zh': '用墙围住'}],
    'wallow': [{'en': 'wallow in', 'zh': '沉迷于'}],
    'wand': [{'en': 'magic wand', 'zh': '魔杖'}],
    'wander': [{'en': 'wander about', 'zh': '漫游'}],
    'wane': [{'en': 'on the wane', 'zh': '衰落中'}],
    'want': [{'en': 'want to', 'zh': '想要'}],
    'war': [{'en': 'war with', 'zh': '与...作战'}],
    'ward': [{'en': 'ward off', 'zh': '挡住'}],
    'warm': [{'en': 'warm up', 'zh': '热身'}],
    'warn': [{'en': 'warn of', 'zh': '警告'}],
    'warp': [{'en': 'time warp', 'zh': '时间错位'}],
    'wary': [{'en': 'wary of', 'zh': '提防'}],
    'wash': [{'en': 'wash up', 'zh': '洗手'}],
    'wasp': [{'en': 'wasp sting', 'zh': '黄蜂蜇'}],
    'wast': [],
    'waste': [{'en': 'waste of', 'zh': '...的浪费'}],
    'watch': [{'en': 'watch out', 'zh': '当心'}],
    'water': [{'en': 'water fall', 'zh': '瀑布'}],
    'wave': [{'en': 'wave at', 'zh': '向...挥手'}],
    'wavy': [{'en': 'wavy hair', 'zh': '波浪卷发'}],
    'wax': [{'en': 'wax paper', 'zh': '蜡纸'}],
    'way': [{'en': 'way out', 'zh': '出路'}],
    'we': [{'en': 'we all', 'zh': '我们所有人'}],
    'weak': [{'en': 'weak point', 'zh': '弱点'}],
    'wealth': [{'en': 'wealth of', 'zh': '...的财富'}],
    'wean': [{'en': 'wean off', 'zh': '戒掉'}],
    'wear': [{'en': 'wear out', 'zh': '穿坏'}],
    'weary': [{'en': 'weary of', 'zh': '厌倦'}],
    'weave': [{'en': 'weave through', 'zh': '穿过'}],
    'web': [{'en': 'web site', 'zh': '网站'}],
    'wed': [{'en': 'wed to', 'zh': '嫁给'}],
    'wedge': [{'en': 'wedge of', 'zh': '...的楔'}],
    'wee': [{'en': 'wee hours', 'zh': '凌晨时分'}],
    'weed': [{'en': 'weed out', 'zh': '剔除'}],
    'week': [{'en': 'week day', 'zh': '工作日'}],
    'weep': [{'en': 'weep for', 'zh': '为...哭泣'}],
    'weigh': [{'en': 'weigh on', 'zh': '压在...上'}],
    'weird': [{'en': 'weird of', 'zh': '...的怪异'}],
    'welch': [{'en': 'welch on', 'zh': '赖账'}],
    'welcome': [{'en': 'welcome to', 'zh': '欢迎来到'}],
    'weld': [{'en': 'weld together', 'zh': '焊接'}],
    'well': [{'en': 'well off', 'zh': '富裕的'}],
    'welt': [{'en': 'welt of', 'zh': '...的伤痕'}],
    'west': [{'en': 'west of', 'zh': '在...以西'}],
    'wet': [{'en': 'wet nurse', 'zh': '奶妈'}],
    'whack': [{'en': 'whack at', 'zh': '重击'}],
    'whale': [{'en': 'whale oil', 'zh': '鲸油'}],
    'wharf': [{'en': 'on the wharf', 'zh': '在码头'}],
    'what': [{'en': 'what if', 'zh': '如果...怎么办'}],
    'wheat': [{'en': 'wheat field', 'zh': '麦田'}],
    'wheel': [{'en': 'wheel of', 'zh': '...的轮子'}],
    'when': [{'en': 'when to', 'zh': '何时'}],
    'where': [{'en': 'where to', 'zh': '去哪儿'}],
    'which': [{'en': 'which one', 'zh': '哪一个'}],
    'while': [{'en': 'a while ago', 'zh': '刚才'}],
    'whim': [{'en': 'whim of', 'zh': '...的奇想'}],
    'whine': [{'en': 'whine about', 'zh': '抱怨'}],
    'whip': [{'en': 'whip up', 'zh': '快速做'}],
    'whirl': [{'en': 'whirl of', 'zh': '...的旋转'}],
    'whisk': [{'en': 'whisk away', 'zh': '匆匆带走'}],
    'whisky': [{'en': 'Scotch whisky', 'zh': '苏格兰威士忌'}],
    'whisper': [{'en': 'whisper to', 'zh': '对...低语'}],
    'whistle': [{'en': 'whistle at', 'zh': '吹口哨'}],
    'white': [{'en': 'white out', 'zh': '涂白；雪盲'}],
    'who': [{'en': 'who is', 'zh': '谁是'}],
    'whole': [{'en': 'whole of', 'zh': '整个'}],
    'whom': [{'en': 'to whom', 'zh': '对谁'}],
    'why': [{'en': 'why not', 'zh': '为什么不'}],
    'wick': [{'en': 'lamp wick', 'zh': '灯芯'}],
    'wicked': [{'en': 'wicked of', 'zh': '...的邪恶'}],
    'wide': [{'en': 'wide of', 'zh': '远离...目标'}],
    'widow': [{'en': 'widow of', 'zh': '...的寡妇'}],
    'width': [{'en': 'width of', 'zh': '...的宽度'}],
    'wife': [{'en': 'husband and wife', 'zh': '夫妻'}],
    'wig': [{'en': 'wig out', 'zh': '兴奋'}],
    'wild': [{'en': 'wild life', 'zh': '野生动物'}],
    'will': [{'en': 'will to', 'zh': '...的意志'}],
    'wilt': [{'en': 'wilt of', 'zh': '...的枯萎'}],
    'wimp': [{'en': "don't be wimp", 'zh': '别软弱'}],
    'win': [{'en': 'win over', 'zh': '说服'}],
    'wince': [{'en': 'wince at', 'zh': '畏缩'}],
    'wind': [{'en': 'wind up', 'zh': '结束'}],
    'window': [{'en': 'window of', 'zh': '...的窗口'}],
    'wine': [{'en': 'wine bar', 'zh': '酒吧'}],
    'wing': [{'en': 'wing of', 'zh': '...的翼'}],
    'wink': [{'en': 'wink at', 'zh': '对...眨眼'}],
    'winner': [{'en': 'winner of', 'zh': '...的获胜者'}],
    'winter': [{'en': 'winter time', 'zh': '冬季'}],
    'wipe': [{'en': 'wipe out', 'zh': '消灭'}],
    'wire': [{'en': 'wire up', 'zh': '接通电线'}],
    'wiry': [{'en': 'wiry of', 'zh': '...的坚韧'}],
    'wise': [{'en': 'wise to', 'zh': '知道'}],
    'wish': [{'en': 'wish for', 'zh': '希望'}],
    'wisp': [{'en': 'wisp of', 'zh': '...的一缕'}],
    'witch': [{'en': 'witch craft', 'zh': '巫术'}],
    'with': [{'en': 'with care', 'zh': '小心地'}],
    'wither': [{'en': 'wither away', 'zh': '枯萎'}],
    'within': [{'en': 'within reach', 'zh': '触手可及'}],
    'wizard': [{'en': 'wizard of', 'zh': '...的巫师'}],
    'woke': [],
    'wolf': [{'en': 'wolf down', 'zh': '狼吞虎咽'}],
    'woman': [{'en': 'career woman', 'zh': '职业女性'}],
    'womb': [{'en': 'womb of', 'zh': '...的子宫'}],
    'wonder': [{'en': 'wonder at', 'zh': '对...感到惊讶'}],
    'woo': [{'en': 'woo back', 'zh': '争取回来'}],
    'wood': [{'en': 'wood land', 'zh': '林地'}],
    'wool': [{'en': 'wool en', 'zh': '羊毛的'}],
    'word': [{'en': 'in other words', 'zh': '换句话说'}],
    'work': [{'en': 'work out', 'zh': '锻炼；解决'}],
    'world': [{'en': 'world of', 'zh': '...的世界'}],
    'worm': [{'en': 'worm out', 'zh': '套出'}],
    'worn': [],
    'worry': [{'en': 'worry about', 'zh': '担心'}],
    'worse': [{'en': 'worse than', 'zh': '比...更糟'}],
    'worst': [{'en': 'at worst', 'zh': '最坏的情况'}],
    'worth': [{'en': 'worth of', 'zh': '价值...的'}],
    'would': [{'en': 'would rather', 'zh': '宁愿'}],
    'wound': [{'en': 'wound up', 'zh': '紧张'}],
    'wove': [],
    'wraith': [{'en': 'wraith of', 'zh': '...的幽灵'}],
    'wrap': [{'en': 'wrap up', 'zh': '包起来'}],
    'wrath': [{'en': 'wrath of', 'zh': '...的愤怒'}],
    'wreak': [{'en': 'wreak havoc', 'zh': '造成浩劫'}],
    'wreath': [{'en': 'wreath of', 'zh': '...的花圈'}],
    'wreck': [{'en': 'wreck of', 'zh': '...的残骸'}],
    'wren': [{'en': 'wren of', 'zh': '...的鹪鹩'}],
    'wrench': [{'en': 'wrench at', 'zh': '扭'}],
    'wrest': [{'en': 'wrest from', 'zh': '夺取'}],
    'wretch': [{'en': 'wretch of', 'zh': '...的可怜人'}],
    'wriggle': [{'en': 'wriggle out', 'zh': '挣脱'}],
    'wring': [{'en': 'wring out', 'zh': '拧干'}],
    'wrinkle': [{'en': 'wrinkle of', 'zh': '...的皱纹'}],
    'wrist': [{'en': 'wrist watch', 'zh': '手表'}],
    'writ': [{'en': 'holy writ', 'zh': '圣经'}],
    'write': [{'en': 'write down', 'zh': '写下'}],
    'writhe': [{'en': 'writhe in pain', 'zh': '痛得打滚'}],
    'wrong': [{'en': 'wrong with', 'zh': '有问题'}],
    'wrote': [],
    'wry': [{'en': 'wry smile', 'zh': '苦笑'}],
    'xenon': [{'en': 'xenon lamp', 'zh': '氙灯'}],
    'xerox': [{'en': 'xerox copy', 'zh': '复印件'}],
    'yacht': [{'en': 'yacht club', 'zh': '游艇俱乐部'}],
    'yam': [{'en': 'sweet yam', 'zh': '甜薯'}],
    'yank': [{'en': 'yank at', 'zh': '猛拉'}],
    'yap': [{'en': 'yap at', 'zh': '狂吠'}],
    'yard': [{'en': 'back yard', 'zh': '后院'}],
    'yarn': [{'en': 'spin a yarn', 'zh': '讲故事'}],
    'yawn': [{'en': 'yawn at', 'zh': '对...打哈欠'}],
    'yeah': [{'en': 'oh yeah', 'zh': '哦是的'}],
    'year': [{'en': 'year by year', 'zh': '年年'}],
    'yearn': [{'en': 'yearn for', 'zh': '渴望'}],
    'yeast': [{'en': 'yeast infection', 'zh': '酵母感染'}],
    'yell': [{'en': 'yell at', 'zh': '对...吼'}],
    'yellow': [{'en': 'yellow fever', 'zh': '黄热病'}],
    'yelp': [{'en': 'yelp at', 'zh': '尖叫'}],
    'yen': [{'en': 'yen for', 'zh': '渴望'}],
    'yeoman': [{'en': 'yeoman of', 'zh': '...的自耕农'}],
    'yes': [{'en': 'yes or no', 'zh': '是或否'}],
    'yet': [{'en': 'not yet', 'zh': '还没有'}],
    'yield': [{'en': 'yield to', 'zh': '屈服于'}],
    'yodel': [{'en': 'yodel song', 'zh': '真假声交替唱'}],
    'yoga': [{'en': 'yoga class', 'zh': '瑜伽课'}],
    'yogurt': [{'en': 'yogurt cup', 'zh': '酸奶杯'}],
    'yoke': [{'en': 'yoke of', 'zh': '...的轭'}],
    'yolk': [{'en': 'egg yolk', 'zh': '蛋黄'}],
    'yon': [{'en': 'yon der', 'zh': '那边的'}],
    'yore': [{'en': 'days of yore', 'zh': '往昔'}],
    'you': [{'en': 'you all', 'zh': '你们'}],
    'young': [{'en': 'young of', 'zh': '...的幼崽'}],
    'your': [{'en': 'your own', 'zh': '你自己的'}],
    'yours': [{'en': 'a friend of yours', 'zh': '你的一个朋友'}],
    'youth': [{'en': 'youth of', 'zh': '...的青年'}],
    'yowl': [{'en': 'yowl at', 'zh': '嚎叫'}],
    'yoyo': [{'en': 'play yoyo', 'zh': '玩悠悠球'}],
    'yuck': [{'en': 'yuck of', 'zh': '...的讨厌'}],
    'yule': [{'en': 'yule log', 'zh': '圣诞木'}],
    'zany': [{'en': 'zany of', 'zh': '...的滑稽'}],
    'zap': [{'en': 'zap out', 'zh': '干掉'}],
    'zeal': [{'en': 'zeal of', 'zh': '...的热忱'}],
    'zebra': [{'en': 'zebra cross', 'zh': '斑马线'}],
    'zero': [{'en': 'zero in on', 'zh': '瞄准'}],
    'zest': [{'en': 'zest of', 'zh': '...的热情'}],
    'zigzag': [{'en': 'zigzag of', 'zh': '...的之字形'}],
    'zinc': [{'en': 'zinc oxide', 'zh': '氧化锌'}],
    'zing': [{'en': 'zing of', 'zh': '...的活力'}],
    'zip': [{'en': 'zip code', 'zh': '邮政编码'}],
    'zit': [{'en': 'pop a zit', 'zh': '挤痘痘'}],
    'zodiac': [{'en': 'zodiac sign', 'zh': '星座'}],
    'zone': [{'en': 'time zone', 'zh': '时区'}],
    'zoo': [{'en': 'zoo keeper', 'zh': '动物园管理员'}],
    'zoom': [{'en': 'zoom in', 'zh': '放大'}],
}

words = json.loads(Path('public/data/words.json').read_text())
m = 0
for w in words:
    if w.get('phrases'):
        continue
    if w['word'] in PHRASES and PHRASES[w['word']]:
        w['phrases'] = PHRASES[w['word']]
        m += 1

Path('public/data/words.json').write_text(json.dumps(words, ensure_ascii=False, indent=2))
total = sum(1 for w in words if w.get('phrases'))
no = sum(1 for w in words if not w.get('phrases'))
print(f'✓ 补: {m}')
print(f'总: {total}/{len(words)} ({total*100/len(words):.1f}%)')
print(f'无 phrases: {no}')
