"""W62 phrases P3 - 6 字符 100 词"""
import json
from pathlib import Path

PHRASES = {
    'accent': [{'en': 'speak with accent', 'zh': '带口音说话'}],
    'adverb': [{'en': 'adverb of', 'zh': '...的副词'}],
    'affect': [{'en': 'affect on', 'zh': '影响'}],
    'affirm': [{'en': 'affirm that', 'zh': '断言'}],
    'ampere': [{'en': 'ampere of', 'zh': '...的安培'}],
    'anyhow': [{'en': 'anyhow so', 'zh': '不管怎样'}],
    'anyone': [{'en': 'anyone who', 'zh': '任何人'}],
    'anyway': [{'en': 'anyway so', 'zh': '不管怎样'}],
    'assess': [{'en': 'assess at', 'zh': '估价为'}],
    'attack': [{'en': 'attack on', 'zh': '攻击'}, {'en': 'heart attack', 'zh': '心脏病发作'}],
    'attain': [{'en': 'attain to', 'zh': '达到'}],
    'August': [{'en': 'in August', 'zh': '在八月'}],
    'aviate': [{'en': 'aviate over', 'zh': '飞行于'}],
    'barely': [{'en': 'barely so', 'zh': '几乎不'}],
    'beggar': [{'en': 'beggar at', 'zh': '乞丐'}],
    'bishop': [{'en': 'bishop of', 'zh': '...的主教'}],
    'blouse': [{'en': 'wear blouse', 'zh': '穿衬衫'}],
    'border': [{'en': 'on the border', 'zh': '在边界上'}],
    'brandy': [{'en': 'drink brandy', 'zh': '喝白兰地'}],
    'bruise': [{'en': 'bruise on', 'zh': '...的擦伤'}],
    'brunch': [{'en': 'eat brunch', 'zh': '吃早午餐'}],
    'bundle': [{'en': 'bundle of', 'zh': '...的一捆'}],
    'center': [{'en': 'in the center', 'zh': '在中心'}],
    'clever': [{'en': 'clever at', 'zh': '擅长'}],
    'clothe': [{'en': 'clothe in', 'zh': '给...穿衣'}],
    'clumsy': [{'en': 'clumsy at', 'zh': '笨拙于'}],
    'compel': [{'en': 'compel to', 'zh': '强迫'}],
    'convey': [{'en': 'convey to', 'zh': '传达给'}],
    'costly': [{'en': 'costly to', 'zh': '昂贵'}],
    'coward': [{'en': 'coward at', 'zh': '...的懦夫'}],
    'crisis': [{'en': 'in crisis', 'zh': '在危机中'}],
    'crimson': [{'en': 'crimson red', 'zh': '深红'}],
    'cuddle': [{'en': 'cuddle with', 'zh': '拥抱'}],
    'cunning': [{'en': 'cunning of', 'zh': '...的狡猾'}],
    'decree': [{'en': 'decree on', 'zh': '颁布'}],
    'defeat': [{'en': 'defeat at', 'zh': '击败'}],
    'defend': [{'en': 'defend from', 'zh': '保卫'}],
    'define': [{'en': 'define as', 'zh': '定义为'}],
    'degree': [{'en': 'degree of', 'zh': '...的程度'}, {'en': "master's degree", 'zh': '硕士学位'}],
    'demand': [{'en': 'demand for', 'zh': '需求'}],
    'depend': [{'en': 'depend on', 'zh': '依赖'}],
    'deport': [{'en': 'deport from', 'zh': '驱逐出'}],
    'depict': [{'en': 'depict in', 'zh': '描绘'}],
    'deputy': [{'en': 'deputy of', 'zh': '...的副手'}],
    'derive': [{'en': 'derive from', 'zh': '源自'}],
    'descend': [{'en': 'descend from', 'zh': '源于'}],
    'desire': [{'en': 'desire for', 'zh': '渴望'}],
    'despair': [{'en': 'despair at', 'zh': '绝望'}],
    'despite': [{'en': 'despite of', 'zh': '尽管'}],
    'destroy': [{'en': 'destroy in', 'zh': '摧毁'}],
    'detail': [{'en': 'in detail', 'zh': '详细地'}],
    'detect': [{'en': 'detect in', 'zh': '检测出'}],
    'develop': [{'en': 'develop in', 'zh': '在...发展'}],
    'device': [{'en': 'device of', 'zh': '...的设备'}],
    'devote': [{'en': 'devote to', 'zh': '献身于'}],
    'differ': [{'en': 'differ from', 'zh': '与...不同'}],
    'dignity': [{'en': 'dignity of', 'zh': '...的尊严'}],
    'dilute': [{'en': 'dilute with', 'zh': '稀释'}],
    'dinner': [{'en': 'dinner time', 'zh': '晚餐时间'}],
    'direct': [{'en': 'direct to', 'zh': '指向'}],
    'distant': [{'en': 'distant from', 'zh': '远离'}],
    'divide': [{'en': 'divide into', 'zh': '分成'}],
    'divine': [{'en': 'divine of', 'zh': '...的神圣'}],
    'doctor': [{'en': 'see a doctor', 'zh': '看医生'}],
    'dollar': [{'en': 'US dollar', 'zh': '美元'}],
    'domain': [{'en': 'domain of', 'zh': '...的领域'}],
    'donate': [{'en': 'donate to', 'zh': '捐赠'}],
    'double': [{'en': 'double of', 'zh': '两倍'}],
    'doubt': [{'en': 'no doubt', 'zh': '毫无疑问'}],
    'dozen': [{'en': 'dozen of', 'zh': '...的十二个'}],
    'draft': [{'en': 'draft of', 'zh': '...的草稿'}],
    'drain': [{'en': 'brain drain', 'zh': '人才外流'}],
    'drama': [{'en': 'soap drama', 'zh': '肥皂剧'}],
    'dread': [{'en': 'dread of', 'zh': '...的恐惧'}],
    'drift': [{'en': 'drift away', 'zh': '漂走'}],
    'drill': [{'en': 'fire drill', 'zh': '消防演习'}],
    'drink': [{'en': 'drink to', 'zh': '为...干杯'}],
    'drunk': [{'en': 'get drunk', 'zh': '喝醉'}],
    'dwell': [{'en': 'dwell on', 'zh': '细想'}],
    'eager': [{'en': 'eager to', 'zh': '渴望'}],
    'eagle': [{'en': 'eagle eye', 'zh': '鹰眼'}],
    'earth': [{'en': 'on earth', 'zh': '究竟'}],
    'easily': [{'en': 'easily so', 'zh': '容易地'}],
    'echo': [{'en': 'echo back', 'zh': '回声'}],
    'elbow': [{'en': 'elbow of', 'zh': '...的肘'}],
    'elder': [{'en': 'elder to', 'zh': '年长的'}],
    'elect': [{'en': 'elect to', 'zh': '选举'}],
    'email': [{'en': 'send email', 'zh': '发邮件'}],
    'empire': [{'en': 'Roman Empire', 'zh': '罗马帝国'}],
    'enable': [{'en': 'enable to', 'zh': '使能够'}],
    'endure': [{'en': 'endure to', 'zh': '忍受'}],
    'energy': [{'en': 'solar energy', 'zh': '太阳能'}],
    'engage': [{'en': 'engage in', 'zh': '从事'}],
    'engine': [{'en': 'engine of', 'zh': '...的发动机'}],
    'enough': [{'en': 'enough of', 'zh': '足够'}],
    'ensure': [{'en': 'ensure to', 'zh': '确保'}],
    'enter': [{'en': 'enter into', 'zh': '进入'}],
    'entire': [{'en': 'entire of', 'zh': '整个'}],
    'envy': [{'en': 'envy at', 'zh': '嫉妒'}],
    'equip': [{'en': 'equip with', 'zh': '装备'}],
    'escape': [{'en': 'escape from', 'zh': '逃脱'}],
    'esteem': [{'en': 'esteem for', 'zh': '尊敬'}],
    'ethics': [{'en': 'code of ethics', 'zh': '道德准则'}],
    'ethnic': [{'en': 'ethnic of', 'zh': '...的种族'}],
    'evolve': [{'en': 'evolve into', 'zh': '演变成'}],
    'exact': [{'en': 'exact of', 'zh': '精确的'}],
    'exceed': [{'en': 'exceed in', 'zh': '超过'}],
    'excel': [{'en': 'excel in', 'zh': '擅长'}],
    'expel': [{'en': 'expel from', 'zh': '驱逐'}],
    'expert': [{'en': 'expert at', 'zh': '专家'}],
    'expire': [{'en': 'expire on', 'zh': '到期'}],
    'export': [{'en': 'export to', 'zh': '出口'}],
    'extend': [{'en': 'extend to', 'zh': '延伸至'}],
    'extent': [{'en': 'extent of', 'zh': '...的程度'}],
    'fabric': [{'en': 'fabric of', 'zh': '...的织物'}],
    'factor': [{'en': 'factor in', 'zh': '因素'}],
    'faculty': [{'en': 'faculty of', 'zh': '...的 faculty'}],
    'fading': [],
    'fairly': [{'en': 'fairly so', 'zh': '公平地'}],
    'famine': [{'en': 'famine in', 'zh': '饥荒'}],
    'famous': [{'en': 'famous for', 'zh': '因...著名'}],
    'fancy': [{'en': 'fancy to', 'zh': '喜爱'}],
    'farewell': [{'en': 'say farewell', 'zh': '告别'}],
    'farmer': [{'en': 'farmer in', 'zh': '农民'}],
    'fashion': [{'en': 'fashion of', 'zh': '...的时尚'}],
    'fasten': [{'en': 'fasten to', 'zh': '系紧'}],
    'fatal': [{'en': 'fatal to', 'zh': '致命的'}],
    'fatigue': [{'en': 'fatigue from', 'zh': '疲劳'}],
    'faulty': [{'en': 'faulty in', 'zh': '有缺陷的'}],
    'favor': [{'en': 'favor of', 'zh': '...的恩惠'}],
    'feeble': [{'en': 'feeble of', 'zh': '虚弱的'}],
    'fellow': [{'en': 'fellow of', 'zh': '...的同伴'}],
    'female': [{'en': 'female of', 'zh': '...的女性'}],
    'fierce': [{'en': 'fierce in', 'zh': '凶猛的'}],
    'fifteen': [{'en': 'fifteen of', 'zh': '十五'}],
    'filter': [{'en': 'filter out', 'zh': '过滤'}],
    'finger': [{'en': 'finger of', 'zh': '手指'}],
    'firing': [],
    'flavor': [{'en': 'flavor of', 'zh': '...的味道'}],
    'flesh': [{'en': 'flesh of', 'zh': '...的肉'}],
    'flight': [{'en': 'flight to', 'zh': '飞往'}],
    'flower': [{'en': 'flower of', 'zh': '...的花'}],
    'flying': [],
    'follow': [{'en': 'follow up', 'zh': '跟进'}],
    'forbid': [{'en': 'forbid to', 'zh': '禁止'}],
    'force': [{'en': 'force of', 'zh': '...的力量'}],
    'forest': [{'en': 'forest of', 'zh': '...的森林'}],
    'forget': [{'en': 'forget to', 'zh': '忘记'}],
    'forgive': [{'en': 'forgive for', 'zh': '原谅'}],
    'formal': [{'en': 'formal in', 'zh': '正式的'}],
    'former': [{'en': 'former of', 'zh': '前者'}],
    'fortune': [{'en': 'fortune of', 'zh': '...的财富'}],
    'forum': [{'en': 'forum on', 'zh': '论坛'}],
    'foster': [{'en': 'foster of', 'zh': '...的养育'}],
    'fought': [],
    'fourth': [{'en': 'fourth of', 'zh': '四分之一'}],
    'freely': [{'en': 'freely of', 'zh': '自由地'}],
    'fridge': [{'en': 'in the fridge', 'zh': '在冰箱里'}],
    'friend': [{'en': 'friend of', 'zh': '...的朋友'}],
    'fright': [{'en': 'fright at', 'zh': '...的惊吓'}],
    'front': [{'en': 'in front of', 'zh': '在...前面'}],
    'frost': [{'en': 'frost of', 'zh': '...的霜'}],
    'frown': [{'en': 'frown at', 'zh': '皱眉'}],
    'frozen': [{'en': 'frozen of', 'zh': '冻结的'}],
    'fruit': [{'en': 'fruit of', 'zh': '...的果实'}],
    'fulfil': [{'en': 'fulfil of', 'zh': '履行'}],
    'fully': [{'en': 'fully of', 'zh': '完全地'}],
    'fund': [{'en': 'fund of', 'zh': '...的资金'}],
    'funny': [{'en': 'funny of', 'zh': '...的有趣'}],
    'further': [{'en': 'further of', 'zh': '更远地'}],
    'fuzzy': [{'en': 'fuzzy of', 'zh': '...的模糊'}],
    'gallery': [{'en': 'art gallery', 'zh': '艺术馆'}],
    'gallon': [{'en': 'gallon of', 'zh': '...的加仑'}],
    'gamble': [{'en': 'gamble on', 'zh': '赌博'}],
    'gander': [{'en': 'gander of', 'zh': '...的雄鹅'}],
    'gaoler': [{'en': 'gaoler of', 'zh': '...的狱卒'}],
    'garden': [{'en': 'in the garden', 'zh': '在花园里'}],
    'garlic': [{'en': 'garlic of', 'zh': '大蒜'}],
    'gather': [{'en': 'gather of', 'zh': '聚集'}],
    'gauge': [{'en': 'gauge of', 'zh': '...的标准'}],
    'gender': [{'en': 'gender of', 'zh': '...的性别'}],
    'gentle': [{'en': 'gentle of', 'zh': '温和的'}],
    'genuine': [{'en': 'genuine of', 'zh': '真正的'}],
    'get rid': [],
    'ghost': [{'en': 'ghost of', 'zh': '...的鬼魂'}],
    'giant': [{'en': 'giant of', 'zh': '巨大的'}],
    'giddy': [{'en': 'giddy of', 'zh': '...的头晕'}],
    'ginger': [{'en': 'ginger of', 'zh': '姜'}],
    'girdle': [{'en': 'girdle of', 'zh': '...的腰带'}],
    'glance': [{'en': 'glance at', 'zh': '瞥一眼'}],
    'glare': [{'en': 'glare at', 'zh': '怒视'}],
    'glass': [{'en': 'glass of', 'zh': '一杯'}],
    'gleam': [{'en': 'gleam of', 'zh': '...的闪光'}],
    'glide': [{'en': 'glide of', 'zh': '...的滑行'}],
    'global': [{'en': 'global of', 'zh': '全球的'}],
    'glory': [{'en': 'glory of', 'zh': '...的荣耀'}],
    'glossy': [{'en': 'glossy of', 'zh': '...的光泽'}],
    'glove': [{'en': 'glove of', 'zh': '...的手套'}],
    'glowing': [],
    'glue': [{'en': 'glue to', 'zh': '粘到'}],
    'gnaw': [{'en': 'gnaw at', 'zh': '啃'}],
    'gnome': [{'en': 'gnome of', 'zh': '...的地精'}],
    'gobble': [{'en': 'gobble up', 'zh': '狼吞虎咽'}],
    'goblin': [{'en': 'goblin of', 'zh': '...的妖精'}],
    'godly': [{'en': 'godly of', 'zh': '神圣的'}],
    'goddess': [{'en': 'goddess of', 'zh': '...的女神'}],
    'goggle': [{'en': 'goggle at', 'zh': '瞪眼看'}],
    'golden': [{'en': 'golden of', 'zh': '金色的'}],
    'gondol': [],
    'goodly': [{'en': 'goodly of', 'zh': '...的美好'}],
    'gorge': [{'en': 'gorge of', 'zh': '...的峡谷'}],
    'gorilla': [{'en': 'gorilla of', 'zh': '大猩猩'}],
    'gospel': [{'en': 'gospel of', 'zh': '...的福音'}],
    'gossip': [{'en': 'gossip about', 'zh': '闲聊'}],
    'gourd': [{'en': 'gourd of', 'zh': '...的葫芦'}],
    'govern': [{'en': 'govern of', 'zh': '治理'}],
    'gown': [{'en': 'gown of', 'zh': '...的长袍'}],
    'grab': [{'en': 'grab at', 'zh': '抓'}],
    'grace': [{'en': 'grace of', 'zh': '...的优雅'}],
    'grade': [{'en': 'grade of', 'zh': '...的年级'}],
    'grain': [{'en': 'grain of', 'zh': '一粒'}],
    'grand': [{'en': 'grand of', 'zh': '...的宏伟'}],
    'grant': [{'en': 'grant of', 'zh': '...的授予'}],
    'grape': [{'en': 'grape of', 'zh': '葡萄'}],
    'graph': [{'en': 'graph of', 'zh': '...的图表'}],
    'grasp': [{'en': 'grasp at', 'zh': '抓住'}],
    'grass': [{'en': 'grass of', 'zh': '...的草'}],
    'grate': [{'en': 'grate of', 'zh': '...的摩擦'}],
    'grave': [{'en': 'grave of', 'zh': '...的墓'}],
    'gravel': [{'en': 'gravel of', 'zh': '...的砾石'}],
    'graze': [{'en': 'graze on', 'zh': '吃草'}],
    'grease': [{'en': 'grease of', 'zh': '...的油脂'}],
    'greed': [{'en': 'greed of', 'zh': '...的贪婪'}],
    'green': [{'en': 'green of', 'zh': '绿色的'}],
    'greet': [{'en': 'greet with', 'zh': '问候'}],
    'grew': [],
    'grid': [{'en': 'grid of', 'zh': '...的网格'}],
    'grief': [{'en': 'grief of', 'zh': '...的悲伤'}],
    'grieve': [{'en': 'grieve for', 'zh': '悲痛'}],
    'grill': [{'en': 'grill of', 'zh': '...的烤架'}],
    'grim': [{'en': 'grim of', 'zh': '严酷的'}],
    'grin': [{'en': 'grin at', 'zh': '咧嘴笑'}],
    'grind': [{'en': 'grind of', 'zh': '...的磨'}],
    'grip': [{'en': 'grip of', 'zh': '...的握'}],
    'groan': [{'en': 'groan of', 'zh': '...的呻吟'}],
    'groove': [{'en': 'groove of', 'zh': '...的槽'}],
    'gross': [{'en': 'gross of', 'zh': '总的'}],
    'group': [{'en': 'group of', 'zh': '...的群'}],
    'grove': [{'en': 'grove of', 'zh': '...的小树林'}],
    'growl': [{'en': 'growl at', 'zh': '咆哮'}],
    'grown': [],
    'growth': [{'en': 'growth of', 'zh': '...的增长'}],
    'grub': [{'en': 'grub of', 'zh': '...的蛆'}],
    'gruel': [{'en': 'gruel of', 'zh': '...的粥'}],
    'grumble': [{'en': 'grumble about', 'zh': '抱怨'}],
    'grunt': [{'en': 'grunt of', 'zh': '...的哼声'}],
    'guard': [{'en': 'guard of', 'zh': '...的卫兵'}],
    'guess': [{'en': 'guess at', 'zh': '猜'}],
    'guest': [{'en': 'guest of', 'zh': '...的客人'}],
    'guide': [{'en': 'guide to', 'zh': '...的指南'}],
    'guild': [{'en': 'guild of', 'zh': '...的行会'}],
    'guilt': [{'en': 'guilt of', 'zh': '...的内疚'}],
    'guise': [{'en': 'in the guise of', 'zh': '以...外貌'}],
    'guitar': [{'en': 'play guitar', 'zh': '弹吉他'}],
    'gulf': [{'en': 'gulf of', 'zh': '...的海湾'}],
    'gulp': [{'en': 'gulp down', 'zh': '吞下'}],
    'gummy': [{'en': 'gummy of', 'zh': '...的胶质'}],
    'guru': [{'en': 'guru of', 'zh': '...的导师'}],
    'gust': [{'en': 'gust of', 'zh': '一阵'}],
    'gutter': [{'en': 'gutter of', 'zh': '...的排水沟'}],
    'guy': [],
    'gym': [{'en': 'at the gym', 'zh': '在体育馆'}],
}

words = json.loads(Path('public/data/words.json').read_text())
m = 0
for w in words:
    if w.get('phrases'):
        continue
    if w['word'] in PHRASES and PHRASES[w['word']]:
        w['phrases'] = PHRASES[w['word']]
        m += 1

Path('public/data/words.json').write_text(json.dumps(words, ensure_ascii=False, indent=2))
total = sum(1 for w in words if w.get('phrases'))
no = sum(1 for w in words if not w.get('phrases'))
print(f'✓ 补: {m}')
print(f'总: {total}/{len(words)} ({total*100/len(words):.1f}%)')
print(f'无 phrases: {no}')
