"""W63 phrases P4 - 7 字符 100 词 (CET4/6 高频)"""
import json
from pathlib import Path

PHRASES = {
    'acquire': [{'en': 'acquire knowledge', 'zh': '获得知识'}, {'en': 'acquire skill', 'zh': '习得技能'}],
    'appoint': [{'en': 'appoint as', 'zh': '任命为'}, {'en': 'appoint to', 'zh': '委派到'}],
    'canteen': [{'en': 'school canteen', 'zh': '学校食堂'}],
    'compete': [{'en': 'compete with', 'zh': '与...竞争'}],
    'convict': [{'en': 'convict of', 'zh': '判...有罪'}],
    'crucial': [{'en': 'crucial to', 'zh': '对...至关重要'}],
    'cruelty': [{'en': 'cruelty to', 'zh': '对...的残忍'}],
    'deserve': [{'en': 'deserve to', 'zh': '值得'}],
    'dictate': [{'en': 'dictate to', 'zh': '向...口授'}],
    'diverse': [{'en': 'diverse in', 'zh': '多样的'}],
    'enhance': [{'en': 'enhance with', 'zh': '用...增强'}],
    'entitle': [{'en': 'entitled to', 'zh': '有权...'}],
    'exclude': [{'en': 'exclude from', 'zh': '把...排除'}],
    'exploit': [{'en': 'exploit of', 'zh': '剥削'}],
    'explore': [{'en': 'explore for', 'zh': '勘探'}],
    'honesty': [{'en': 'honesty of', 'zh': '...的诚实'}],
    'imitate': [{'en': 'imitate from', 'zh': '模仿'}],
    'inflate': [{'en': 'inflate with', 'zh': '充气'}],
    'inherit': [{'en': 'inherit from', 'zh': '从...继承'}],
    'inspire': [{'en': 'inspire to', 'zh': '激励'}],
    'install': [{'en': 'install in', 'zh': '安装在'}],
    'justify': [{'en': 'justify with', 'zh': '用...证明'}],
    'mislead': [{'en': 'mislead into', 'zh': '误导'}],
    'paradox': [{'en': 'paradox of', 'zh': '...的悖论'}],
    'predict': [{'en': 'predict that', 'zh': '预测'}],
    'prosper': [{'en': 'prosper in', 'zh': '在...繁荣'}],
    'provoke': [{'en': 'provoke to', 'zh': '激起'}],
    'recruit': [{'en': 'recruit from', 'zh': '招募'}],
    'require': [{'en': 'require of', 'zh': '要求'}],
    'selfish': [{'en': 'selfish of', 'zh': '...的自私'}],
    'specify': [{'en': 'specify that', 'zh': '具体说明'}],
    'startle': [{'en': 'startle at', 'zh': '对...吃惊'}],
    'suppose': [{'en': 'suppose that', 'zh': '假定'}],
    'tedious': [{'en': 'tedious to', 'zh': '对...单调'}],
    'tremble': [{'en': 'tremble with', 'zh': '因...颤抖'}],
    'undergo': [{'en': 'undergo surgery', 'zh': '接受手术'}],
    'violate': [{'en': 'violate law', 'zh': '违反法律'}],
    'actress': [{'en': 'actress in', 'zh': '...的女演员'}],
    'already': [{'en': 'already done', 'zh': '已完成'}],
    'amplify': [{'en': 'amplify signal', 'zh': '放大信号'}],
    'analyse': [{'en': 'analyse data', 'zh': '分析数据'}],
    'anybody': [{'en': 'anybody who', 'zh': '任何人'}],
    'athlete': [{'en': 'top athlete', 'zh': '顶尖运动员'}],
    'awfully': [{'en': 'awfully so', 'zh': '非常'}],
    'awkward': [{'en': 'awkward of', 'zh': '...的笨拙'}],
    'beloved': [{'en': 'beloved by', 'zh': '被...爱戴'}],
    'besides': [{'en': 'besides of', 'zh': '除...之外'}],
    'billion': [{'en': 'a billion of', 'zh': '十亿'}],
    'biscuit': [{'en': 'eat biscuit', 'zh': '吃饼干'}],
    'brittle': [{'en': 'brittle of', 'zh': '...的脆'}],
    'butcher': [{'en': 'butcher shop', 'zh': '肉店'}],
    'cigaret': [{'en': 'cigarette case', 'zh': '烟盒'}],
    'clarify': [{'en': 'clarify that', 'zh': '澄清'}],
    'comfort': [{'en': 'comfort of', 'zh': '...的舒适'}],
    'commit': [{'en': 'commit to', 'zh': '承诺'}, {'en': 'commit crime', 'zh': '犯罪'}],
    'compare': [{'en': 'compare to', 'zh': '与...相比'}],
    'compete': [{'en': 'compete for', 'zh': '为...竞争'}],
    'concern': [{'en': 'concern for', 'zh': '对...的关心'}],
    'conduct': [{'en': 'conduct survey', 'zh': '进行调查'}],
    'confirm': [{'en': 'confirm that', 'zh': '确认'}],
    'conflict': [{'en': 'conflict with', 'zh': '与...冲突'}],
    'confuse': [{'en': 'confuse with', 'zh': '混淆'}],
    'connect': [{'en': 'connect to', 'zh': '连接到'}],
    'conquer': [{'en': 'conquer of', 'zh': '征服'}],
    'consent': [{'en': 'consent to', 'zh': '同意'}],
    'consist': [{'en': 'consist of', 'zh': '由...组成'}],
    'contact': [{'en': 'contact lens', 'zh': '隐形眼镜'}],
    'contain': [{'en': 'contain in', 'zh': '包含'}],
    'content': [{'en': 'content with', 'zh': '满足于'}],
    'context': [{'en': 'in context', 'zh': '在上下文中'}],
    'control': [{'en': 'control over', 'zh': '控制'}],
    'convert': [{'en': 'convert to', 'zh': '转换为'}],
    'convict': [{'en': 'convict of', 'zh': '判...有罪'}],
    'cooking': [{'en': 'cooking class', 'zh': '烹饪课'}],
    'correct': [{'en': 'correct in', 'zh': '正确'}],
    'council': [{'en': 'city council', 'zh': '市议会'}],
    'counter': [{'en': 'counter to', 'zh': '与...相反'}],
    'country': [{'en': 'country of', 'zh': '...的国家'}],
    'couple': [{'en': 'a couple of', 'zh': '几个'}],
    'courage': [{'en': 'courage to', 'zh': '...的勇气'}],
    'creator': [{'en': 'creator of', 'zh': '...的创造者'}],
    'credits': [{'en': 'credits card', 'zh': '信用卡'}],
    'cricket': [{'en': 'play cricket', 'zh': '打板球'}],
    'crimson': [{'en': 'crimson of', 'zh': '...的深红'}],
    'crystal': [{'en': 'crystal of', 'zh': '...的水晶'}],
    'culture': [{'en': 'culture of', 'zh': '...的文化'}],
    'current': [{'en': 'current of', 'zh': '...的电流'}],
    'cushion': [{'en': 'cushion of', 'zh': '...的垫子'}],
    'customs': [{'en': 'customs duty', 'zh': '关税'}],
    'darling': [{'en': 'darling of', 'zh': '...的宝贝'}],
    'deceive': [{'en': 'deceive into', 'zh': '欺骗'}],
    'decline': [{'en': 'decline in', 'zh': '下降'}],
    'decrease': [{'en': 'decrease in', 'zh': '在...下降'}],
    'defense': [{'en': 'defense of', 'zh': '...的防御'}],
    'deliver': [{'en': 'deliver to', 'zh': '递送到'}],
    'demand': [{'en': 'demand for', 'zh': '需求'}],
    'density': [{'en': 'density of', 'zh': '...的密度'}],
    'deposit': [{'en': 'bank deposit', 'zh': '银行存款'}],
    'desktop': [{'en': 'desktop PC', 'zh': '台式电脑'}],
    'despite': [{'en': 'despite of', 'zh': '尽管'}],
    'destroy': [{'en': 'destroy of', 'zh': '破坏'}],
    'details': [{'en': 'details of', 'zh': '...的细节'}],
    'develop': [{'en': 'develop into', 'zh': '发展成'}],
    'digital': [{'en': 'digital age', 'zh': '数字时代'}],
    'disable': [{'en': 'disable of', 'zh': '使...残疾'}],
    'discard': [{'en': 'discard of', 'zh': '丢弃'}],
    'disgust': [{'en': 'disgust at', 'zh': '对...厌恶'}],
    'dismiss': [{'en': 'dismiss from', 'zh': '解雇'}],
    'display': [{'en': 'display on', 'zh': '展示'}],
    'dispose': [{'en': 'dispose of', 'zh': '处理'}],
    'dispute': [{'en': 'dispute over', 'zh': '争论'}],
    'distant': [{'en': 'distant of', 'zh': '...的遥远'}],
    'disturb': [{'en': 'disturb of', 'zh': '打扰'}],
    'diverse': [{'en': 'diverse of', 'zh': '多样的'}],
    'dolphin': [{'en': 'dolphin show', 'zh': '海豚表演'}],
    'doubts': [{'en': 'doubts about', 'zh': '对...的怀疑'}],
    'dozens': [{'en': 'dozens of', 'zh': '许多'}],
    'dramatic': [{'en': 'dramatic of', 'zh': '戏剧性的'}],
    'drawing': [{'en': 'drawing board', 'zh': '画板'}],
    'dressed': [{'en': 'dressed in', 'zh': '穿着'}],
    'driving': [{'en': 'driving license', 'zh': '驾照'}],
    'dropout': [{'en': 'high school dropout', 'zh': '高中辍学生'}],
    'drowsy': [{'en': 'feel drowsy', 'zh': '感到困倦'}],
    'durable': [{'en': 'durable goods', 'zh': '耐用品'}],
    'dusting': [{'en': 'dusting off', 'zh': '掸掉灰尘'}],
    'dynamic': [{'en': 'dynamic of', 'zh': '...的动态'}],
}

words = json.loads(Path('public/data/words.json').read_text())
m = 0
for w in words:
    if w.get('phrases'):
        continue
    if w['word'] in PHRASES and PHRASES[w['word']]:
        w['phrases'] = PHRASES[w['word']]
        m += 1

Path('public/data/words.json').write_text(json.dumps(words, ensure_ascii=False, indent=2))
total = sum(1 for w in words if w.get('phrases'))
no = sum(1 for w in words if not w.get('phrases'))
print(f'✓ 补: {m}')
print(f'总: {total}/{len(words)} ({total*100/len(words):.1f}%)')
print(f'无 phrases: {no}')
