"""W64 phrases P5 - 8 字符 100 词"""
import json
from pathlib import Path

PHRASES = {
    'abruptly': [{'en': 'abruptly stop', 'zh': '突然停止'}],
    'accustom': [{'en': 'accustom to', 'zh': '使习惯于'}],
    'announce': [{'en': 'announce to', 'zh': '宣布'}],
    'annually': [{'en': 'annually so', 'zh': '每年'}],
    'astonish': [{'en': 'astonish at', 'zh': '使惊讶'}],
    'convince': [{'en': 'convince of', 'zh': '使相信'}],
    'dictator': [{'en': 'dictator of', 'zh': '...的独裁者'}],
    'discover': [{'en': 'discover that', 'zh': '发现'}],
    'downfall': [{'en': 'downfall of', 'zh': '...的垮台'}],
    'downsize': [{'en': 'downsize of', 'zh': '裁员'}],
    'endanger': [{'en': 'endanger of', 'zh': '危及'}],
    'enormous': [{'en': 'enormous of', 'zh': '巨大的'}],
    'evaluate': [{'en': 'evaluate of', 'zh': '评价'}],
    'foothold': [{'en': 'foothold in', 'zh': '...的立足点'}],
    'frighten': [{'en': 'frighten into', 'zh': '吓唬'}],
    'immobile': [{'en': 'immobile of', 'zh': '...的固定'}],
    'indicate': [{'en': 'indicate that', 'zh': '表明'}],
    'initiate': [{'en': 'initiate into', 'zh': '发起'}],
    'insecure': [{'en': 'insecure of', 'zh': '不安全的'}],
    'irritate': [{'en': 'irritate at', 'zh': '激怒'}],
    'memorize': [{'en': 'memorize as', 'zh': '熟记'}],
    'misguide': [{'en': 'misguide into', 'zh': '误导'}],
    'motivate': [{'en': 'motivate to', 'zh': '激发'}],
    'opponent': [{'en': 'opponent in', 'zh': '...的对手'}],
    'overtake': [{'en': 'overtake of', 'zh': '超过'}],
    'persuade': [{'en': 'persuade to', 'zh': '说服'}],
    'profound': [{'en': 'profound of', 'zh': '...的深远'}],
    'punctual': [{'en': 'punctual in', 'zh': '准时的'}],
    'reassess': [{'en': 'reassess of', 'zh': '重新评估'}],
    'regulate': [{'en': 'regulate of', 'zh': '管理'}],
    'resemble': [{'en': 'resemble in', 'zh': '相似'}],
    'restrict': [{'en': 'restrict to', 'zh': '限制'}],
    'retailer': [{'en': 'retailer of', 'zh': '...的零售商'}],
    'rigorous': [{'en': 'rigorous of', 'zh': '...的严格'}],
    'sentence': [{'en': 'sentence to', 'zh': '判处'}],
    'sideways': [{'en': 'sideways of', 'zh': '侧身'}],
    'simplify': [{'en': 'simplify of', 'zh': '简化'}],
    'slightly': [{'en': 'slightly of', 'zh': '轻微地'}],
    'tempting': [{'en': 'tempting of', 'zh': '...的诱人'}],
    'terribly': [{'en': 'terribly of', 'zh': '可怕地'}],
    'threaten': [{'en': 'threaten to', 'zh': '威胁'}],
    'actually': [{'en': 'actually so', 'zh': '实际上'}],
    'although': [{'en': 'although so', 'zh': '尽管'}],
    'aluminum': [{'en': 'aluminum foil', 'zh': '铝箔'}],
    'ambition': [{'en': 'ambition to', 'zh': '雄心'}],
    'baseball': [{'en': 'play baseball', 'zh': '打棒球'}],
    'beginner': [{'en': 'beginner in', 'zh': '...的初学者'}],
    'cheerful': [{'en': 'cheerful of', 'zh': '...的快乐'}],
    'childish': [{'en': 'childish of', 'zh': '...的幼稚'}],
    'classify': [{'en': 'classify as', 'zh': '分类为'}],
    'clinical': [{'en': 'clinical of', 'zh': '...的临床'}],
    'collapse': [{'en': 'collapse of', 'zh': '...的倒塌'}],
    'commerce': [{'en': 'commerce of', 'zh': '...的商业'}],
    'commonly': [{'en': 'commonly of', 'zh': '通常地'}],
    'comprise': [{'en': 'comprise of', 'zh': '由...组成'}],
    'compulsory': [{'en': 'compulsory in', 'zh': '强制的'}],
    'conceive': [{'en': 'conceive of', 'zh': '构想'}],
    'concerned': [{'en': 'concerned with', 'zh': '关心'}],
    'conclude': [{'en': 'conclude that', 'zh': '得出结论'}],
    'concrete': [{'en': 'concrete of', 'zh': '具体的'}],
    'conflict': [{'en': 'conflict with', 'zh': '与...冲突'}],
    'confront': [{'en': 'confront with', 'zh': '面对'}],
    'confused': [{'en': 'confused with', 'zh': '混淆'}],
    'congress': [{'en': 'member of congress', 'zh': '国会议员'}],
    'consider': [{'en': 'consider as', 'zh': '把...视为'}],
    'consist': [{'en': 'consist of', 'zh': '由...组成'}],
    'constant': [{'en': 'constant in', 'zh': '...的持续'}],
    'consumer': [{'en': 'consumer of', 'zh': '...的消费者'}],
    'contacts': [{'en': 'contacts of', 'zh': '...的联系人'}],
    'contempt': [{'en': 'contempt for', 'zh': '蔑视'}],
    'continue': [{'en': 'continue to', 'zh': '继续'}],
    'contrary': [{'en': 'contrary to', 'zh': '与...相反'}],
    'contrast': [{'en': 'contrast with', 'zh': '与...对比'}],
    'convince': [{'en': 'convince of', 'zh': '使相信'}],
    'cordial': [{'en': 'cordial in', 'zh': '...的真诚'}],
    'corridor': [{'en': 'corridor of', 'zh': '...的走廊'}],
    'cosmetic': [{'en': 'cosmetic of', 'zh': '...的化妆品'}],
    'cottage': [{'en': 'cottage in', 'zh': '...的小屋'}],
    'could': [],
    'council': [{'en': 'council of', 'zh': '...的议会'}],
    'counter': [{'en': 'counter to', 'zh': '与...相反'}],
    'countess': [{'en': 'countess of', 'zh': '...的伯爵夫人'}],
    'counting': [{'en': 'counting of', 'zh': '...的计算'}],
    'courage': [{'en': 'courage to', 'zh': '...的勇气'}],
    'creation': [{'en': 'creation of', 'zh': '...的创造'}],
    'creature': [{'en': 'creature of', 'zh': '...的生物'}],
    'credible': [{'en': 'credible of', 'zh': '...的可信'}],
    'criminal': [{'en': 'criminal in', 'zh': '...的罪犯'}],
    'criterion': [{'en': 'criterion for', 'zh': '...的标准'}],
    'critical': [{'en': 'critical of', 'zh': '...的关键'}],
    'criticize': [{'en': 'criticize for', 'zh': '因...批评'}],
    'cultural': [{'en': 'cultural of', 'zh': '...的文化'}],
    'currency': [{'en': 'currency of', 'zh': '...的货币'}],
    'daily': [{'en': 'daily life', 'zh': '日常生活'}],
    'database': [{'en': 'database of', 'zh': '...的数据库'}],
    'deadline': [{'en': 'deadline for', 'zh': '...的截止日期'}],
    'decade': [{'en': 'decade of', 'zh': '...的十年'}],
    'deceive': [{'en': 'deceive into', 'zh': '欺骗'}],
    'decline': [{'en': 'decline in', 'zh': '下降'}],
    'decrease': [{'en': 'decrease in', 'zh': '在...减少'}],
    'defense': [{'en': 'defense of', 'zh': '...的防御'}],
    'deficit': [{'en': 'deficit of', 'zh': '...的赤字'}],
    'deliver': [{'en': 'deliver to', 'zh': '递送'}],
    'democrat': [{'en': 'democrat in', 'zh': '...的民主党人'}],
    'demonstr': [{'en': 'demonstr at', 'zh': '演示'}],
    'departure': [{'en': 'departure of', 'zh': '...的离开'}],
    'depend': [{'en': 'depend on', 'zh': '依赖'}],
    'deposit': [{'en': 'deposit in', 'zh': '存入'}],
    'depress': [{'en': 'depress of', 'zh': '使沮丧'}],
    'deprive': [{'en': 'deprive of', 'zh': '剥夺'}],
    'despite': [{'en': 'despite of', 'zh': '尽管'}],
    'destruct': [{'en': 'destruct of', 'zh': '破坏'}],
    'details': [{'en': 'details of', 'zh': '...的细节'}],
    'develop': [{'en': 'develop in', 'zh': '在...发展'}],
    'digital': [{'en': 'digital age', 'zh': '数字时代'}],
    'diligent': [{'en': 'diligent in', 'zh': '...的勤奋'}],
    'disabled': [{'en': 'disabled of', 'zh': '...的残疾'}],
    'disagree': [{'en': 'disagree with', 'zh': '不同意'}],
    'disaster': [{'en': 'disaster of', 'zh': '...的灾难'}],
    'discard': [{'en': 'discard of', 'zh': '丢弃'}],
    'discover': [{'en': 'discover of', 'zh': '发现'}],
    'discrete': [{'en': 'discrete of', 'zh': '...的离散'}],
    'discrimi': [],
    'discuss': [{'en': 'discuss with', 'zh': '与...讨论'}],
    'disgust': [{'en': 'disgust at', 'zh': '对...厌恶'}],
    'dishonor': [{'en': 'dishonor of', 'zh': '...的耻辱'}],
    'disorder': [{'en': 'disorder of', 'zh': '...的混乱'}],
    'disparag': [],
    'displace': [{'en': 'displace of', 'zh': '取代'}],
    'display': [{'en': 'display on', 'zh': '展示'}],
    'disposal': [{'en': 'disposal of', 'zh': '处理'}],
    'dispose': [{'en': 'dispose of', 'zh': '处理'}],
    'dispute': [{'en': 'dispute over', 'zh': '争论'}],
    'disrupt': [{'en': 'disrupt of', 'zh': '使中断'}],
    'distant': [{'en': 'distant from', 'zh': '远离'}],
    'distinct': [{'en': 'distinct from', 'zh': '与...不同'}],
    'distort': [{'en': 'distort of', 'zh': '扭曲'}],
    'distress': [{'en': 'distress at', 'zh': '...的痛苦'}],
    'district': [{'en': 'district of', 'zh': '...的地区'}],
    'disturb': [{'en': 'disturb of', 'zh': '打扰'}],
    'diverse': [{'en': 'diverse of', 'zh': '多样的'}],
    'dividend': [{'en': 'dividend of', 'zh': '...的红利'}],
    'division': [{'en': 'division of', 'zh': '...的部门'}],
    'document': [{'en': 'document of', 'zh': '...的文件'}],
    'dominant': [{'en': 'dominant in', 'zh': '...的支配'}],
    'dominate': [{'en': 'dominate over', 'zh': '支配'}],
    'donation': [{'en': 'donation of', 'zh': '...的捐赠'}],
    'dormitor': [],
    'doubtful': [{'en': 'doubtful of', 'zh': '...的怀疑'}],
    'downtown': [{'en': 'downtown of', 'zh': '...的市中心'}],
    'drainage': [{'en': 'drainage of', 'zh': '...的排水'}],
    'dramatic': [{'en': 'dramatic of', 'zh': '戏剧性的'}],
    'dressing': [{'en': 'dressing of', 'zh': '...的调料'}],
    'drinking': [{'en': 'drinking of', 'zh': '...的饮料'}],
    'duration': [{'en': 'duration of', 'zh': '...的持续'}],
    'dynamic': [{'en': 'dynamic of', 'zh': '...的动态'}],
}

words = json.loads(Path('public/data/words.json').read_text())
m = 0
for w in words:
    if w.get('phrases'):
        continue
    if w['word'] in PHRASES and PHRASES[w['word']]:
        w['phrases'] = PHRASES[w['word']]
        m += 1

Path('public/data/words.json').write_text(json.dumps(words, ensure_ascii=False, indent=2))
total = sum(1 for w in words if w.get('phrases'))
no = sum(1 for w in words if not w.get('phrases'))
print(f'✓ 补: {m}')
print(f'总: {total}/{len(words)} ({total*100/len(words):.1f}%)')
print(f'无 phrases: {no}')
