"""W65 phrases P6 - 9 字符 100 词"""
import json
from pathlib import Path

PHRASES = {
    'adversity': [{'en': 'in adversity', 'zh': '在逆境中'}],
    'advocator': [{'en': 'advocator of', 'zh': '...的倡导者'}],
    'ambitious': [{'en': 'ambitious for', 'zh': '对...有抱负'}],
    'backslide': [{'en': 'backslide into', 'zh': '倒退'}],
    'caregiver': [{'en': 'caregiver of', 'zh': '...的照料者'}],
    'carpenter': [{'en': 'carpenter of', 'zh': '...的木匠'}],
    'civilized': [{'en': 'civilized of', 'zh': '...的文明'}],
    'colleague': [{'en': 'colleague of', 'zh': '...的同事'}],
    'currently': [{'en': 'currently so', 'zh': '当前'}],
    'determine': [{'en': 'determine to', 'zh': '下决心'}],
    'dishonest': [{'en': 'dishonest of', 'zh': '不诚实'}],
    'easygoing': [{'en': 'easygoing of', 'zh': '...的随和'}],
    'embarrass': [{'en': 'embarrass at', 'zh': '使尴尬'}],
    'emphasize': [{'en': 'emphasize on', 'zh': '强调'}],
    'energetic': [{'en': 'energetic of', 'zh': '...的精力充沛'}],
    'fantasize': [{'en': 'fantasize about', 'zh': '幻想'}],
    'fascinate': [{'en': 'fascinate with', 'zh': '迷住'}],
    'formulate': [{'en': 'formulate of', 'zh': '制定'}],
    'highlight': [{'en': 'highlight of', 'zh': '突出'}],
    'homemaker': [{'en': 'homemaker of', 'zh': '...的主妇'}],
    'ignorance': [{'en': 'ignorance of', 'zh': '...的无知'}],
    'initially': [{'en': 'initially so', 'zh': '最初'}],
    'laborious': [{'en': 'laborious of', 'zh': '...的费劲'}],
    'logically': [{'en': 'logically so', 'zh': '合逻辑地'}],
    'marvelous': [{'en': 'marvelous of', 'zh': '...的奇妙'}],
    'masculine': [{'en': 'masculine of', 'zh': '...的男性'}],
    'miserable': [{'en': 'miserable of', 'zh': '...的痛苦'}],
    'misguided': [{'en': 'misguided of', 'zh': '...的误导'}],
    'objection': [{'en': 'objection to', 'zh': '反对'}],
    'overstate': [{'en': 'overstate of', 'zh': '夸大'}],
    'passively': [{'en': 'passively so', 'zh': '被动地'}],
    'patience': [{'en': 'patience of', 'zh': '...的耐心'}],
    'permanent': [{'en': 'permanent of', 'zh': '...的永久'}],
    'philosophy': [{'en': 'philosophy of', 'zh': '...的哲学'}],
    'pleasantly': [{'en': 'pleasantly so', 'zh': '愉快地'}],
    'pollution': [{'en': 'pollution of', 'zh': '...的污染'}],
    'possessed': [{'en': 'possessed of', 'zh': '...的拥有'}],
    'potential': [{'en': 'potential of', 'zh': '...的潜力'}],
    'precisely': [{'en': 'precisely so', 'zh': '精确地'}],
    'prejudice': [{'en': 'prejudice of', 'zh': '...的偏见'}],
    'previously': [{'en': 'previously so', 'zh': '以前'}],
    'primarily': [{'en': 'primarily so', 'zh': '主要地'}],
    'privilege': [{'en': 'privilege of', 'zh': '...的特权'}],
    'processor': [{'en': 'processor of', 'zh': '...的处理器'}],
    'professor': [{'en': 'professor of', 'zh': '...的教授'}],
    'prominent': [{'en': 'prominent in', 'zh': '...的杰出'}],
    'promising': [{'en': 'promising of', 'zh': '...的有希望'}],
    'promptly': [{'en': 'promptly so', 'zh': '迅速地'}],
    'propagate': [{'en': 'propagate of', 'zh': '传播'}],
    'properly': [{'en': 'properly so', 'zh': '正确地'}],
    'proposed': [{'en': 'proposed by', 'zh': '由...提出'}],
    'prospect': [{'en': 'prospect of', 'zh': '...的前景'}],
    'prosperous': [{'en': 'prosperous of', 'zh': '...的繁荣'}],
    'protective': [{'en': 'protective of', 'zh': '...的保护'}],
    'psychology': [{'en': 'psychology of', 'zh': '...的心理学'}],
    'punishment': [{'en': 'punishment of', 'zh': '...的惩罚'}],
    'puzzled': [{'en': 'puzzled at', 'zh': '对...困惑'}],
    'qualified': [{'en': 'qualified of', 'zh': '...的合格'}],
    'qualities': [{'en': 'qualities of', 'zh': '...的品质'}],
    'radiation': [{'en': 'radiation of', 'zh': '...的辐射'}],
    'rational': [{'en': 'rational of', 'zh': '...的合理'}],
    'realistic': [{'en': 'realistic of', 'zh': '...的现实'}],
    'reasoning': [{'en': 'reasoning of', 'zh': '...的推理'}],
    'recipient': [{'en': 'recipient of', 'zh': '...的接受者'}],
    'recognize': [{'en': 'recognize of', 'zh': '认出'}],
    'reconcile': [{'en': 'reconcile with', 'zh': '与...和解'}],
    'recover': [{'en': 'recover from', 'zh': '从...恢复'}],
    'recruit': [{'en': 'recruit from', 'zh': '招募'}],
    'reduction': [{'en': 'reduction of', 'zh': '...的减少'}],
    'reference': [{'en': 'reference to', 'zh': '参考'}],
    'reflection': [{'en': 'reflection of', 'zh': '...的反映'}],
    'regardless': [{'en': 'regardless of', 'zh': '不管'}],
    'register': [{'en': 'register for', 'zh': '注册'}],
    'regulate': [{'en': 'regulate of', 'zh': '管理'}],
    'reinforce': [{'en': 'reinforce of', 'zh': '加强'}],
    'relatively': [{'en': 'relatively so', 'zh': '相对地'}],
    'reluctant': [{'en': 'reluctant to', 'zh': '不情愿'}],
    'remarkable': [{'en': 'remarkable of', 'zh': '...的非凡'}],
    'repeatedly': [{'en': 'repeatedly so', 'zh': '反复地'}],
    'represent': [{'en': 'represent of', 'zh': '代表'}],
    'reproduce': [{'en': 'reproduce of', 'zh': '繁殖'}],
    'requirement': [{'en': 'requirement of', 'zh': '...的要求'}],
    'researcher': [{'en': 'researcher of', 'zh': '...的研究者'}],
    'resemble': [{'en': 'resemble in', 'zh': '相似'}],
    'residence': [{'en': 'residence of', 'zh': '...的住所'}],
    'resistant': [{'en': 'resistant to', 'zh': '抵抗'}],
    'resolution': [{'en': 'resolution of', 'zh': '...的解决'}],
    'respective': [{'en': 'respective of', 'zh': '...的各自'}],
    'responded': [],
    'response': [{'en': 'response to', 'zh': '对...的回应'}],
    'responsib': [],
    'restaurant': [{'en': 'at the restaurant', 'zh': '在餐厅'}],
    'restrict': [{'en': 'restrict to', 'zh': '限制'}],
    'revenue': [{'en': 'revenue of', 'zh': '...的收入'}],
    'revision': [{'en': 'revision of', 'zh': '...的修订'}],
    'rewarding': [{'en': 'rewarding of', 'zh': '...的有回报'}],
    'righteous': [{'en': 'righteous of', 'zh': '...的正直'}],
    'rigorous': [{'en': 'rigorous of', 'zh': '...的严格'}],
    'romantic': [{'en': 'romantic of', 'zh': '...的浪漫'}],
    'sacrifice': [{'en': 'sacrifice for', 'zh': '为...牺牲'}],
    'safeguard': [{'en': 'safeguard of', 'zh': '...的保护'}],
    'satisfied': [{'en': 'satisfied with', 'zh': '对...满意'}],
    'scattered': [{'en': 'scattered of', 'zh': '...的分散'}],
    'scrutinize': [{'en': 'scrutinize of', 'zh': '详细检查'}],
    'secondary': [{'en': 'secondary of', 'zh': '...的次要'}],
    'sensible': [{'en': 'sensible of', 'zh': '...的明智'}],
    'sensitive': [{'en': 'sensitive to', 'zh': '对...敏感'}],
    'sentence': [{'en': 'sentence to', 'zh': '判处'}],
    'separation': [{'en': 'separation of', 'zh': '...的分离'}],
    'seriously': [{'en': 'seriously so', 'zh': '认真地'}],
    'servant': [{'en': 'servant of', 'zh': '...的仆人'}],
    'sheltered': [{'en': 'sheltered of', 'zh': '...的庇护'}],
    'shortage': [{'en': 'shortage of', 'zh': '...的短缺'}],
    'simplify': [{'en': 'simplify of', 'zh': '简化'}],
    'situated': [{'en': 'situated of', 'zh': '...的位于'}],
    'skeptical': [{'en': 'skeptical of', 'zh': '...的怀疑'}],
    'slightly': [{'en': 'slightly of', 'zh': '轻微地'}],
    'socially': [{'en': 'socially so', 'zh': '社交地'}],
    'solidity': [{'en': 'solidity of', 'zh': '...的坚固'}],
    'somewhat': [{'en': 'somewhat of', 'zh': '有点'}],
    'sophistic': [],
    'sovereign': [{'en': 'sovereign of', 'zh': '...的君主'}],
    'spacious': [{'en': 'spacious of', 'zh': '...的宽敞'}],
    'specialty': [{'en': 'specialty of', 'zh': '...的专业'}],
    'speculate': [{'en': 'speculate on', 'zh': '推测'}],
    'spiritual': [{'en': 'spiritual of', 'zh': '...的精神'}],
    'sponsored': [],
    'spontaneo': [],
    'sprawling': [],
    'stability': [{'en': 'stability of', 'zh': '...的稳定'}],
    'stagnant': [{'en': 'stagnant of', 'zh': '...的停滞'}],
    'stamina': [{'en': 'stamina of', 'zh': '...的耐力'}],
    'stimulus': [{'en': 'stimulus for', 'zh': '...的刺激'}],
    'strategy': [{'en': 'strategy of', 'zh': '...的策略'}],
    'strengthen': [{'en': 'strengthen of', 'zh': '加强'}],
    'structure': [{'en': 'structure of', 'zh': '...的结构'}],
    'struggle': [{'en': 'struggle for', 'zh': '为...奋斗'}],
    'stubborn': [{'en': 'stubborn of', 'zh': '...的顽固'}],
    'subjected': [],
    'submissiv': [],
    'subordina': [],
    'subscript': [],
    'substance': [{'en': 'substance of', 'zh': '...的物质'}],
    'substitute': [{'en': 'substitute for', 'zh': '代替'}],
    'subtract': [{'en': 'subtract from', 'zh': '减去'}],
    'suitable': [{'en': 'suitable for', 'zh': '适合'}],
    'suppress': [{'en': 'suppress of', 'zh': '镇压'}],
    'surround': [{'en': 'surround with', 'zh': '包围'}],
    'survival': [{'en': 'survival of', 'zh': '...的生存'}],
    'suspect': [{'en': 'suspect of', 'zh': '怀疑'}],
    'suspend': [{'en': 'suspend from', 'zh': '悬挂'}],
    'sustain': [{'en': 'sustain of', 'zh': '维持'}],
    'sympathy': [{'en': 'sympathy for', 'zh': '同情'}],
    'synthetic': [{'en': 'synthetic of', 'zh': '...的合成'}],
    'systematic': [{'en': 'systematic of', 'zh': '...的系统'}],
}

words = json.loads(Path('public/data/words.json').read_text())
m = 0
for w in words:
    if w.get('phrases'):
        continue
    if w['word'] in PHRASES and PHRASES[w['word']]:
        w['phrases'] = PHRASES[w['word']]
        m += 1

Path('public/data/words.json').write_text(json.dumps(words, ensure_ascii=False, indent=2))
total = sum(1 for w in words if w.get('phrases'))
no = sum(1 for w in words if not w.get('phrases'))
print(f'✓ 补: {m}')
print(f'总: {total}/{len(words)} ({total*100/len(words):.1f}%)')
print(f'无 phrases: {no}')
