"""W69 phrases P10 - 9-11 字符 188 词"""
import json
from pathlib import Path

PHRASES = {
    'accessary': [{'en': 'accessary of', 'zh': '...的从犯'}],
    'adjective': [{'en': 'adjective of', 'zh': '...的形容词'}],
    'admirable': [{'en': 'admirable of', 'zh': '...的令人钦佩'}],
    'advisable': [{'en': 'advisable of', 'zh': '...的可取'}],
    'aeroplane': [{'en': 'aeroplane of', 'zh': '...的飞机'}],
    'affection': [{'en': 'affection for', 'zh': '...的爱'}],
    'afterward': [{'en': 'afterward so', 'zh': '之后'}],
    'afterwards': [{'en': 'afterwards so', 'zh': '之后'}],
    'altogether': [{'en': 'altogether so', 'zh': '完全地'}],
    'ambiguous': [{'en': 'ambiguous of', 'zh': '...的含糊'}],
    'antarctic': [{'en': 'Antarctic of', 'zh': '南极的'}],
    'apparatus': [{'en': 'apparatus of', 'zh': '...的仪器'}],
    'assistant': [{'en': 'assistant to', 'zh': '...的助理'}],
    'astronaut': [{'en': 'astronaut of', 'zh': '...的宇航员'}],
    'athletics': [{'en': 'athletics of', 'zh': '...的体育'}],
    'attentive': [{'en': 'attentive to', 'zh': '对...注意'}],
    'authentic': [{'en': 'authentic of', 'zh': '...的真实的'}],
    'backwards': [{'en': 'backwards of', 'zh': '向后地'}],
    'barbershop': [{'en': 'barbershop of', 'zh': '...的理发店'}],
    'basically': [{'en': 'basically so', 'zh': '基本上'}],
    'bedclothes': [{'en': 'bedclothes of', 'zh': '...的床上用品'}],
    'behaviour': [{'en': 'behaviour of', 'zh': '...的行为'}],
    'behavious': [],
    'biography': [{'en': 'biography of', 'zh': '...的传记'}],
    'birthplace': [{'en': 'birthplace of', 'zh': '...的出生地'}],
    'bookshelf': [{'en': 'bookshelf of', 'zh': '...的书架'}],
    'breathless': [{'en': 'breathless from', 'zh': '因...气喘吁吁'}],
    'bridegroom': [{'en': 'bridegroom of', 'zh': '...的新郎'}],
    'cafeteria': [{'en': 'at the cafeteria', 'zh': '在自助餐厅'}],
    'cathedral': [{'en': 'cathedral of', 'zh': '...的大教堂'}],
    'centimeter': [{'en': 'centimeter of', 'zh': '...的厘米'}],
    'centimetre': [{'en': 'centimetre of', 'zh': '...的厘米'}],
    'certainly': [{'en': 'certainly so', 'zh': '当然地'}],
    'chairwoman': [{'en': 'chairwoman of', 'zh': '...的女主席'}],
    'changeable': [{'en': 'changeable of', 'zh': '...的多变'}],
    'circulate': [{'en': 'circulate of', 'zh': '循环'}],
    'classmate': [{'en': 'classmate of', 'zh': '...的同学'}],
    'communism': [{'en': 'communism of', 'zh': '...的共产主义'}],
    'completely': [{'en': 'completely so', 'zh': '完全地'}],
    'complicate': [{'en': 'complicate of', 'zh': '使复杂'}],
    'conversely': [{'en': 'conversely so', 'zh': '相反地'}],
    'definitely': [{'en': 'definitely so', 'zh': '明确地'}],
    'desirable': [{'en': 'desirable of', 'zh': '...的合乎需要'}],
    'desperate': [{'en': 'desperate of', 'zh': '...的绝望'}],
    'dictation': [{'en': 'dictation of', 'zh': '...的口授'}],
    'direction': [{'en': 'direction of', 'zh': '...的方向'}],
    'disappoint': [{'en': 'disappoint of', 'zh': '使失望'}],
    'dishonour': [{'en': 'dishonour of', 'zh': '...的耻辱'}],
    'displease': [{'en': 'displease of', 'zh': '使不高兴'}],
    'doubtless': [{'en': 'doubtless of', 'zh': '无疑的'}],
    'eastwards': [{'en': 'eastwards so', 'zh': '向东地'}],
    'elsewhere': [{'en': 'elsewhere so', 'zh': '在别处'}],
    'Englishman': [{'en': 'Englishman of', 'zh': '...的英国人'}],
    'enjoyable': [{'en': 'enjoyable of', 'zh': '...的愉快'}],
    'entertain': [{'en': 'entertain of', 'zh': '招待'}],
    'evaporate': [{'en': 'evaporate of', 'zh': '蒸发'}],
    'eventually': [{'en': 'eventually so', 'zh': '最终地'}],
    'everybody': [{'en': 'everybody of', 'zh': '...的每个人'}],
    'eyewitness': [{'en': 'eyewitness of', 'zh': '...的目击者'}],
    'favourite': [{'en': 'favourite of', 'zh': '...的最爱'}],
    'fingernail': [{'en': 'fingernail of', 'zh': '...的指甲'}],
    'fireplace': [{'en': 'fireplace of', 'zh': '...的壁炉'}],
    'fireworks': [{'en': 'fireworks of', 'zh': '...的烟火'}],
    'fisherman': [{'en': 'fisherman of', 'zh': '...的渔夫'}],
    'flashlight': [{'en': 'flashlight of', 'zh': '...的手电筒'}],
    'foreigner': [{'en': 'foreigner of', 'zh': '...的外国人'}],
    'forgetful': [{'en': 'forgetful of', 'zh': '...的健忘'}],
    'fortnight': [{'en': 'fortnight of', 'zh': '...的两周'}],
    'Frenchman': [{'en': 'Frenchman of', 'zh': '...的法国人'}],
    'furniture': [{'en': 'furniture of', 'zh': '...的家具'}],
    'glasshouse': [{'en': 'glasshouse of', 'zh': '...的玻璃房'}],
    'gradually': [{'en': 'gradually so', 'zh': '逐渐地'}],
    'grandchild': [{'en': 'grandchild of', 'zh': '...的孙子'}],
    'gunpowder': [{'en': 'gunpowder of', 'zh': '...的火药'}],
    'gymnasium': [{'en': 'gymnasium of', 'zh': '...的体育馆'}],
    'hamburger': [{'en': 'hamburger of', 'zh': '...的汉堡包'}],
    'handtruck': [{'en': 'handtruck of', 'zh': '...的手推车'}],
    'headmaster': [{'en': 'headmaster of', 'zh': '...的校长'}],
    'helicopter': [{'en': 'helicopter of', 'zh': '...的直升机'}],
    'hibernate': [{'en': 'hibernate of', 'zh': '冬眠'}],
    'honourable': [{'en': 'honourable of', 'zh': '...的光荣'}],
    'housewife': [{'en': 'housewife of', 'zh': '...的家庭主妇'}],
    'impatient': [{'en': 'impatient of', 'zh': '...的不耐烦'}],
    'impressive': [{'en': 'impressive of', 'zh': '...的令人印象深'}],
    'indignant': [{'en': 'indignant of', 'zh': '...的愤慨'}],
    'inhabitant': [{'en': 'inhabitant of', 'zh': '...的居民'}],
    'instantly': [{'en': 'instantly so', 'zh': '立即地'}],
    'jewellery': [{'en': 'jewellery of', 'zh': '...的珠宝'}],
    'journalist': [{'en': 'journalist of', 'zh': '...的新闻记者'}],
    'kilometer': [{'en': 'kilometer of', 'zh': '...的千米'}],
    'librarian': [{'en': 'librarian of', 'zh': '...的图书管理员'}],
    'marvellous': [{'en': 'marvellous of', 'zh': '...的奇妙'}],
    'millimeter': [{'en': 'millimeter of', 'zh': '...的毫米'}],
    'millimetre': [{'en': 'millimetre of', 'zh': '...的毫米'}],
    'miniskirt': [{'en': 'miniskirt of', 'zh': '...的超短裙'}],
    'motherland': [{'en': 'motherland of', 'zh': '...的祖国'}],
    'motorbike': [{'en': 'motorbike of', 'zh': '...的摩托车'}],
    'moustache': [{'en': 'moustache of', 'zh': '...的胡子'}],
    'mysterious': [{'en': 'mysterious of', 'zh': '...的神秘'}],
    'nationwide': [{'en': 'nationwide so', 'zh': '全国性地'}],
    'naturally': [{'en': 'naturally so', 'zh': '自然地'}],
    'neighbour': [{'en': 'neighbour of', 'zh': '...的邻居'}],
    'northeast': [{'en': 'northeast of', 'zh': '...的东北'}],
    'northwards': [{'en': 'northwards so', 'zh': '向北地'}],
    'noticeable': [{'en': 'noticeable of', 'zh': '...的显著'}],
    'obviously': [{'en': 'obviously so', 'zh': '明显地'}],
    'orchestra': [{'en': 'orchestra of', 'zh': '...的管弦乐队'}],
    'organiser': [{'en': 'organiser of', 'zh': '...的组织者'}],
    'outspoken': [{'en': 'outspoken of', 'zh': '...的坦率'}],
    'overcharge': [{'en': 'overcharge of', 'zh': '索价过高'}],
    'overnight': [{'en': 'overnight of', 'zh': '...的一夜'}],
    'overweight': [{'en': 'overweight of', 'zh': '...的超重'}],
    'paperwork': [{'en': 'paperwork of', 'zh': '...的文书工作'}],
    'patiently': [{'en': 'patiently so', 'zh': '耐心地'}],
    'penetrate': [{'en': 'penetrate of', 'zh': '穿透'}],
    'performer': [{'en': 'performer of', 'zh': '...的表演者'}],
    'playground': [{'en': 'playground of', 'zh': '...的操场'}],
    'plentiful': [{'en': 'plentiful of', 'zh': '...的丰富'}],
    'pointless': [{'en': 'pointless of', 'zh': '...的无意义'}],
    'politician': [{'en': 'politician of', 'zh': '...的政治家'}],
    'preceding': [{'en': 'preceding of', 'zh': '...的先前'}],
    'preferable': [{'en': 'preferable of', 'zh': '...的更可取'}],
    'presently': [{'en': 'presently so', 'zh': '目前地'}],
    'publicize': [{'en': 'publicize of', 'zh': '宣传'}],
    'punctuate': [{'en': 'punctuate of', 'zh': '加标点'}],
    'radically': [{'en': 'radically so', 'zh': '根本地'}],
    'rearrange': [{'en': 'rearrange of', 'zh': '重新安排'}],
    'recognise': [{'en': 'recognise of', 'zh': '认出'}],
    'reflexion': [{'en': 'reflexion of', 'zh': '...的反射'}],
    'regularly': [{'en': 'regularly so', 'zh': '有规律地'}],
    'reservior': [{'en': 'reservior of', 'zh': '...的储水池'}],
    'respectful': [{'en': 'respectful of', 'zh': '...的尊敬'}],
    'ridiculous': [{'en': 'ridiculous of', 'zh': '...的荒谬'}],
    'routinely': [{'en': 'routinely so', 'zh': '例行地'}],
    'salesgirl': [{'en': 'salesgirl of', 'zh': '...的女售货员'}],
    'saleswoman': [{'en': 'saleswoman of', 'zh': '...的女售货员'}],
    'sceptical': [{'en': 'sceptical of', 'zh': '...的怀疑'}],
    'schoolbag': [{'en': 'schoolbag of', 'zh': '...的书包'}],
    'schoolboy': [{'en': 'schoolboy of', 'zh': '...的男学生'}],
    'schoolgirl': [{'en': 'schoolgirl of', 'zh': '...的女学生'}],
    'schoolmate': [{'en': 'schoolmate of', 'zh': '...的同学'}],
    'secondhand': [{'en': 'secondhand of', 'zh': '...的二手'}],
    'semicircle': [{'en': 'semicircle of', 'zh': '...的半圆'}],
    'September': [{'en': 'in September', 'zh': '在九月'}],
    'seventeen': [{'en': 'seventeen of', 'zh': '...的十七'}],
    'shopkeeper': [{'en': 'shopkeeper of', 'zh': '...的店主'}],
    'similarly': [{'en': 'similarly so', 'zh': '相似地'}],
    'sixteenth': [{'en': 'sixteenth of', 'zh': '...的第十六'}],
    'skateboard': [{'en': 'skateboard of', 'zh': '...的滑板'}],
    'skillfully': [{'en': 'skillfully so', 'zh': '熟练地'}],
    'skyrocket': [{'en': 'skyrocket of', 'zh': '...的火箭'}],
    'skyscraper': [{'en': 'skyscraper of', 'zh': '...的摩天大楼'}],
    'socialize': [{'en': 'socialize of', 'zh': '社交'}],
    'sometimes': [{'en': 'sometimes so', 'zh': '有时'}],
    'southeast': [{'en': 'southeast of', 'zh': '...的东南'}],
    'spaghetti': [{'en': 'spaghetti of', 'zh': '...的意大利面'}],
    'spokesman': [{'en': 'spokesman of', 'zh': '...的发言人'}],
    'sportsman': [{'en': 'sportsman of', 'zh': '...的运动员'}],
    'statesman': [{'en': 'statesman of', 'zh': '...的政治家'}],
    'stereotype': [{'en': 'stereotype of', 'zh': '...的刻板印象'}],
    'stopwatch': [{'en': 'stopwatch of', 'zh': '...的秒表'}],
    'subscribe': [{'en': 'subscribe to', 'zh': '订阅'}],
    'subsidize': [{'en': 'subsidize of', 'zh': '补贴'}],
    'summarize': [{'en': 'summarize of', 'zh': '总结'}],
    'sunglasses': [{'en': 'sunglasses of', 'zh': '...的太阳镜'}],
    'suspicion': [{'en': 'suspicion of', 'zh': '...的怀疑'}],
    'symbolize': [{'en': 'symbolize of', 'zh': '象征'}],
    'tasteless': [{'en': 'tasteless of', 'zh': '...的乏味'}],
    'therefore': [{'en': 'therefore so', 'zh': '因此'}],
    'toothache': [{'en': 'toothache of', 'zh': '...的牙痛'}],
    'toothpaste': [{'en': 'toothpaste of', 'zh': '...的牙膏'}],
    'traveller': [{'en': 'traveller of', 'zh': '...的旅行者'}],
    'trolleybus': [{'en': 'trolleybus of', 'zh': '...的无轨电车'}],
    'underline': [{'en': 'underline of', 'zh': '...的下划线'}],
    'underneath': [{'en': 'underneath so', 'zh': '在下面'}],
    'undervalue': [{'en': 'undervalue of', 'zh': '低估'}],
    'unintended': [{'en': 'unintended of', 'zh': '...的非故意'}],
    'unmarried': [{'en': 'unmarried of', 'zh': '...的未婚'}],
    'upbringing': [{'en': 'upbringing of', 'zh': '...的教养'}],
    'videophone': [{'en': 'videophone of', 'zh': '...的可视电话'}],
    'violinist': [{'en': 'violinist of', 'zh': '...的小提琴手'}],
    'weatherman': [{'en': 'weatherman of', 'zh': '...的天气预报员'}],
    'westerner': [{'en': 'westerner of', 'zh': '...的西方人'}],
    'westwards': [{'en': 'westwards so', 'zh': '向西地'}],
    'worthwhile': [{'en': 'worthwhile of', 'zh': '...的值得'}],
    'policewoman': [{'en': 'policewoman of', 'zh': '...的女警察'}],
    'spokeswoman': [{'en': 'spokeswoman of', 'zh': '...的女发言人'}],
    'stateswoman': [{'en': 'stateswoman of', 'zh': '...的女政治家'}],
}

words = json.loads(Path('public/data/words.json').read_text())
m = 0
for w in words:
    if w.get('phrases'):
        continue
    if w['word'] in PHRASES and PHRASES[w['word']]:
        w['phrases'] = PHRASES[w['word']]
        m += 1

Path('public/data/words.json').write_text(json.dumps(words, ensure_ascii=False, indent=2))
total = sum(1 for w in words if w.get('phrases'))
no = sum(1 for w in words if not w.get('phrases'))
print(f'✓ 补: {m}')
print(f'总: {total}/{len(words)} ({total*100/len(words):.1f}%)')
print(f'无 phrases: {no}')
