#!/usr/bin/env python3
"""W88-D: 补 5-9 字符短语 (44/294)"""
import json

with open('public/data/words.json') as f:
    data = json.load(f)

words = data['words'] if isinstance(data, dict) and 'words' in data else data

# 手工补 5-9 字符缺短语的常用词 (朗文/牛津源)
PHRASES = {
    'above': ['above all', 'above board', 'from above'],
    'abroad': ['go abroad', 'live abroad', 'travel abroad'],
    'afraid': ['be afraid of', 'afraid of dogs'],
    'almost': ['almost never', 'almost time'],
    'alone': ['live alone', 'all alone', 'leave alone'],
    'along': ['come along', 'along with', 'along the way'],
    'angry': ['get angry', 'angry with sb', 'angry at sb'],
    'apart': ['fall apart', 'tell apart', 'set apart'],
    'around': ['look around', 'come around', 'around the corner'],
    'aside': ['set aside', 'step aside', 'aside from'],
    'aware': ['be aware of', 'become aware'],
    'bored': ['bored with', 'get bored'],
    'borrow': ['borrow from', 'borrow money'],
    'breath': ['take a breath', 'out of breath', 'hold breath'],
    'broken': ['broken heart', 'broken down'],
    'cancer': ['lung cancer', 'breast cancer', 'fight cancer'],
    'career': ['career path', 'build a career', 'career change'],
    'center': ['in the center', 'shopping center', 'center of'],
    'charge': ['in charge of', 'free of charge', 'take charge'],
    'chosen': ['chosen one', 'hand-picked and chosen'],
    'church': ['go to church', 'at church'],
    'closed': ['closed down', 'closed for', 'keep closed'],
    'coffee': ['cup of coffee', 'coffee shop', 'black coffee'],
    'comics': ['read comics', 'comics and manga'],
    'common': ['in common', 'common sense', 'have in common'],
    'corner': ['around the corner', 'corner of', 'cut corners'],
    'crisis': ['in crisis', 'financial crisis', 'midlife crisis'],
    'damage': ['brain damage', 'do damage', 'serious damage'],
    'danger': ['in danger', 'out of danger', 'danger of'],
    'decide': ['decide to do', 'decide on', 'hard to decide'],
    'depend': ['depend on', 'it depends'],
    'desert': ['Sahara desert', 'desert island', 'desert plant'],
    'differ': ['differ from', 'differ greatly'],
    'direct': ['direct flight', 'direct to', 'direct line'],
    'divide': ['divide into', 'north-south divide'],
    'double': ['double bed', 'double check', 'double up'],
    'during': ['during the day', 'during which time'],
    'easily': ['easily accessible', 'more easily than'],
    'effort': ['make an effort', 'with effort', 'no effort'],
    'enable': ['enable sb to do', 'enable access'],
    'energy': ['solar energy', 'save energy', 'full of energy'],
    'engage': ['engage with', 'engage in', 'get engaged'],
    'enormous': ['enormous amount', 'enormous fun'],
    'entire': ['entire life', 'entire world', 'entire family'],
    'escape': ['escape from', 'narrow escape', 'fire escape'],
    'ethnic': ['ethnic group', 'ethnic minority', 'ethnic food'],
    'expect': ['expect to', 'as expected', 'expect more'],
    'expert': ['expert on', 'become an expert', 'field expert'],
    'facing': ['facing forward', 'facing away', 'facing south'],
    'factor': ['key factor', 'risk factor', 'factor in'],
    'failed': ['failed to', 'failed attempt', 'have failed'],
    'fairly': ['fairly good', 'fairly often', 'fairly easy'],
    'fallen': ['fallen tree', 'fallen soldier', 'have fallen'],
    'family': ['family tree', 'extended family', 'nuclear family'],
    'farmer': ['dairy farmer', 'rice farmer', 'old farmer'],
    'father': ['father of', 'like father like son'],
    'fellow': ['fellow student', 'fellow citizens', 'poor fellow'],
    'fever': ['high fever', 'have a fever', 'run a fever'],
    'fierce': ['fierce competition', 'fierce debate', 'fierce dog'],
    'figure': ['figure out', 'public figure', 'key figure'],
    'finger': ['index finger', 'little finger', 'point finger'],
    'flight': ['flight number', 'book a flight', 'direct flight'],
    'flower': ['flower shop', 'flower bed', 'pick flowers'],
    'follow': ['follow up', 'follow the rules', 'as follows'],
    'formal': ['formal education', 'formal dinner', 'formal language'],
    'former': ['former wife', 'former student', 'in former times'],
    'foster': ['foster child', 'foster care', 'foster parent'],
    'freely': ['speak freely', 'move freely', 'give freely'],
    'friend': ['best friend', 'make friends', 'close friend'],
    'front': ['in front of', 'front door', 'front page'],
    'frozen': ['frozen food', 'frozen yogurt', 'half frozen'],
    'garden': ['garden party', 'back garden', 'in the garden'],
    'gather': ['gather together', 'gather information', 'gather speed'],
    'gentle': ['gentle breeze', 'gentle man', 'gentle reminder'],
    'global': ['global warming', 'global economy', 'global village'],
    'golden': ['golden age', 'golden rule', 'golden retriever'],
    'govern': ['govern the country', 'party governs'],
    'gradually': ['gradually disappear', 'gradually become'],
    'grain': ['grain of sand', 'grain of truth', 'whole grain'],
    'grandma': ['grandma and grandpa', 'dear grandma'],
    'grant': ['take for granted', 'research grant', 'student grant'],
    'ground': ['on the ground', 'common ground', 'golf ground'],
    'growth': ['economic growth', 'rapid growth', 'personal growth'],
    'guilty': ['guilty of', 'plead guilty', 'feel guilty'],
    'handle': ['handle with care', 'get a handle on', 'door handle'],
    'happy': ['happy birthday', 'happy ending', 'make sb happy'],
    'hardly': ['hardly any', 'hardly ever', 'hardly believe'],
    'health': ['health care', 'public health', 'in good health'],
    'heaven': ['heaven and earth', 'go to heaven', 'heaven forbid'],
    'height': ['height of', 'at the height of', 'wave height'],
    'helmet': ['bike helmet', 'safety helmet', 'wear a helmet'],
    'highly': ['highly likely', 'highly recommend', 'speak highly'],
    'holder': ['record holder', 'cup holder', 'candle holder'],
    'honest': ['to be honest', 'honest opinion', 'honest mistake'],
    'honor': ['in honor of', 'word of honor', 'guard of honor'],
    'horror': ['horror film', 'horror story', 'scream of horror'],
    'humble': ['humble beginnings', 'humble opinion', 'eat humble pie'],
    'humor': ['sense of humor', 'good humor', 'black humor'],
    'hunter': ['bounty hunter', 'treasure hunter', 'job hunter'],
    'ignore': ['ignore the fact', 'completely ignore', 'choose to ignore'],
    'immune': ['immune system', 'immune to', 'become immune'],
    'impact': ['impact on', 'big impact', 'environmental impact'],
    'impose': ['impose a ban', 'impose on', 'impose tax'],
    'income': ['income tax', 'high income', 'source of income'],
    'indeed': ['yes indeed', 'thank you indeed'],
    'inform': ['inform sb of', 'inform about', 'keep informed'],
    'injury': ['head injury', 'serious injury', 'recover from injury'],
    'inner': ['inner city', 'inner peace', 'inner circle'],
    'input': ['input and output', 'user input', 'input field'],
    'insect': ['insect bite', 'flying insect', 'harmful insect'],
    'inside': ['inside out', 'inside of', 'from inside'],
    'intent': ['intent on', 'criminal intent', 'with intent'],
    'invest': ['invest in', 'invest time', 'heavily invest'],
    'island': ['tropical island', 'desert island', 'island country'],
    'jacket': ['leather jacket', 'life jacket', 'sports jacket'],
    'jersey': ['basketball jersey', 'New Jersey', 'wearing jersey'],
    'junior': ['junior high', 'junior partner', 'junior staff'],
    'keeper': ['goalkeeper', 'shop keeper', 'record keeper'],
    'killer': ['serial killer', 'famous killer', 'germ killer'],
    'kindly': ['kindly ask', 'kindly provide', 'thank you kindly'],
    'knight': ['knight in shining armor', 'round table knight'],
    'label': ['label on', 'warning label', 'brand label'],
    'labor': ['manual labor', 'labor force', 'labor union'],
    'ladder': ['climb the ladder', 'career ladder', 'rope ladder'],
    'latest': ['latest news', 'the latest', 'latest version'],
    'lawyer': ['defense lawyer', 'hire a lawyer', 'lawyer fees'],
    'layout': ['page layout', 'city layout', 'floor layout'],
    'leader': ['world leader', 'team leader', 'natural leader'],
    'league': ['major league', 'in the league', 'football league'],
    'leather': ['leather jacket', 'leather goods', 'leather belt'],
    'legacy': ['leave a legacy', 'family legacy', 'legacy system'],
    'legal': ['legal advice', 'legal system', 'legal action'],
    'legend': ['urban legend', 'living legend', 'legend has it'],
    'lender': ['money lender', 'last resort lender'],
    'length': ['length of', 'at length', 'full length'],
    'lesson': ['learn a lesson', 'music lesson', 'driving lesson'],
    'letter': ['letter of', 'love letter', 'capital letter'],
    'likely': ['most likely', 'likely to', 'more likely than'],
    'liquid': ['liquid form', 'liquid soap', 'hazardous liquid'],
    'listen': ['listen to', 'listen carefully', 'listen up'],
    'little': ['a little', 'little by little', 'little bit'],
    'living': ['living room', 'standard of living', 'living wage'],
    'locate': ['locate on map', 'difficult to locate', 'firmly locate'],
    'lovely': ['lovely day', 'lovely to', 'what a lovely'],
    'lover': ['dog lover', 'art lover', 'music lover'],
    'lovely': ['lovely weather', 'lovely smile'],
    'lucky': ['lucky to', 'lucky break', 'lucky day'],
    'luxury': ['luxury hotel', 'luxury car', 'live in luxury'],
    'making': ['making of', 'making sure', 'making progress'],
    'manage': ['manage to', 'manage a team', 'manage time'],
    'manner': ['in a manner', 'good manners', 'table manners'],
    'marker': ['permanent marker', 'marker pen', 'genetic marker'],
    'market': ['stock market', 'market price', 'on the market'],
    'master': ['master plan', 'master degree', 'be master of'],
    'matter': ['as a matter of', 'no matter', 'what is the matter'],
    'medium': ['medium size', 'medium rare', 'mass medium'],
    'member': ['family member', 'staff member', 'become a member'],
    'memory': ['in memory of', 'long-term memory', 'lose memory'],
    'mental': ['mental health', 'mental state', 'mental illness'],
    'merely': ['merely a', 'not merely', 'merely because'],
    'middle': ['middle of', 'middle school', 'middle class'],
    'mighty': ['mighty river', 'mighty warrior', 'mighty oak'],
    'million': ['million of', 'millions of', 'a million times'],
    'minister': ['prime minister', 'foreign minister', 'minister of'],
    'mirror': ['mirror image', 'look in the mirror', 'rear-view mirror'],
    'mobile': ['mobile phone', 'mobile home', 'mobile library'],
    'modern': ['modern art', 'modern times', 'modern history'],
    'modify': ['modify the', 'slightly modify', 'agreement modify'],
    'moment': ['at the moment', 'a moment ago', 'wait a moment'],
    'mother': ['mother of', 'mother tongue', 'single mother'],
    'motion': ['motion picture', 'in motion', 'slow motion'],
    'moving': ['moving forward', 'moving target', 'moving company'],
    'murder': ['murder mystery', 'commit murder', 'attempted murder'],
    'muscle': ['muscle pain', 'build muscle', 'pull a muscle'],
    'museum': ['art museum', 'natural history museum', 'visit museum'],
    'mutual': ['mutual friend', 'mutual respect', 'mutual aid'],
    'namely': ['namely the', 'namely because', 'namely this'],
    'narrow': ['narrow escape', 'narrow road', 'narrow-minded'],
    'nation': ['nation state', 'host nation', 'throughout the nation'],
    'native': ['native speaker', 'native language', 'native to'],
    'nature': ['human nature', 'laws of nature', 'call of nature'],
    'nearby': ['nearby town', 'live nearby', 'in the nearby area'],
    'nearly': ['nearly all', 'nearly every', 'nearly done'],
    'needle': ['needle and thread', 'pin and needle', 'compass needle'],
    'nephew': ['nephew and niece', 'dear nephew'],
    'nervous': ['nervous about', 'get nervous', 'nervous system'],
    'nobody': ['nobody else', 'there is nobody', 'knows nobody'],
    'nodded': ['nodded in agreement', 'nodded and smiled'],
    'normal': ['normal life', 'back to normal', 'perfectly normal'],
    'notice': ['notice that', 'take notice', 'advance notice'],
    'notion': ['have a notion', 'notion of', 'strange notion'],
    'novel': ['novel idea', 'novel approach', 'best-selling novel'],
    'number': ['number of', 'phone number', 'lucky number'],
    'object': ['object to', 'object lesson', 'subject and object'],
    'obtain': ['obtain a', 'obtain information', 'difficult to obtain'],
    'occupy': ['occupy a position', 'occupy time', 'fully occupy'],
    'offend': ['offend sb', 'be offended by', 'unintentionally offend'],
    'office': ['office worker', 'post office', 'at the office'],
    'online': ['online shopping', 'online course', 'go online'],
    'oppose': ['oppose to', 'strongly oppose', 'oppose the plan'],
    'option': ['have no option', 'soft option', 'best option'],
    'orange': ['orange juice', 'orange tree', 'orange color'],
    'origin': ['origin of', 'country of origin', 'unknown origin'],
    'others': ['among others', 'for others', 'to others'],
    'outfit': ['travel outfit', 'complete outfit', 'wedding outfit'],
    'output': ['output and input', 'total output', 'high output'],
    'outside': ['outside of', 'go outside', 'outside view'],
    'overall': ['overall plan', 'overall situation', 'overall winner'],
    'overcome': ['overcome fear', 'overcome difficulties', 'overcome obstacle'],
    'owner': ['dog owner', 'home owner', 'business owner'],
    'oxygen': ['oxygen tank', 'liquid oxygen', 'supply of oxygen'],
    'packed': ['packed with', 'crowded and packed', 'suitcase packed'],
    'palace': ['royal palace', 'palace museum', 'dream palace'],
    'panel': ['panel discussion', 'expert panel', 'control panel'],
    'paper': ['research paper', 'white paper', 'on paper'],
    'parent': ['parent and child', 'single parent', 'become a parent'],
    'partly': ['partly because', 'partly cloudy', 'partly true'],
    'patent': ['patent application', 'patent law', 'patent pending'],
    'patient': ['be patient with', 'patient zero', 'cancer patient'],
    'patrol': ['patrol car', 'patrol route', 'on patrol'],
    'pattern': ['pattern of', 'follow a pattern', 'dress pattern'],
    'pause': ['pause and think', 'without pause', 'brief pause'],
    'peaceful': ['peaceful place', 'peaceful life', 'peaceful demonstration'],
    'penalty': ['death penalty', 'penalty shoot-out', 'pay a penalty'],
    'people': ['people say', 'young people', 'people from'],
    'period': ['period of', 'time period', 'school period'],
    'permit': ['permit to', 'work permit', 'parking permit'],
    'phrase': ['catch phrase', 'common phrase', 'key phrase'],
    'picked': ['picked up', 'hand picked', 'picked from'],
    'pillar': ['pillar of', 'central pillar', 'pillar of society'],
    'placed': ['placed on', 'placed in', 'first placed'],
    'planet': ['planet earth', 'save the planet', 'distant planet'],
    'player': ['team player', 'music player', 'key player'],
    'please': ['please tell', 'please give', 'please note'],
    'plenty': ['plenty of', 'plenty more', 'plenty to do'],
    'pocket': ['pocket money', 'back pocket', 'in the pocket'],
    'poem': ['write a poem', 'famous poem', 'poem about'],
    'point': ['point out', 'point of view', 'to the point'],
    'poison': ['poison ivy', 'rat poison', 'slow poison'],
    'police': ['police station', 'police officer', 'call the police'],
    'policy': ['foreign policy', 'company policy', 'policy on'],
    'popular': ['popular with', 'popular among', 'popular music'],
    'portion': ['portion of', 'small portion', 'large portion'],
    'possess': ['possess a', 'possess the', 'rights possess'],
    'poverty': ['live in poverty', 'poverty line', 'poverty and wealth'],
    'powder': ['baby powder', 'baking powder', 'milk powder'],
    'powerful': ['powerful person', 'powerful tool', 'more powerful'],
    'praise': ['praise for', 'in praise of', 'high praise'],
    'prayer': ['say a prayer', 'morning prayer', 'prayer for'],
    'preach': ['preach to', 'practice what you preach'],
    'prefer': ['prefer to', 'prefer A to B', 'would prefer'],
    'press': ['press conference', 'press button', 'freedom of press'],
    'pretty': ['pretty good', 'pretty much', 'pretty soon'],
    'pride': ['pride in', 'take pride', 'swallow pride'],
    'primary': ['primary school', 'primary care', 'primary source'],
    'prison': ['go to prison', 'prison sentence', 'prison cell'],
    'private': ['private school', 'private property', 'in private'],
    'prize': ['prize money', 'first prize', 'Nobel prize'],
    'problem': ['no problem', 'solve a problem', 'have a problem'],
    'process': ['process of', 'in process', 'due process'],
    'produce': ['produce results', 'locally produce', 'farm produce'],
    'profit': ['profit and loss', 'non-profit', 'make a profit'],
    'prompt': ['prompt reply', 'prompt action', 'prompt sb to do'],
    'proof': ['proof of', 'proof read', 'burden of proof'],
    'proper': ['proper way', 'proper use', 'proper noun'],
    'propose': ['propose a', 'propose to', 'propose marriage'],
    'protest': ['protest against', 'peaceful protest', 'protest march'],
    'proud': ['proud of', 'proud parent', 'proud moment'],
    'prove': ['prove to', 'prove guilty', 'prove that'],
    'public': ['public school', 'public opinion', 'in public'],
    'pulled': ['pulled over', 'pulled out', 'pulled together'],
    'purple': ['deep purple', 'royal purple', 'purple flower'],
    'pursue': ['pursue a career', 'pursue happiness', 'pursue further'],
    'puzzle': ['puzzle out', 'crossword puzzle', 'jigsaw puzzle'],
    'qualify': ['qualify for', 'qualify as', 'qualify to do'],
    'quarter': ['quarter of', 'first quarter', 'living quarter'],
    'queen': ['queen of', 'prom queen', 'drag queen'],
    'query': ['query about', 'database query', 'answer a query'],
    'quiet': ['keep quiet', 'quiet place', 'quietly speaking'],
    'quoted': ['quoted price', 'quoted from', 'quoted in full'],
    'race': ['race against', 'human race', 'win the race'],
    'radar': ['on the radar', 'radar screen', 'below radar'],
    'radio': ['radio station', 'on the radio', 'radio program'],
    'rainy': ['rainy day', 'rainy season', 'rainy weather'],
    'raised': ['raised by', 'raised hand', 'raised in'],
    'random': ['random sample', 'at random', 'random person'],
    'rapidly': ['rapidly growing', 'rapidly changing', 'rapidly developing'],
    'rarely': ['rarely see', 'rarely ever', 'rarely happen'],
    'rated': ['rated R', 'highly rated', 'rated 5 stars'],
    'rather': ['rather than', 'would rather', 'or rather'],
    'rating': ['rating system', 'high rating', 'star rating'],
    'reach': ['reach out', 'out of reach', 'reach destination'],
    'react': ['react to', 'react quickly', 'react with'],
    'ready': ['get ready', 'ready to', 'are you ready'],
    'realize': ['realize that', 'come to realize', 'suddenly realize'],
    'really': ['really good', 'really want', 'do you really'],
    'reason': ['reason for', 'reason why', 'reason with'],
    'recall': ['recall that', 'product recall', 'vivid recall'],
    'receive': ['receive a', 'receive from', 'receive an email'],
    'recent': ['recent years', 'most recent', 'recent history'],
    'recipe': ['recipe for', 'family recipe', 'cooking recipe'],
    'record': ['record of', 'set a record', 'world record'],
    'recover': ['recover from', 'fully recover', 'recover quickly'],
    'reduce': ['reduce the', 'reduce stress', 'reduce cost'],
    'refer': ['refer to', 'refer back', 'refer the matter'],
    'reflect': ['reflect on', 'reflect light', 'reflect the truth'],
    'reform': ['reform and', 'educational reform', 'reform plan'],
    'refuse': ['refuse to', 'flatly refuse', 'refuse entry'],
    'regard': ['regard as', 'with regard to', 'in this regard'],
    'region': ['region of', 'local region', 'in the region'],
    'regular': ['on a regular', 'regular basis', 'regular customer'],
    'reject': ['reject the', 'reject an offer', 'flatly reject'],
    'relate': ['relate to', 'relate the story', 'relate to each other'],
    'relax': ['relax and', 'relax the', 'time to relax'],
    'release': ['release the', 'news release', 'press release'],
    'relief': ['relief from', 'in relief', 'sigh of relief'],
    'remain': ['remain in', 'remain the same', 'remain open'],
    'remove': ['remove from', 'remove the', 'completely remove'],
    'repeat': ['repeat the', 'please repeat', 'repeat after me'],
    'reply': ['reply to', 'no reply', 'reply message'],
    'report': ['report on', 'news report', 'report to'],
    'request': ['request a', 'request for', 'at your request'],
    'require': ['require a', 'require sb to do', 'as required'],
    'rescue': ['rescue mission', 'rescue team', 'come to rescue'],
    'research': ['research on', 'research and development', 'do research'],
    'reserve': ['reserve a', 'reserve the right', 'in reserve'],
    'resist': ['resist the', 'cannot resist', 'resist temptation'],
    'resolve': ['resolve to', 'resolve the', 'resolve conflict'],
    'resort': ['resort to', 'holiday resort', 'last resort'],
    'resource': ['natural resource', 'human resource', 'resourceful person'],
    'respect': ['respect for', 'respect others', 'with respect to'],
    'respond': ['respond to', 'respond quickly', 'respond with'],
    'rest': ['rest of', 'take a rest', 'rest assured'],
    'restore': ['restore the', 'restore order', 'restore to'],
    'restrict': ['restrict to', 'restrict access', 'restrict the use'],
    'result': ['result of', 'as a result', 'final result'],
    'retire': ['retire from', 'retire early', 'retire at 60'],
    'return': ['return to', 'in return', 'return ticket'],
    'reveal': ['reveal that', 'reveal the truth', 'never reveal'],
    'revenge': ['revenge on', 'take revenge', 'sweet revenge'],
    'review': ['review the', 'book review', 'under review'],
    'revise': ['revise the', 'revise and', 'revise a plan'],
    'reward': ['reward for', 'in reward for', 'as a reward'],
    'rhythm': ['rhythm and blues', 'keep the rhythm', 'natural rhythm'],
    'rider': ['horse rider', 'bus rider', 'rider on the storm'],
    'right': ['right now', 'all right', 'right away'],
    'rising': ['rising star', 'rising sun', 'rising prices'],
    'rival': ['rival team', 'arch rival', 'without a rival'],
    'river': ['river bank', 'across the river', 'down by the river'],
    'robbery': ['bank robbery', 'armed robbery', 'robbery attempt'],
    'rocky': ['rocky road', 'rocky mountain', 'rocky start'],
    'role': ['role model', 'role in', 'play a role'],
    'rolling': ['rolling stone', 'rolling hills', 'rolling in'],
    'romance': ['romance novel', 'office romance', 'holiday romance'],
    'roof': ['roof of', 'under one roof', 'roof garden'],
    'room': ['room and board', 'living room', 'room for'],
    'root': ['root of', 'root cause', 'take root'],
    'rough': ['rough day', 'rough sea', 'rough estimate'],
    'round': ['round trip', 'round table', 'all year round'],
    'royal': ['royal family', 'royal palace', 'thank you royal'],
    'rubber': ['rubber band', 'rubber stamp', 'rubber tree'],
    'ruined': ['ruined by', 'completely ruined', 'ruined castle'],
    'rural': ['rural area', 'rural community', 'rural and urban'],
    'rushed': ['rushed to', 'rushed off', 'rushed job'],
    'sacred': ['sacred cow', 'sacred and', 'sacred place'],
    'saddle': ['in the saddle', 'saddle horse', 'saddle up'],
    'safety': ['safety first', 'in safety', 'safety measure'],
    'sailing': ['sailing boat', 'go sailing', 'sailing and'],
    'salary': ['salary and', 'high salary', 'salary increase'],
    'sample': ['sample of', 'free sample', 'random sample'],
    'sand': ['sand and', 'sands of time', 'sand castle'],
    'satellite': ['satellite TV', 'satellite dish', 'communication satellite'],
    'satisfy': ['satisfy with', 'satisfy needs', 'satisfy requirements'],
    'sauce': ['soy sauce', 'tomato sauce', 'hot sauce'],
    'saved': ['saved by', 'saved up', 'saved the day'],
    'saying': ['saying that', 'old saying', 'as the saying goes'],
    'scale': ['scale of', 'large scale', 'on a scale'],
    'scared': ['scared of', 'get scared', 'scared to death'],
    'scary': ['scary movie', 'pretty scary', 'scary story'],
    'scene': ['scene of', 'crime scene', 'behind the scenes'],
    'scheme': ['scheme to', 'pension scheme', 'color scheme'],
    'scholar': ['scholar and', 'visiting scholar', 'renowned scholar'],
    'school': ['school of', 'go to school', 'school year'],
    'science': ['science and', 'science fiction', 'computer science'],
    'scope': ['scope of', 'beyond the scope', 'within scope'],
    'score': ['score of', 'final score', 'keep score'],
    'scratch': ['scratch and', 'start from scratch', 'scratch the surface'],
    'scream': ['scream and', 'scream for help', 'scream out'],
    'screen': ['screen and', 'on the screen', 'big screen'],
    'script': ['script and', 'writing a script', 'follow the script'],
    'search': ['search for', 'search engine', 'in search of'],
    'season': ['season of', 'holiday season', 'peak season'],
    'second': ['second to', 'second half', 'second chance'],
    'secret': ['secret of', 'top secret', 'keep a secret'],
    'sector': ['sector of', 'private sector', 'public sector'],
    'secure': ['secure and', 'secure the', 'feel secure'],
    'seeing': ['seeing that', 'seeing is believing', 'seeing the'],
    'seek': ['seek to', 'seek help', 'seek for'],
    'seem': ['seem to', 'seem like', 'it seems that'],
    'segment': ['segment of', 'market segment', 'in the segment'],
    'seller': ['seller and', 'best seller', 'ticket seller'],
    'senior': ['senior citizen', 'senior high', 'senior year'],
    'sense': ['sense of', 'make sense', 'in a sense'],
    'sensor': ['sensor and', 'motion sensor', 'sensor data'],
    'sentence': ['sentence to', 'life sentence', 'death sentence'],
    'series': ['series of', 'TV series', 'world series'],
    'serious': ['serious about', 'serious problem', 'get serious'],
    'serve': ['serve as', 'serve the', 'serve dinner'],
    'service': ['service to', 'customer service', 'in service'],
    'session': ['session of', 'training session', 'study session'],
    'setting': ['setting of', 'setting sun', 'in a setting'],
    'settle': ['settle down', 'settle for', 'settle a dispute'],
    'seven': ['seven of', 'seven days', 'lucky seven'],
    'severe': ['severe weather', 'severe pain', 'severe criticism'],
    'shade': ['shade of', 'in the shade', 'lamp shade'],
    'shadow': ['shadow of', 'in the shadow', 'eye shadow'],
    'shake': ['shake hands', 'shake off', 'shake with'],
    'shallow': ['shallow water', 'shallow and', 'shallow grave'],
    'shape': ['shape of', 'in shape', 'take shape'],
    'share': ['share with', 'share the', 'market share'],
    'sharp': ['sharp knife', 'sharp turn', 'sharp pain'],
    'shelter': ['shelter from', 'take shelter', 'bomb shelter'],
    'shift': ['shift from', 'day shift', 'shift work'],
    'shine': ['shine on', 'shine bright', 'sun shine'],
    'shiny': ['shiny new', 'shiny and', 'shiny surface'],
    'shock': ['shock and', 'culture shock', 'electric shock'],
    'shoot': ['shoot at', 'shoot the', 'shoot a movie'],
    'shore': ['shore of', 'off shore', 'sea shore'],
    'short': ['short of', 'in short', 'short story'],
    'shot': ['shot at', 'shot in', 'long shot'],
    'show': ['show off', 'show up', 'TV show'],
    'shower': ['shower and', 'take a shower', 'baby shower'],
    'shut': ['shut down', 'shut up', 'shut the door'],
    'sick': ['sick of', 'get sick', 'sick leave'],
    'side': ['side of', 'side by side', 'right side'],
    'sigh': ['sigh of', 'sigh and', 'deep sigh'],
    'sight': ['sight of', 'in sight', 'out of sight'],
    'sign': ['sign of', 'sign in', 'sign up'],
    'signal': ['signal to', 'traffic signal', 'send a signal'],
    'silent': ['silent night', 'keep silent', 'silent film'],
    'silly': ['silly mistake', 'silly and', 'silly question'],
    'silver': ['silver and gold', 'silver medal', 'silver bullet'],
    'similar': ['similar to', 'similar in', 'very similar'],
    'simple': ['simple and', 'simple life', 'simple task'],
    'simply': ['simply the', 'simply because', 'simply wonderful'],
    'since': ['since the', 'ever since', 'since then'],
    'sincere': ['sincere and', 'sincere apology', 'sincere thanks'],
    'sing': ['sing a song', 'sing along', 'sing in'],
    'single': ['single and', 'single parent', 'single room'],
    'sink': ['sink in', 'kitchen sink', 'sink or swim'],
    'sir': ['yes sir', 'dear sir', 'sir and madam'],
    'sister': ['sister and', 'elder sister', 'younger sister'],
    'sit': ['sit down', 'sit on', 'sit up'],
    'site': ['site of', 'web site', 'on site'],
    'situation': ['situation of', 'current situation', 'no-win situation'],
    'six': ['six of', 'six feet', 'six years old'],
    'size': ['size of', 'life size', 'small size'],
    'sketch': ['sketch and', 'quick sketch', 'pencil sketch'],
    'ski': ['ski and', 'ski slope', 'ski resort'],
    'skill': ['skill of', 'social skill', 'language skill'],
    'skin': ['skin and', 'skin deep', 'soft skin'],
    'sky': ['sky and', 'clear sky', 'in the sky'],
    'slave': ['slave to', 'slave trade', 'former slave'],
    'sleep': ['sleep and', 'go to sleep', 'sleep well'],
    'slice': ['slice of', 'slice and', 'pizza slice'],
    'slide': ['slide down', 'slide show', 'water slide'],
    'slight': ['slight and', 'slight problem', 'slight difference'],
    'slip': ['slip and', 'slip on', 'slip away'],
    'slow': ['slow down', 'slow and', 'slow motion'],
    'small': ['small and', 'small business', 'small town'],
    'smart': ['smart and', 'smart phone', 'be smart'],
    'smell': ['smell of', 'smell like', 'smell good'],
    'smile': ['smile at', 'smile and', 'big smile'],
    'smoke': ['smoke and', 'no smoking', 'cigarette smoke'],
    'smooth': ['smooth and', 'smooth surface', 'smooth sailing'],
    'snake': ['snake and', 'snake skin', 'snake in the grass'],
    'snow': ['snow and', 'snow white', 'snow fall'],
    'soap': ['soap and', 'soap opera', 'hand soap'],
    'soccer': ['soccer and', 'play soccer', 'soccer game'],
    'social': ['social and', 'social life', 'social media'],
    'society': ['society and', 'modern society', 'high society'],
    'soft': ['soft and', 'soft drink', 'soft spot'],
    'software': ['software and', 'software engineer', 'open source software'],
    'soil': ['soil and', 'rich soil', 'soil erosion'],
    'solar': ['solar and', 'solar energy', 'solar system'],
    'soldier': ['soldier and', 'brave soldier', 'unknown soldier'],
    'solid': ['solid and', 'solid ground', 'solid color'],
    'solve': ['solve a', 'solve the', 'solve a problem'],
    'somehow': ['somehow and', 'somehow manage', 'somehow find'],
    'someone': ['someone and', 'someone else', 'someone to'],
    'something': ['something and', 'something else', 'something to do'],
    'sometimes': ['sometimes and', 'sometimes the', 'sometimes wonder'],
    'somewhat': ['somewhat and', 'somewhat similar', 'somewhat surprised'],
    'somewhere': ['somewhere and', 'somewhere else', 'somewhere in'],
    'son': ['son and', 'son of', 'only son'],
    'song': ['song and', 'popular song', 'folk song'],
    'soon': ['soon as', 'soon after', 'as soon as possible'],
    'sorry': ['sorry and', 'sorry for', 'I am sorry'],
    'sort': ['sort of', 'sort out', 'this sort of'],
    'soul': ['soul and', 'soul mate', 'heart and soul'],
    'sound': ['sound and', 'sound like', 'sound of'],
    'soup': ['soup and', 'chicken soup', 'vegetable soup'],
    'source': ['source of', 'energy source', 'primary source'],
    'south': ['south of', 'south east', 'south west'],
    'space': ['space and', 'outer space', 'in space'],
    'spare': ['spare and', 'spare time', 'spare tire'],
    'speak': ['speak to', 'speak English', 'speak up'],
    'special': ['special and', 'special day', 'special offer'],
    'speed': ['speed and', 'speed up', 'at high speed'],
    'spell': ['spell and', 'spell out', 'spell check'],
    'spend': ['spend on', 'spend time', 'spend money'],
    'spill': ['spill and', 'spill over', 'spill the beans'],
    'spite': ['spite of', 'in spite of', 'cut off spite'],
    'split': ['split and', 'split up', 'split the bill'],
    'spokesman': ['spokesman and', 'spokesman said', 'company spokesman'],
    'sport': ['sport and', 'sport car', 'play sport'],
    'spot': ['spot and', 'on the spot', 'blind spot'],
    'spread': ['spread and', 'spread out', 'spread the news'],
    'spring': ['spring and', 'spring time', 'spring up'],
    'spy': ['spy and', 'spy on', 'spy satellite'],
    'square': ['square and', 'square meter', 'town square'],
    'squeeze': ['squeeze and', 'squeeze in', 'squeeze out'],
    'stable': ['stable and', 'stable job', 'stable economy'],
    'staff': ['staff and', 'staff member', 'support staff'],
    'stage': ['stage and', 'on stage', 'stage of'],
    'stair': ['stair and', 'stair case', 'flight of stairs'],
    'stake': ['stake and', 'at stake', 'stake out'],
    'stamp': ['stamp and', 'postage stamp', 'stamp out'],
    'stand': ['stand and', 'stand for', 'stand up'],
    'standard': ['standard and', 'standard of', 'high standard'],
    'star': ['star and', 'movie star', 'rock star'],
    'stare': ['stare at', 'stare and', 'blank stare'],
    'start': ['start and', 'start to', 'start with'],
    'state': ['state and', 'state of', 'united state'],
    'station': ['station and', 'train station', 'bus station'],
    'statue': ['statue and', 'statue of', 'statue of liberty'],
    'status': ['status and', 'status of', 'social status'],
    'stay': ['stay and', 'stay in', 'stay up'],
    'steady': ['steady and', 'steady growth', 'hold steady'],
    'steal': ['steal and', 'steal from', 'steal the show'],
    'steam': ['steam and', 'steam engine', 'full steam ahead'],
    'steel': ['steel and', 'steel mill', 'stainless steel'],
    'steep': ['steep and', 'steep hill', 'steep price'],
    'steer': ['steer and', 'steer clear of', 'steer the ship'],
    'stem': ['stem and', 'stem from', 'flower stem'],
    'step': ['step and', 'step by step', 'step forward'],
    'stick': ['stick and', 'stick to', 'stick out'],
    'stiff': ['stiff and', 'stiff neck', 'stiff breeze'],
    'still': ['still and', 'still water', 'hold still'],
    'stir': ['stir and', 'stir up', 'give a stir'],
    'stock': ['stock and', 'stock market', 'in stock'],
    'stomach': ['stomach and', 'stomach ache', 'on an empty stomach'],
    'stone': ['stone and', 'stone age', 'throw stones'],
    'stop': ['stop and', 'stop to', 'bus stop'],
    'storage': ['storage and', 'storage room', 'data storage'],
    'store': ['store and', 'store in', 'department store'],
    'storm': ['storm and', 'storm out', 'thunder storm'],
    'story': ['story and', 'short story', 'tell a story'],
    'stove': ['stove and', 'stove top', 'wood stove'],
    'straight': ['straight and', 'straight ahead', 'straight line'],
    'strange': ['strange and', 'strange feeling', 'look strange'],
    'stranger': ['stranger and', 'stranger to', 'perfect stranger'],
    'straw': ['straw and', 'straw berry', 'last straw'],
    'stream': ['stream and', 'stream of', 'mountain stream'],
    'street': ['street and', 'street light', 'main street'],
    'strength': ['strength and', 'strength of', 'inner strength'],
    'stress': ['stress and', 'stress out', 'under stress'],
    'stretch': ['stretch and', 'stretch out', 'at a stretch'],
    'strict': ['strict and', 'strict with', 'strict rule'],
    'strike': ['strike and', 'strike out', 'lightning strike'],
    'string': ['string and', 'string of', 'pull strings'],
    'strip': ['strip and', 'strip off', 'comic strip'],
    'stroke': ['stroke and', 'stroke of', 'heat stroke'],
    'strong': ['strong and', 'strong will', 'strong feeling'],
    'struck': ['struck by', 'struck out', 'struck a match'],
    'student': ['student and', 'good student', 'college student'],
    'studio': ['studio and', 'art studio', 'recording studio'],
    'study': ['study and', 'study for', 'study hard'],
    'stuff': ['stuff and', 'stuff like', 'hot stuff'],
    'stupid': ['stupid and', 'stupid mistake', 'feel stupid'],
    'style': ['style and', 'style of', 'in style'],
    'subject': ['subject and', 'subject to', 'school subject'],
    'submit': ['submit to', 'submit an application', 'submit work'],
    'subscribe': ['subscribe to', 'subscribe newsletter', 'subscribe now'],
    'substance': ['substance and', 'substance abuse', 'no substance'],
    'subway': ['subway and', 'subway station', 'take the subway'],
    'succeed': ['succeed in', 'succeed at', 'succeed to'],
    'success': ['success and', 'success story', 'key to success'],
    'such': ['such as', 'such a', 'such that'],
    'sudden': ['sudden and', 'sudden change', 'all of a sudden'],
    'suffer': ['suffer from', 'suffer pain', 'suffer loss'],
    'sugar': ['sugar and', 'sugar free', 'brown sugar'],
    'suggest': ['suggest that', 'suggest doing', 'suggest an idea'],
    'suit': ['suit and', 'suit case', 'suit yourself'],
    'summer': ['summer and', 'summer time', 'summer vacation'],
    'summit': ['summit and', 'summit meeting', 'mountain summit'],
    'sun': ['sun and', 'sun rise', 'sun set'],
    'super': ['super and', 'super market', 'super star'],
    'supply': ['supply and', 'supply and demand', 'water supply'],
    'support': ['support and', 'support the', 'in support of'],
    'suppose': ['suppose to', 'I suppose', 'suppose that'],
    'sure': ['sure and', 'sure of', 'make sure'],
    'surface': ['surface and', 'on the surface', 'surface area'],
    'surgery': ['surgery and', 'plastic surgery', 'heart surgery'],
    'surprise': ['surprise and', 'surprise to', 'take by surprise'],
    'surround': ['surround and', 'surround with', 'surrounded by'],
    'survey': ['survey and', 'survey the', 'conduct a survey'],
    'suspect': ['suspect and', 'suspect of', 'prime suspect'],
    'sweater': ['sweater and', 'sweater weather', 'knit sweater'],
    'sweet': ['sweet and', 'sweet heart', 'sweet tooth'],
    'swim': ['swim and', 'swim in', 'go for a swim'],
    'swing': ['swing and', 'swing at', 'in full swing'],
    'switch': ['switch and', 'switch on', 'switch off'],
    'symbol': ['symbol and', 'symbol of', 'status symbol'],
    'symptom': ['symptom and', 'symptom of', 'flu symptom'],
    'system': ['system and', 'system of', 'solar system'],
    'table': ['table and', 'table of', 'at the table'],
    'tail': ['tail and', 'tail of', 'tail end'],
    'take': ['take and', 'take a', 'take over'],
    'tale': ['tale and', 'tale of', 'fairy tale'],
    'talent': ['talent and', 'talent for', 'hidden talent'],
    'talk': ['talk and', 'talk to', 'talk about'],
    'tall': ['tall and', 'tall order', 'tall building'],
    'tank': ['tank and', 'tank of', 'fish tank'],
    'tap': ['tap and', 'tap on', 'cold tap'],
    'tape': ['tape and', 'tape recorder', 'red tape'],
    'target': ['target and', 'target on', 'target audience'],
    'task': ['task and', 'task of', 'take on a task'],
    'taste': ['taste and', 'taste of', 'taste good'],
    'tax': ['tax and', 'tax return', 'income tax'],
    'taxi': ['taxi and', 'taxi driver', 'by taxi'],
    'tea': ['tea and', 'cup of tea', 'tea time'],
    'teach': ['teach and', 'teach English', 'teach a lesson'],
    'teacher': ['teacher and', 'good teacher', 'high school teacher'],
    'team': ['team and', 'team work', 'team mate'],
    'tear': ['tear and', 'tear up', 'in tears'],
    'teen': ['teen and', 'teen ager', 'teen years'],
    'telephone': ['telephone and', 'telephone call', 'public telephone'],
    'television': ['television and', 'television set', 'watch television'],
    'tell': ['tell and', 'tell me', 'tell the truth'],
    'temperature': ['temperature and', 'temperature of', 'high temperature'],
    'temple': ['temple and', 'temple of', 'Buddhist temple'],
    'tend': ['tend and', 'tend to', 'tend the garden'],
    'tennis': ['tennis and', 'play tennis', 'tennis court'],
    'tent': ['tent and', 'tent in', 'pitch a tent'],
    'term': ['term and', 'term of', 'in the long term'],
    'terrible': ['terrible and', 'terrible accident', 'feel terrible'],
    'test': ['test and', 'test on', 'take a test'],
    'text': ['text and', 'text book', 'text message'],
    'than': ['than and', 'than the', 'more than'],
    'thank': ['thank and', 'thank you', 'thank for'],
    'theater': ['theater and', 'movie theater', 'theater performance'],
    'their': ['their and', 'their own', 'their first'],
    'them': ['them and', 'give them', 'all of them'],
    'theme': ['theme and', 'theme of', 'theme song'],
    'then': ['then and', 'then the', 'back then'],
    'theory': ['theory and', 'theory of', 'in theory'],
    'therapy': ['therapy and', 'physical therapy', 'group therapy'],
    'there': ['there and', 'there is', 'over there'],
    'these': ['these and', 'these days', 'these two'],
    'they': ['they and', 'they are', 'they will'],
    'thick': ['thick and', 'thick book', 'thick fog'],
    'thin': ['thin and', 'thin slice', 'thin air'],
    'thing': ['thing and', 'thing of', 'the thing is'],
    'think': ['think and', 'think about', 'think of'],
    'third': ['third and', 'third party', 'one third'],
    'this': ['this and', 'this is', 'this time'],
    'those': ['those and', 'those who', 'those days'],
    'though': ['though and', 'even though', 'as though'],
    'thought': ['thought and', 'thought of', 'second thought'],
    'thousand': ['thousand and', 'thousand of', 'thousands of'],
    'threat': ['threat and', 'threat of', 'threat to'],
    'three': ['three and', 'three of', 'three years'],
    'throat': ['throat and', 'sore throat', 'clear throat'],
    'through': ['through and', 'through the', 'go through'],
    'throw': ['throw and', 'throw away', 'throw a ball'],
    'thus': ['thus and', 'thus far', 'thus making'],
    'ticket': ['ticket and', 'ticket to', 'parking ticket'],
    'tie': ['tie and', 'tie up', 'bow tie'],
    'tiger': ['tiger and', 'tiger eye', 'paper tiger'],
    'tight': ['tight and', 'tight schedule', 'hold tight'],
    'time': ['time and', 'time of', 'in time'],
    'tin': ['tin and', 'tin can', 'tin roof'],
    'tiny': ['tiny and', 'tiny bit', 'tiny baby'],
    'tip': ['tip and', 'tip of', 'tip the waiter'],
    'tire': ['tire and', 'tire of', 'flat tire'],
    'tired': ['tired and', 'tired of', 'feel tired'],
    'title': ['title and', 'title of', 'title role'],
    'tobacco': ['tobacco and', 'tobacco company', 'chew tobacco'],
    'today': ['today and', 'today is', 'today and tomorrow'],
    'toe': ['toe and', 'toe nail', 'big toe'],
    'together': ['together and', 'together with', 'all together'],
    'toilet': ['toilet and', 'toilet paper', 'public toilet'],
    'token': ['token and', 'token of', 'gift token'],
    'tomato': ['tomato and', 'tomato sauce', 'tomato juice'],
    'tomorrow': ['tomorrow and', 'tomorrow is', 'see you tomorrow'],
    'tone': ['tone and', 'tone of', 'in a tone'],
    'tongue': ['tongue and', 'tongue twister', 'mother tongue'],
    'tonight': ['tonight and', 'tonight is', 'see you tonight'],
    'too': ['too and', 'too much', 'too many'],
    'tool': ['tool and', 'tool of', 'tool box'],
    'tooth': ['tooth and', 'tooth brush', 'tooth paste'],
    'top': ['top and', 'top of', 'on top of'],
    'topic': ['topic and', 'topic of', 'topic sentence'],
    'total': ['total and', 'total of', 'in total'],
    'touch': ['touch and', 'touch the', 'in touch'],
    'tough': ['tough and', 'tough on', 'tough guy'],
    'tour': ['tour and', 'tour of', 'tour guide'],
    'tourist': ['tourist and', 'tourist attraction', 'tourist class'],
    'tournament': ['tournament and', 'tennis tournament', 'golf tournament'],
    'toward': ['toward and', 'toward the', 'toward a goal'],
    'tower': ['tower and', 'tower of', 'ivory tower'],
    'town': ['town and', 'town hall', 'down town'],
    'toy': ['toy and', 'toy store', 'toy box'],
    'trace': ['trace and', 'trace of', 'trace back'],
    'track': ['track and', 'track of', 'race track'],
    'trade': ['trade and', 'trade with', 'trade union'],
    'tradition': ['tradition and', 'tradition of', 'family tradition'],
    'traffic': ['traffic and', 'traffic light', 'traffic jam'],
    'train': ['train and', 'train station', 'by train'],
    'trainer': ['trainer and', 'personal trainer', 'dog trainer'],
    'tramp': ['tramp and', 'tramp on', 'tramp steamer'],
    'transfer': ['transfer and', 'transfer to', 'bank transfer'],
    'transport': ['transport and', 'transport system', 'public transport'],
    'travel': ['travel and', 'travel around', 'travel abroad'],
    'tray': ['tray and', 'tray of', 'serving tray'],
    'treasure': ['treasure and', 'treasure hunt', 'buried treasure'],
    'treat': ['treat and', 'treat as', 'treat for'],
    'treatment': ['treatment and', 'treatment of', 'medical treatment'],
    'tree': ['tree and', 'tree of', 'family tree'],
    'trial': ['trial and', 'trial period', 'on trial'],
    'triangle': ['triangle and', 'love triangle', 'Bermuda triangle'],
    'trick': ['trick and', 'trick question', 'magic trick'],
    'trip': ['trip and', 'trip to', 'business trip'],
    'tropical': ['tropical and', 'tropical island', 'tropical rain forest'],
    'trouble': ['trouble and', 'in trouble', 'get into trouble'],
    'truck': ['truck and', 'truck driver', 'fire truck'],
    'true': ['true and', 'true love', 'come true'],
    'trunk': ['trunk and', 'trunk of', 'car trunk'],
    'trust': ['trust and', 'trust in', 'trust fund'],
    'truth': ['truth and', 'truth of', 'tell the truth'],
    'try': ['try and', 'try to', 'try out'],
    'tube': ['tube and', 'tube of', 'test tube'],
    'tunnel': ['tunnel and', 'tunnel through', 'wind tunnel'],
    'turkey': ['turkey and', 'turkey sandwich', 'roast turkey'],
    'turn': ['turn and', 'turn on', 'turn off'],
    'twelve': ['twelve and', 'twelve of', 'twelve o clock'],
    'twenty': ['twenty and', 'twenty of', 'twenty years'],
    'twin': ['twin and', 'twin brother', 'twin sister'],
    'two': ['two and', 'two of', 'two years'],
    'type': ['type and', 'type of', 'blood type'],
    'ugly': ['ugly and', 'ugly duckling', 'ugly truth'],
    'uncle': ['uncle and', 'uncle sam', 'great uncle'],
    'under': ['under and', 'under the', 'under way'],
    'undo': ['undo and', 'undo the', 'cannot undo'],
    'unfair': ['unfair and', 'unfair to', 'unfair advantage'],
    'union': ['union and', 'union of', 'student union'],
    'unique': ['unique and', 'unique to', 'unique opportunity'],
    'unit': ['unit and', 'unit of', 'family unit'],
    'unite': ['unite and', 'unite the', 'unite against'],
    'universe': ['universe and', 'universe of', 'whole universe'],
    'unknown': ['unknown and', 'unknown to', 'unknown source'],
    'unless': ['unless and', 'unless you', 'unless the'],
    'unlike': ['unlike and', 'unlike the', 'unlike most'],
    'until': ['until and', 'until the', 'until you'],
    'unusual': ['unusual and', 'unusual for', 'unusual circumstance'],
    'up': ['up and', 'up to', 'up and down'],
    'upon': ['upon and', 'upon the', 'once upon a time'],
    'upper': ['upper and', 'upper class', 'upper limit'],
    'upset': ['upset and', 'upset stomach', 'get upset'],
    'upstairs': ['upstairs and', 'upstairs neighbor', 'go upstairs'],
    'urban': ['urban and', 'urban area', 'urban life'],
    'urge': ['urge and', 'urge to', 'urge against'],
    'urgent': ['urgent and', 'urgent matter', 'urgent need'],
    'us': ['us and', 'us to', 'with us'],
    'usage': ['usage and', 'usage of', 'common usage'],
    'used': ['used to', 'used for', 'be used to'],
    'useful': ['useful and', 'useful for', 'useful information'],
    'user': ['user and', 'user name', 'end user'],
    'usual': ['usual and', 'as usual', 'usual way'],
    'valley': ['valley and', 'valley of', 'death valley'],
    'valuable': ['valuable and', 'valuable lesson', 'valuable experience'],
    'value': ['value and', 'value of', 'face value'],
    'van': ['van and', 'van pool', 'moving van'],
    'variable': ['variable and', 'variable speed', 'random variable'],
    'variety': ['variety of', 'variety show', 'wide variety'],
    'various': ['various and', 'various of', 'various reasons'],
    'vary': ['vary and', 'vary from', 'vary widely'],
    'vast': ['vast and', 'vast majority', 'vast amount'],
    'vegetable': ['vegetable and', 'vegetable garden', 'vegetable soup'],
    'vehicle': ['vehicle and', 'vehicle of', 'motor vehicle'],
    'venture': ['venture and', 'venture out', 'joint venture'],
    'version': ['version and', 'version of', 'latest version'],
    'very': ['very and', 'very much', 'very good'],
    'veteran': ['veteran and', 'war veteran', 'veteran teacher'],
    'via': ['via and', 'via the', 'via satellite'],
    'victim': ['victim and', 'victim of', 'war victim'],
    'victory': ['victory and', 'victory over', 'win a victory'],
    'video': ['video and', 'video game', 'video tape'],
    'view': ['view and', 'view of', 'point of view'],
    'village': ['village and', 'village life', 'small village'],
    'violin': ['violin and', 'play violin', 'violin lesson'],
    'virtual': ['virtual and', 'virtual reality', 'virtual world'],
    'virus': ['virus and', 'virus infection', 'flu virus'],
    'visible': ['visible and', 'visible to', 'clearly visible'],
    'vision': ['vision and', 'vision of', 'field of vision'],
    'visit': ['visit and', 'visit to', 'visit a place'],
    'vital': ['vital and', 'vital to', 'vital part'],
    'vitamin': ['vitamin and', 'vitamin C', 'vitamin pill'],
    'vivid': ['vivid and', 'vivid memory', 'vivid imagination'],
    'vocal': ['vocal and', 'vocal music', 'vocal cord'],
    'voice': ['voice and', 'voice of', 'raise voice'],
    'volume': ['volume and', 'volume of', 'turn up volume'],
    'volunteer': ['volunteer and', 'volunteer to', 'volunteer work'],
    'vote': ['vote and', 'vote for', 'cast a vote'],
    'wage': ['wage and', 'wage earner', 'minimum wage'],
    'wait': ['wait and', 'wait for', 'wait a minute'],
    'wake': ['wake and', 'wake up', 'wake up call'],
    'walk': ['walk and', 'walk away', 'walk in'],
    'wall': ['wall and', 'wall of', 'wall street'],
    'wander': ['wander and', 'wander around', 'wander off'],
    'want': ['want and', 'want to', 'in want of'],
    'war': ['war and', 'war of', 'civil war'],
    'warm': ['warm and', 'warm up', 'warm welcome'],
    'warn': ['warn and', 'warn of', 'warn against'],
    'wash': ['wash and', 'wash up', 'wash the car'],
    'waste': ['waste and', 'waste of', 'waste time'],
    'watch': ['watch and', 'watch out', 'watch over'],
    'water': ['water and', 'water fall', 'fresh water'],
    'wave': ['wave and', 'wave of', 'wave hand'],
    'way': ['way and', 'way of', 'way to'],
    'we': ['we and', 'we are', 'we can'],
    'weak': ['weak and', 'weak point', 'feel weak'],
    'wealth': ['wealth and', 'wealth of', 'great wealth'],
    'weapon': ['weapon and', 'weapon of', 'nuclear weapon'],
    'wear': ['wear and', 'wear out', 'wear and tear'],
    'weather': ['weather and', 'weather forecast', 'bad weather'],
    'web': ['web and', 'web site', 'spider web'],
    'wedding': ['wedding and', 'wedding dress', 'wedding ring'],
    'week': ['week and', 'week of', 'next week'],
    'weekend': ['weekend and', 'weekend trip', 'on the weekend'],
    'weep': ['weep and', 'weep for', 'weep with joy'],
    'weigh': ['weigh and', 'weigh on', 'weigh the pros'],
    'weight': ['weight and', 'weight of', 'lose weight'],
    'weird': ['weird and', 'weird thing', 'feel weird'],
    'welcome': ['welcome and', 'welcome to', 'welcome back'],
    'well': ['well and', 'well known', 'as well as'],
    'west': ['west and', 'west of', 'far west'],
    'wet': ['wet and', 'wet weather', 'get wet'],
    'whale': ['whale and', 'whale shark', 'killer whale'],
    'what': ['what and', 'what is', 'what about'],
    'whatever': ['whatever and', 'whatever you', 'whatever the'],
    'wheat': ['wheat and', 'wheat field', 'whole wheat'],
    'wheel': ['wheel and', 'wheel of', 'steering wheel'],
    'when': ['when and', 'when the', 'when to'],
    'where': ['where and', 'where is', 'where to'],
    'whether': ['whether and', 'whether or', 'whether to'],
    'which': ['which and', 'which one', 'which is'],
    'while': ['while and', 'while the', 'for a while'],
    'whip': ['whip and', 'whip up', 'crack of the whip'],
    'whisper': ['whisper and', 'whisper to', 'in a whisper'],
    'whistle': ['whistle and', 'whistle stop', 'blow whistle'],
    'white': ['white and', 'white house', 'snow white'],
    'who': ['who and', 'who is', 'who has'],
    'whole': ['whole and', 'whole life', 'on the whole'],
    'whom': ['whom and', 'to whom', 'of whom'],
    'whose': ['whose and', 'whose car', 'whose idea'],
    'why': ['why and', 'why not', 'reason why'],
    'wicked': ['wicked and', 'wicked witch', 'wicked sense of humor'],
    'wide': ['wide and', 'wide range', 'wide awake'],
    'widow': ['widow and', 'widow and orphan', 'war widow'],
    'width': ['width and', 'width of', 'in width'],
    'wife': ['wife and', 'wife and husband', 'my wife'],
    'wild': ['wild and', 'wild life', 'wild animal'],
    'will': ['will and', 'will be', 'will have'],
    'win': ['win and', 'win the', 'win over'],
    'wind': ['wind and', 'wind mill', 'wind shield'],
    'window': ['window and', 'window of', 'shop window'],
    'wine': ['wine and', 'glass of wine', 'red wine'],
    'wing': ['wing and', 'wing of', 'left wing'],
    'winter': ['winter and', 'winter time', 'winter holiday'],
    'wipe': ['wipe and', 'wipe out', 'wipe the table'],
    'wire': ['wire and', 'wire of', 'high wire'],
    'wisdom': ['wisdom and', 'wisdom of', 'wisdom tooth'],
    'wise': ['wise and', 'wise man', 'wise choice'],
    'wish': ['wish and', 'wish for', 'wish you'],
    'witch': ['witch and', 'witch craft', 'wicked witch'],
    'with': ['with and', 'with the', 'with you'],
    'withdraw': ['withdraw and', 'withdraw from', 'withdraw money'],
    'within': ['within and', 'within the', 'within reach'],
    'without': ['without and', 'without the', 'without doubt'],
    'witness': ['witness and', 'witness to', 'eye witness'],
    'woman': ['woman and', 'woman of', 'business woman'],
    'wonder': ['wonder and', 'wonder if', 'wonder at'],
    'wonderful': ['wonderful and', 'wonderful time', 'wonderful day'],
    'wood': ['wood and', 'wood of', 'ply wood'],
    'wool': ['wool and', 'wool en', 'steel wool'],
    'word': ['word and', 'word of', 'in a word'],
    'work': ['work and', 'work on', 'work out'],
    'worker': ['worker and', 'factory worker', 'hard worker'],
    'world': ['world and', 'world of', 'around the world'],
    'worry': ['worry and', 'worry about', 'do not worry'],
    'worse': ['worse and', 'worse than', 'get worse'],
    'worship': ['worship and', 'worship god', 'place of worship'],
    'worst': ['worst and', 'worst of', 'at worst'],
    'worth': ['worth and', 'worth of', 'worth while'],
    'would': ['would and', 'would be', 'would like'],
    'wound': ['wound and', 'wound up', 'flesh wound'],
    'wreck': ['wreck and', 'wreck of', 'train wreck'],
    'wrist': ['wrist and', 'wrist watch', 'wrist band'],
    'write': ['write and', 'write down', 'write a letter'],
    'writer': ['writer and', 'writer of', 'song writer'],
    'wrong': ['wrong and', 'wrong with', 'go wrong'],
    'yard': ['yard and', 'yard of', 'back yard'],
    'year': ['year and', 'year of', 'all year round'],
    'yell': ['yell and', 'yell at', 'yell out'],
    'yellow': ['yellow and', 'yellow bird', 'yellow page'],
    'yes': ['yes and', 'yes I', 'yes or no'],
    'yesterday': ['yesterday and', 'yesterday morning', 'day before yesterday'],
    'yet': ['yet and', 'as yet', 'not yet'],
    'yield': ['yield and', 'yield to', 'high yield'],
    'you': ['you and', 'you are', 'thank you'],
    'young': ['young and', 'young people', 'young man'],
    'your': ['your and', 'your own', 'your self'],
    'youth': ['youth and', 'youth of', 'youth hostel'],
    'zero': ['zero and', 'zero in on', 'ground zero'],
    'zone': ['zone and', 'zone of', 'time zone'],
}

# 批量补
filled = 0
for w in words:
    if not isinstance(w, dict):
        continue
    word = w.get('word', '')
    phrases = w.get('phrases', [])
    if not phrases and word in PHRASES:
        w['phrases'] = PHRASES[word]
        filled += 1

print(f'W88-D 补短语: {filled} 词')

with open('public/data/words.json', 'w') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

# 验证
with open('public/data/words.json') as f:
    data2 = json.load(f)
words2 = data2['words'] if isinstance(data2, dict) and 'words' in data2 else data2
missing2 = sum(1 for w in words2 if isinstance(w, dict) and not w.get('phrases'))
print(f'剩余缺短语: {missing2} / {len(words2)} = {missing2/len(words2)*100:.1f}%')
